"""
DeLector - Offline Goethe CEFR Vocabulary Core Dictionary
High-frequency German-Chinese dictionary with accurate lemma, POS, gender (der/die/das),
plural endings, CEFR level, and concise Chinese definitions.
O(1) memory lookup for zero-latency token inspection and CEFR difficulty tagging.
"""
from typing import Optional, Dict, Any

# Structure: lemma -> (cefr, pos, gender, plural, definition_zh)
CORE_VOCAB_DB: Dict[str, tuple] = {
    # ── A1 Core Nouns ──────────────────────────────────────────────────────────
    "tag": ("A1", "NOUN", "Masc", "-e", "白天，日子，一天"),
    "morgen": ("A1", "NOUN", "Masc", "-", "早晨，上午"),
    "abend": ("A1", "NOUN", "Masc", "-e", "傍晚，晚上"),
    "nacht": ("A1", "NOUN", "Fem", "-..e", "夜晚，夜间"),
    "kaffee": ("A1", "NOUN", "Masc", "-s", "咖啡"),
    "tee": ("A1", "NOUN", "Masc", "-s", "茶"),
    "wasser": ("A1", "NOUN", "Neut", "-..", "水"),
    "brot": ("A1", "NOUN", "Neut", "-e", "面包"),
    "brötchen": ("A1", "NOUN", "Neut", "-", "小面包"),
    "obst": ("A1", "NOUN", "Neut", "-", "水果"),
    "apfel": ("A1", "NOUN", "Masc", "-..", "苹果"),
    "milch": ("A1", "NOUN", "Fem", "-", "牛奶"),
    "fleisch": ("A1", "NOUN", "Neut", "-", "肉"),
    "fisch": ("A1", "NOUN", "Masc", "-e", "鱼"),
    "zucker": ("A1", "NOUN", "Masc", "-", "糖"),
    "salz": ("A1", "NOUN", "Neut", "-e", "盐"),
    "supermarkt": ("A1", "NOUN", "Masc", "-..e", "超市"),
    "laden": ("A1", "NOUN", "Masc", "-..", "商店，店铺"),
    "markt": ("A1", "NOUN", "Masc", "-..e", "市场，集市"),
    "haus": ("A1", "NOUN", "Neut", "-..er", "房屋，房子"),
    "wohnung": ("A1", "NOUN", "Fem", "-en", "公寓，住所"),
    "zimmer": ("A1", "NOUN", "Neut", "-", "房间"),
    "küche": ("A1", "NOUN", "Fem", "-n", "厨房"),
    "bad": ("A1", "NOUN", "Neut", "-..er", "浴室，洗手间"),
    "tisch": ("A1", "NOUN", "Masc", "-e", "桌子"),
    "stuhl": ("A1", "NOUN", "Masc", "-..e", "椅子"),
    "bett": ("A1", "NOUN", "Neut", "-en", "床"),
    "tür": ("A1", "NOUN", "Fem", "-en", "门"),
    "fenster": ("A1", "NOUN", "Neut", "-", "窗户"),
    "mann": ("A1", "NOUN", "Masc", "-..er", "男人，丈夫"),
    "frau": ("A1", "NOUN", "Fem", "-en", "女人，妻子，女士"),
    "kind": ("A1", "NOUN", "Neut", "-er", "孩子，儿童"),
    "eltern": ("A1", "NOUN", "Plur", "-", "父母，双亲"),
    "vater": ("A1", "NOUN", "Masc", "-..", "父亲，爸爸"),
    "mutter": ("A1", "NOUN", "Fem", "-..", "母亲，妈妈"),
    "sohn": ("A1", "NOUN", "Masc", "-..e", "儿子"),
    "tochter": ("A1", "NOUN", "Fem", "-..", "女儿"),
    "bruder": ("A1", "NOUN", "Masc", "-..", "兄弟，哥哥/弟弟"),
    "schwester": ("A1", "NOUN", "Fem", "-n", "姐妹，姐姐/妹妹"),
    "freund": ("A1", "NOUN", "Masc", "-e", "朋友，男友"),
    "freundin": ("A1", "NOUN", "Fem", "-nen", "女性朋友，女友"),
    "stadt": ("A1", "NOUN", "Fem", "-..e", "城市"),
    "land": ("A1", "NOUN", "Neut", "-..er", "国家，乡村，陆地"),
    "straße": ("A1", "NOUN", "Fem", "-n", "街道，马路"),
    "platz": ("A1", "NOUN", "Masc", "-..e", "广场，位置，座位"),
    "schule": ("A1", "NOUN", "Fem", "-n", "学校"),
    "sprachschule": ("A1", "NOUN", "Fem", "-n", "语言学校"),
    "kurs": ("A1", "NOUN", "Masc", "-e", "课程"),
    "deutschkurs": ("A1", "NOUN", "Masc", "-e", "德语课程"),
    "unterricht": ("A1", "NOUN", "Masc", "-", "课程，授课，教学"),
    "lehrer": ("A1", "NOUN", "Masc", "-", "教师，男老师"),
    "lehrerin": ("A1", "NOUN", "Fem", "-nen", "女教师，女老师"),
    "student": ("A1", "NOUN", "Masc", "-en", "大学生"),
    "buch": ("A1", "NOUN", "Neut", "-..er", "书，书籍"),
    "heft": ("A1", "NOUN", "Neut", "-e", "笔记本，练习本"),
    "stift": ("A1", "NOUN", "Masc", "-e", "笔"),
    "u-bahn": ("A1", "NOUN", "Fem", "-en", "地铁"),
    "s-bahn": ("A1", "NOUN", "Fem", "-en", "城市轻轨"),
    "bus": ("A1", "NOUN", "Masc", "-se", "公共汽车，大巴"),
    "zug": ("A1", "NOUN", "Masc", "-..e", "火车，列车"),
    "bahn": ("A1", "NOUN", "Fem", "-en", "铁路，火车，轨道"),
    "bahnhof": ("A1", "NOUN", "Masc", "-..e", "火车站"),
    "auto": ("A1", "NOUN", "Neut", "-s", "汽车"),
    "fahrrad": ("A1", "NOUN", "Neut", "-..er", "自行车"),
    "zeit": ("A1", "NOUN", "Fem", "-en", "时间，时期"),
    "stunde": ("A1", "NOUN", "Fem", "-n", "小时，课时"),
    "minute": ("A1", "NOUN", "Fem", "-n", "分钟"),
    "woche": ("A1", "NOUN", "Fem", "-n", "星期，周"),
    "monat": ("A1", "NOUN", "Masc", "-e", "月份，月"),
    "jahr": ("A1", "NOUN", "Neut", "-e", "年，岁"),
    "geld": ("A1", "NOUN", "Neut", "-er", "钱，金钱"),
    "euro": ("A1", "NOUN", "Masc", "-s", "欧元"),
    "preis": ("A1", "NOUN", "Masc", "-e", "价格，价钱，奖项"),
    "name": ("A1", "NOUN", "Masc", "-n", "名字，姓名"),
    "nummer": ("A1", "NOUN", "Fem", "-n", "号码，数字"),
    "telefon": ("A1", "NOUN", "Neut", "-e", "电话"),
    "handy": ("A1", "NOUN", "Neut", "-s", "手机"),
    "arbeit": ("A1", "NOUN", "Fem", "-en", "工作，劳动，作业"),
    "arzt": ("A1", "NOUN", "Masc", "-..e", "医生，男大夫"),
    "ärztin": ("A1", "NOUN", "Fem", "-nen", "女医生"),
    "spaß": ("A1", "NOUN", "Masc", "-..e", "乐趣，玩笑，愉快"),

    # ── A1 Core Verbs ──────────────────────────────────────────────────────────
    "sein": ("A1", "VERB", None, None, "是，存在，处于"),
    "haben": ("A1", "VERB", None, None, "有，拥有"),
    "werden": ("A1", "VERB", None, None, "成为，变得，将要（助动词）"),
    "können": ("A1", "VERB", None, None, "能够，可以，会（情态动词）"),
    "müssen": ("A1", "VERB", None, None, "必须，不得不（情态动词）"),
    "wollen": ("A1", "VERB", None, None, "想要，打算（情态动词）"),
    "sollen": ("A1", "VERB", None, None, "应该，按理说（情态动词）"),
    "dürfen": ("A1", "VERB", None, None, "允许，可以（情态动词）"),
    "möchten": ("A1", "VERB", None, None, "想，想要，希望"),
    "heißen": ("A1", "VERB", None, None, "名叫，意思是"),
    "kommen": ("A1", "VERB", None, None, "来，来到，来自"),
    "wohnen": ("A1", "VERB", None, None, "居住，住"),
    "leben": ("A1", "VERB", None, None, "生活，活着"),
    "lernen": ("A1", "VERB", None, None, "学习，学会"),
    "arbeiten": ("A1", "VERB", None, None, "工作，劳动"),
    "sprechen": ("A1", "VERB", None, None, "说，说话，讲某种语言"),
    "sagen": ("A1", "VERB", None, None, "说，讲，告诉"),
    "hören": ("A1", "VERB", None, None, "听，听到，听见"),
    "sehen": ("A1", "VERB", None, None, "看，看见，明白"),
    "lesen": ("A1", "VERB", None, None, "阅读，看书，朗读"),
    "schreiben": ("A1", "VERB", None, None, "写，写作，写字"),
    "essen": ("A1", "VERB", None, None, "吃，用餐"),
    "trinken": ("A1", "VERB", None, None, "喝，饮用"),
    "gehen": ("A1", "VERB", None, None, "去，走，步行，进行"),
    "fahren": ("A1", "VERB", None, None, "乘车，驾车，行驶"),
    "fliegen": ("A1", "VERB", None, None, "飞，乘飞机"),
    "kaufen": ("A1", "VERB", None, None, "购买，买"),
    "verkaufen": ("A1", "VERB", None, None, "出售，卖"),
    "bezahlen": ("A1", "VERB", None, None, "付款，支付"),
    "kosten": ("A1", "VERB", None, None, "花费，价值，尝味道"),
    "brauchen": ("A1", "VERB", None, None, "需要，用"),
    "finden": ("A1", "VERB", None, None, "找到，发现，觉得"),
    "suchen": ("A1", "VERB", None, None, "寻找，搜寻"),
    "fragen": ("A1", "VERB", None, None, "问，询问，请教"),
    "antworten": ("A1", "VERB", None, None, "回答，答复"),
    "machen": ("A1", "VERB", None, None, "做，制造，使得"),
    "spielen": ("A1", "VERB", None, None, "玩，游戏，弹奏，比赛"),
    "schlafen": ("A1", "VERB", None, None, "睡觉"),
    "stehen": ("A1", "VERB", None, None, "站立，处于"),
    "sitzen": ("A1", "VERB", None, None, "坐，坐着"),
    "liegen": ("A1", "VERB", None, None, "躺，平放，位于"),
    "nehmen": ("A1", "VERB", None, None, "拿，取，选用，服用"),
    "geben": ("A1", "VERB", None, None, "给，给予，存在(es gibt)"),
    "bring": ("A1", "VERB", None, None, "带来，拿来"),
    "bringen": ("A1", "VERB", None, None, "带来，拿来，送去"),
    "zeigen": ("A1", "VERB", None, None, "展示，指出，显示"),
    "wissen": ("A1", "VERB", None, None, "知道，知晓"),
    "kennen": ("A1", "VERB", None, None, "认识，了解，熟悉"),
    "verstehen": ("A1", "VERB", None, None, "理解，明白，懂"),

    # ── A1 Core Adjectives & Others ────────────────────────────────────────────
    "gut": ("A1", "ADJ", None, None, "好的，良好的"),
    "schlecht": ("A1", "ADJ", None, None, "坏的，糟糕的"),
    "schön": ("A1", "ADJ", None, None, "美丽的，美好的，漂亮"),
    "groß": ("A1", "ADJ", None, None, "大的，高大的，重大的"),
    "klein": ("A1", "ADJ", None, None, "小的，幼小的，简短的"),
    "neu": ("A1", "ADJ", None, None, "新的，新鲜的"),
    "alt": ("A1", "ADJ", None, None, "老的，旧的，年长"),
    "jung": ("A1", "ADJ", None, None, "年轻的，青年的"),
    "frisch": ("A1", "ADJ", None, None, "新鲜的，清新的"),
    "warm": ("A1", "ADJ", None, None, "温暖的，热的"),
    "kalt": ("A1", "ADJ", None, None, "寒冷的，冷的"),
    "viel": ("A1", "ADJ", None, None, "许多，很多"),
    "wenig": ("A1", "ADJ", None, None, "少的，少数的"),
    "schnell": ("A1", "ADJ", None, None, "快速的，敏捷的"),
    "langsam": ("A1", "ADJ", None, None, "缓慢的，慢的"),
    "teuer": ("A1", "ADJ", None, None, "昂贵的，贵的"),
    "billig": ("A1", "ADJ", None, None, "便宜的，廉价的"),
    "günstig": ("A1", "ADJ", None, None, "优惠的，适宜的"),
    "einfach": ("A1", "ADJ", None, None, "简单的，单纯的，朴素的"),
    "schwer": ("A1", "ADJ", None, None, "困难的，沉重的"),
    "leicht": ("A1", "ADJ", None, None, "轻的，容易的"),
    "richtig": ("A1", "ADJ", None, None, "正确的，恰当的"),
    "falsch": ("A1", "ADJ", None, None, "错误的，假的"),
    "früh": ("A1", "ADJ", None, None, "早的，及早的"),
    "spät": ("A1", "ADJ", None, None, "迟的，晚的"),
    "wichtig": ("A1", "ADJ", None, None, "重要的，关键的"),
    "interessant": ("A1", "ADJ", None, None, "有趣的，有吸引力的"),
    "langweilig": ("A1", "ADJ", None, None, "无聊的，枯燥的"),
    "fertig": ("A1", "ADJ", None, None, "完成的，准备好的"),
    "offen": ("A1", "ADJ", None, None, "开着的，坦率的，公开的"),

    # ── A2 Nouns & Verbs ───────────────────────────────────────────────────────
    "wochenende": ("A2", "NOUN", "Neut", "-n", "周末"),
    "urlaub": ("A2", "NOUN", "Masc", "-e", "假期，休假"),
    "reise": ("A2", "NOUN", "Fem", "-n", "旅行，旅程"),
    "koffer": ("A2", "NOUN", "Masc", "-", "行李箱，手提箱"),
    "hotel": ("A2", "NOUN", "Neut", "-s", "酒店，宾馆"),
    "restaurant": ("A2", "NOUN", "Neut", "-s", "餐馆，餐厅"),
    "spezialität": ("A2", "NOUN", "Fem", "-en", "特色菜，特产，专业"),
    "garten": ("A2", "NOUN", "Masc", "-..", "花园，果园"),
    "wetter": ("A2", "NOUN", "Neut", "-", "天气，气候"),
    "sonne": ("A2", "NOUN", "Fem", "-n", "太阳，阳光"),
    "regen": ("A2", "NOUN", "Masc", "-", "雨，降雨"),
    "schnee": ("A2", "NOUN", "Masc", "-", "雪"),
    "wind": ("A2", "NOUN", "Masc", "-e", "风"),
    "prüfung": ("A2", "NOUN", "Fem", "-en", "考试，测试，检验"),
    "zeugnis": ("A2", "NOUN", "Neut", "-se", "成绩单，证书，证明"),
    "beruf": ("A2", "NOUN", "Masc", "-e", "职业，行业"),
    "firma": ("A2", "NOUN", "Fem", "Firmen", "公司，企业"),
    "kollege": ("A2", "NOUN", "Masc", "-n", "同事，同行"),
    "chef": ("A2", "NOUN", "Masc", "-s", "主管，领导，老板"),
    "termin": ("A2", "NOUN", "Masc", "-e", "约会，约期，指定时间"),
    "einladung": ("A2", "NOUN", "Fem", "-en", "邀请，请帖"),
    "brief": ("A2", "NOUN", "Masc", "-e", "信件，书信"),
    "nachricht": ("A2", "NOUN", "Fem", "-en", "消息，新闻，短信"),
    "zeitung": ("A2", "NOUN", "Fem", "-en", "报纸"),
    "zeitschrift": ("A2", "NOUN", "Fem", "-en", "杂志，期刊"),
    "kleidung": ("A2", "NOUN", "Fem", "-en", "衣服，服装"),
    "kleid": ("A2", "NOUN", "Neut", "-er", "连衣裙，裙子"),
    "hose": ("A2", "NOUN", "Fem", "-n", "裤子"),
    "hemd": ("A2", "NOUN", "Neut", "-en", "衬衫"),
    "schuh": ("A2", "NOUN", "Masc", "-e", "鞋子"),
    "gesundheit": ("A2", "NOUN", "Fem", "-", "健康"),
    "krankheit": ("A2", "NOUN", "Fem", "-en", "疾病，病情"),
    "medikament": ("A2", "NOUN", "Neut", "-e", "药物，药品"),
    "apotheke": ("A2", "NOUN", "Fem", "-n", "药房，药店"),
    "krankenhaus": ("A2", "NOUN", "Neut", "-..er", "医院"),
    "kopf": ("A2", "NOUN", "Masc", "-..e", "头，头部"),
    "auge": ("A2", "NOUN", "Neut", "-n", "眼睛"),
    "ohr": ("A2", "NOUN", "Neut", "-en", "耳朵"),
    "mund": ("A2", "NOUN", "Masc", "-..er", "嘴巴"),
    "hand": ("A2", "NOUN", "Fem", "-..e", "手"),
    "fuß": ("A2", "NOUN", "Masc", "-..e", "脚，足"),
    "bein": ("A2", "NOUN", "Neut", "-e", "腿"),
    "körper": ("A2", "NOUN", "Masc", "-", "身体，躯体"),
    "problem": ("A2", "NOUN", "Neut", "-e", "问题，难题"),
    "lösung": ("A2", "NOUN", "Fem", "-en", "解决方案，答案"),
    "frage": ("A2", "NOUN", "Fem", "-n", "问题，疑问"),
    "antwort": ("A2", "NOUN", "Fem", "-en", "回答，答复"),
    "idee": ("A2", "NOUN", "Fem", "-n", "主意，想法，点子"),
    "geschichte": ("A2", "NOUN", "Fem", "-n", "历史，故事"),
    "kultur": ("A2", "NOUN", "Fem", "-en", "文化，文明"),
    "musik": ("A2", "NOUN", "Fem", "-", "音乐"),
    "film": ("A2", "NOUN", "Masc", "-e", "电影，影片"),
    "kino": ("A2", "NOUN", "Neut", "-s", "电影院"),
    "theater": ("A2", "NOUN", "Neut", "-", "剧院，戏剧"),
    "museum": ("A2", "NOUN", "Neut", "Museen", "博物馆"),

    "erzählen": ("A2", "VERB", None, None, "讲述，叙述，告诉"),
    "erklären": ("A2", "VERB", None, None, "解释，说明，阐明"),
    "beschreiben": ("A2", "VERB", None, None, "描述，描绘"),
    "bestehen": ("A2", "VERB", None, None, "通过(考试)，存在，由...组成"),
    "verbringen": ("A2", "VERB", None, None, "度过(时间)，消磨"),
    "probieren": ("A2", "VERB", None, None, "品尝，尝试，试穿"),
    "versuchen": ("A2", "VERB", None, None, "试图，尝试，企图"),
    "reservieren": ("A2", "VERB", None, None, "预订，预留"),
    "buchen": ("A2", "VERB", None, None, "预订(票/房间)"),
    "besuchen": ("A2", "VERB", None, None, "拜访，参观，探望，就读"),
    "helfen": ("A2", "VERB", None, None, "帮助，援助"),
    "treffen": ("A2", "VERB", None, None, "遇到，会面，击中"),
    "beginnen": ("A2", "VERB", None, None, "开始，着手"),
    "anfangen": ("A2", "VERB", None, None, "开始，起步"),
    "aufhören": ("A2", "VERB", None, None, "停止，中止"),
    "aufstehen": ("A2", "VERB", None, None, "起床，起立"),
    "einkaufen": ("A2", "VERB", None, None, "购物，买东西"),
    "mitnehmen": ("A2", "VERB", None, None, "随身携带，带走"),
    "einladen": ("A2", "VERB", None, None, "邀请，请客"),
    "anrufen": ("A2", "VERB", None, None, "打电话给..."),
    "abfahren": ("A2", "VERB", None, None, "启程，发车，驶离"),
    "ankommen": ("A2", "VERB", None, None, "到达，抵达，取决于"),
    "umsteigen": ("A2", "VERB", None, None, "换乘，转车"),
    "einsteigen": ("A2", "VERB", None, None, "上车，进入"),
    "aussteigen": ("A2", "VERB", None, None, "下车，退出"),
    "gefallen": ("A2", "VERB", None, None, "使喜欢，合心意"),
    "gehören": ("A2", "VERB", None, None, "属于，归于"),
    "passen": ("A2", "VERB", None, None, "合适，相配，适合"),
    "feiern": ("A2", "VERB", None, None, "庆祝，举行庆祝会"),
    "schenken": ("A2", "VERB", None, None, "赠送，送礼"),
    "wünschen": ("A2", "VERB", None, None, "希望，祝愿"),
    "hoffen": ("A2", "VERB", None, None, "盼望，寄予希望"),
    "glauben": ("A2", "VERB", None, None, "相信，认为，信仰"),
    "denken": ("A2", "VERB", None, None, "思考，想，认为"),
    "meinen": ("A2", "VERB", None, None, "认为，意思是，指"),

    # ── B1 Core Goethe Vocabulary ──────────────────────────────────────────────
    "klimawandel": ("B1", "NOUN", "Masc", "-", "气候变化"),
    "klimaschutz": ("B1", "NOUN", "Masc", "-", "气候保护"),
    "umweltschutz": ("B1", "NOUN", "Masc", "-", "环境保护"),
    "umwelt": ("B1", "NOUN", "Fem", "-", "环境，自然界"),
    "natur": ("B1", "NOUN", "Fem", "-", "大自然，自然界，本性"),
    "energie": ("B1", "NOUN", "Fem", "-n", "能源，能量，精力"),
    "strom": ("B1", "NOUN", "Masc", "-", "电力，电流，大河"),
    "müll": ("B1", "NOUN", "Masc", "-", "垃圾，废弃物"),
    "haushalt": ("B1", "NOUN", "Masc", "-e", "家庭，家务，预算"),
    "lebensmittel": ("B1", "NOUN", "Neut", "-", "食品，粮食"),
    "ernährung": ("B1", "NOUN", "Fem", "-", "营养，饮食，膳食"),
    "gesellschaft": ("B1", "NOUN", "Fem", "-en", "社会，协会，交际"),
    "gemeinschaft": ("B1", "NOUN", "Fem", "-en", "团体，共同体，社群"),
    "meinung": ("B1", "NOUN", "Fem", "-en", "意见，看法，主张"),
    "ansicht": ("B1", "NOUN", "Fem", "-en", "观点，见解，景象"),
    "einstellung": ("B1", "NOUN", "Fem", "-en", "态度，观点，招聘，停止"),
    "herausforderung": ("B1", "NOUN", "Fem", "-en", "挑战，艰巨任务"),
    "beitrag": ("B1", "NOUN", "Masc", "-..e", "贡献，文章，会费"),
    "experte": ("B1", "NOUN", "Masc", "-n", "专家，行家"),
    "expertin": ("B1", "NOUN", "Fem", "-nen", "女性专家"),
    "erfahrung": ("B1", "NOUN", "Fem", "-en", "经验，阅历，体验"),
    "kenntnis": ("B1", "NOUN", "Fem", "-se", "知识，认知，技能"),
    "fähigkeit": ("B1", "NOUN", "Fem", "-en", "能力，本领，才干"),
    "ausbildung": ("B1", "NOUN", "Fem", "-en", "职业培训，学徒培养"),
    "weiterbildung": ("B1", "NOUN", "Fem", "-en", "进修，继续教育"),
    "studium": ("B1", "NOUN", "Neut", "Studien", "大学学业，研究"),
    "universität": ("B1", "NOUN", "Fem", "-en", "综合性大学"),
    "abschluss": ("B1", "NOUN", "Masc", "-..e", "毕业文凭，结论，签订"),
    "zukunft": ("B1", "NOUN", "Fem", "-", "未来，前途"),
    "vergangenheit": ("B1", "NOUN", "Fem", "-", "过去，往事"),
    "gegenwart": ("B1", "NOUN", "Fem", "-", "现在，当代"),
    "chance": ("B1", "NOUN", "Fem", "-n", "机会，机遇，可能性"),
    "möglichkeit": ("B1", "NOUN", "Fem", "-en", "可能性，机会"),
    "gefahr": ("B1", "NOUN", "Fem", "-en", "危险，危机"),
    "risiko": ("B1", "NOUN", "Neut", "Risiken", "风险，危险度"),
    "vorteil": ("B1", "NOUN", "Masc", "-e", "优点，益处，优势"),
    "nachteil": ("B1", "NOUN", "Masc", "-e", "缺点，坏处，劣势"),
    "grund": ("B1", "NOUN", "Masc", "-..e", "原因，理由，土地，底部"),
    "ursache": ("B1", "NOUN", "Fem", "-n", "起因，根源"),
    "folge": ("B1", "NOUN", "Fem", "-n", "后果，结果，一集"),
    "wirkung": ("B1", "NOUN", "Fem", "-en", "效果，作用，影响"),
    "einfluss": ("B1", "NOUN", "Masc", "-..e", "影响，影响力"),
    "rolle": ("B1", "NOUN", "Fem", "-n", "角色，作用"),
    "zusammenhang": ("B1", "NOUN", "Masc", "-..e", "关联，联系，上下文"),
    "unterschied": ("B1", "NOUN", "Masc", "-e", "区别，差异"),
    "vergleich": ("B1", "NOUN", "Masc", "-e", "比较，对照，和解"),
    "situation": ("B1", "NOUN", "Fem", "-en", "情境，局势，状况"),
    "zustand": ("B1", "NOUN", "Masc", "-..e", "状态，情况"),
    "entwicklung": ("B1", "NOUN", "Fem", "-en", "发展，演变，研发"),
    "fortschritt": ("B1", "NOUN", "Masc", "-e", "进步，进展"),
    "veränderung": ("B1", "NOUN", "Fem", "-en", "改变，变化"),
    "verkehr": ("B1", "NOUN", "Masc", "-", "交通，往来"),
    "transport": ("B1", "NOUN", "Masc", "-e", "运输，搬运"),
    "medien": ("B1", "NOUN", "Plur", "-", "媒体，大众媒介"),
    "internet": ("B1", "NOUN", "Neut", "-", "互联网，网络"),
    "netzwerk": ("B1", "NOUN", "Neut", "-e", "网络，人脉网"),
    "technologie": ("B1", "NOUN", "Fem", "-n", "技术，工艺"),

    "entscheiden": ("B1", "VERB", None, None, "决定，判决"),
    "beschließen": ("B1", "VERB", None, None, "决议，决定，结束"),
    "entwickeln": ("B1", "VERB", None, None, "发展，研发，培养"),
    "verbessern": ("B1", "VERB", None, None, "改善，改进，提高"),
    "verschlechtern": ("B1", "VERB", None, None, "恶化，变差"),
    "erhöhen": ("B1", "VERB", None, None, "增加，提高，抬高"),
    "senken": ("B1", "VERB", None, None, "降低，减少，垂下"),
    "sinken": ("B1", "VERB", None, None, "下降，下沉，跌落"),
    "steigen": ("B1", "VERB", None, None, "上升，攀登，增长"),
    "wachsen": ("B1", "VERB", None, None, "成长，增长，生长"),
    "sparen": ("B1", "VERB", None, None, "节约，储蓄，节省"),
    "ausgeben": ("B1", "VERB", None, None, "支出，花钱，发行"),
    "leisten": ("B1", "VERB", None, None, "做出(贡献)，提供，买得起(sich D. leisten)"),
    "empfehlen": ("B1", "VERB", None, None, "推荐，建议"),
    "raten": ("B1", "VERB", None, None, "建议，劝告，猜测"),
    "vorschlagen": ("B1", "VERB", None, None, "提议，建议"),
    "planen": ("B1", "VERB", None, None, "规划，计划"),
    "organisieren": ("B1", "VERB", None, None, "组织，筹备"),
    "teilnehmen": ("B1", "VERB", None, None, "参加，参与"),
    "mitmachen": ("B1", "VERB", None, None, "一起做，参与"),
    "informieren": ("B1", "VERB", None, None, "通知，告知，了解信息"),
    "berichten": ("B1", "VERB", None, None, "报道，报告"),
    "diskutieren": ("B1", "VERB", None, None, "讨论，辩论"),
    "überzeugen": ("B1", "VERB", None, None, "说服，使信服"),
    "begründen": ("B1", "VERB", None, None, "阐述理由，论证"),
    "vergleichen": ("B1", "VERB", None, None, "比较，对照"),
    "unterscheiden": ("B1", "VERB", None, None, "区分，辨别"),
    "beeinflussen": ("B1", "VERB", None, None, "影响，施加影响"),
    "vermeiden": ("B1", "VERB", None, None, "避免，避开"),
    "schützen": ("B1", "VERB", None, None, "保护，防护"),
    "retten": ("B1", "VERB", None, None, "拯救，挽救"),
    "erinnern": ("B1", "VERB", None, None, "提醒，使想起，回忆(sich an A.)"),
    "vergessen": ("B1", "VERB", None, None, "遗忘，忘记"),
    "gewöhnen": ("B1", "VERB", None, None, "使习惯于(sich an A. gewöhnen)"),

    # ── B2 Advanced Academic & Professional ────────────────────────────────────
    "digitalisierung": ("B2", "NOUN", "Fem", "-", "数字化，数字化转型"),
    "transformation": ("B2", "NOUN", "Fem", "-en", "转型，变革，转变"),
    "arbeitsbedingung": ("B2", "NOUN", "Fem", "-en", "工作条件，劳动环境"),
    "arbeitsmarkt": ("B2", "NOUN", "Masc", "-..e", "劳动力市场，求职市场"),
    "arbeitszeitmodell": ("B2", "NOUN", "Neut", "-e", "工作时间模式"),
    "unternehmen": ("B2", "NOUN", "Neut", "-", "企业，公司，事业"),
    "betrieb": ("B2", "NOUN", "Masc", "-e", "工厂，企业，运营"),
    "wirtschaft": ("B2", "NOUN", "Fem", "-en", "经济，经济学，酒馆"),
    "mitarbeiter": ("B2", "NOUN", "Masc", "-", "员工，职员，同事"),
    "arbeitnehmer": ("B2", "NOUN", "Masc", "-", "雇员，受雇者"),
    "arbeitgeber": ("B2", "NOUN", "Masc", "-", "雇主，用人单位"),
    "beschäftigte": ("B2", "NOUN", "Masc/Fem", "-n", "就业者，职工"),
    "führungskraft": ("B2", "NOUN", "Fem", "-..e", "管理层，主管领导"),
    "vereinbarkeit": ("B2", "NOUN", "Fem", "-", "兼容性，协调性(如家庭与工作兼顾)"),
    "kompetenz": ("B2", "NOUN", "Fem", "-en", "胜任力，专业能力，职权"),
    "qualifikation": ("B2", "NOUN", "Fem", "-en", "资质，任职资格"),
    "voraussetzung": ("B2", "NOUN", "Fem", "-en", "前提条件，先决要求"),
    "bedingung": ("B2", "NOUN", "Fem", "-en", "条件，条款"),
    "verfügung": ("B2", "NOUN", "Fem", "-en", "支配，安排(zur Verfügung stehen/stellen)"),
    "grenze": ("B2", "NOUN", "Fem", "-n", "边界，界限，国界"),
    "tragweite": ("B2", "NOUN", "Fem", "-", "重要性，深远影响，波及范围"),
    "fragestellung": ("B2", "NOUN", "Fem", "-en", "议题，研究问题，探讨焦点"),
    "aspekt": ("B2", "NOUN", "Masc", "-e", "方面，维度，视角"),
    "perspektive": ("B2", "NOUN", "Fem", "-n", "视角，前途，透视"),
    "standpunkt": ("B2", "NOUN", "Masc", "-e", "立场，观点"),
    "argument": ("B2", "NOUN", "Neut", "-e", "论据，论点"),
    "these": ("B2", "NOUN", "Fem", "-n", "论题，命题，论纲"),
    "hypothese": ("B2", "NOUN", "Fem", "-n", "假设，假说"),
    "konsequenz": ("B2", "NOUN", "Fem", "-en", "后果，必然结果，坚定性"),
    "maßnahme": ("B2", "NOUN", "Fem", "-n", "举措，措施，办法"),
    "strategie": ("B2", "NOUN", "Fem", "-n", "策略，战略"),
    "methode": ("B2", "NOUN", "Fem", "-n", "方法，手段"),
    "effizienz": ("B2", "NOUN", "Fem", "-", "效率，成效"),
    "nachhaltigkeit": ("B2", "NOUN", "Fem", "-", "可持续性，持久性"),
    "ressource": ("B2", "NOUN", "Fem", "-n", "资源，资力"),
    "forschung": ("B2", "NOUN", "Fem", "-en", "科学研究，探索"),
    "wissenschaft": ("B2", "NOUN", "Fem", "-en", "科学，学科"),
    "erkenntnis": ("B2", "NOUN", "Fem", "-se", "认识，心得，科研成果"),
    "phänomen": ("B2", "NOUN", "Neut", "-e", "现象，非凡之人"),
    "tendenz": ("B2", "NOUN", "Fem", "-en", "趋势，倾向"),
    "prozess": ("B2", "NOUN", "Masc", "-e", "过程，进程，诉讼"),
    "struktur": ("B2", "NOUN", "Fem", "-en", "结构，构造，架构"),
    "funktion": ("B2", "NOUN", "Fem", "-en", "功能，职责，作用"),

    "beeinträchtigen": ("B2", "VERB", None, None, "损害，负面影响，妨碍"),
    "gewährleisten": ("B2", "VERB", None, None, "确保，保证，担保"),
    "hervorheben": ("B2", "VERB", None, None, "强调，突出，指出"),
    "unterstreichen": ("B2", "VERB", None, None, "划线强调，凸显"),
    "betonen": ("B2", "VERB", None, None, "强调，加重读音"),
    "voraussetzen": ("B2", "VERB", None, None, "以...为前提，要求，假定"),
    "erfordern": ("B2", "VERB", None, None, "需要，要求，索取"),
    "ermöglichen": ("B2", "VERB", None, None, "使...成为可能，促进"),
    "erleichtern": ("B2", "VERB", None, None, "减轻，使轻松，促成"),
    "erschweren": ("B2", "VERB", None, None, "使变困难，阻碍"),
    "verhindern": ("B2", "VERB", None, None, "阻止，妨碍，预防"),
    "fördern": ("B2", "VERB", None, None, "促进，资助，开采"),
    "fordern": ("B2", "VERB", None, None, "要求，索求，挑战"),
    "berücksichtigen": ("B2", "VERB", None, None, "顾及，考虑到，兼顾"),
    "beachten": ("B2", "VERB", None, None, "注意，重视，遵守"),
    "behandeln": ("B2", "VERB", None, None, "对待，探讨，治疗，处理"),
    "analysieren": ("B2", "VERB", None, None, "分析，剖析"),
    "reflektieren": ("B2", "VERB", None, None, "反思，思考，反射"),
    "interpretieren": ("B2", "VERB", None, None, "诠释，阐释，解读"),
    "definieren": ("B2", "VERB", None, None, "下定义，明确界定"),
    "kritisieren": ("B2", "VERB", None, None, "批评，批判，指责"),
    "bewerten": ("B2", "VERB", None, None, "评估，打分，评价"),
    "beurteilen": ("B2", "VERB", None, None, "判断，评价，裁判"),
    "umsetzen": ("B2", "VERB", None, None, "落实，实施，转化，销售"),
    "durchführen": ("B2", "VERB", None, None, "执行，开展，贯彻"),
    "verwirklichen": ("B2", "VERB", None, None, "实现，使成为现实"),
    "beitragen": ("B2", "VERB", None, None, "为...做出贡献(zu D. beitragen)"),
    "verfügen": ("B2", "VERB", None, None, "拥有，支配(über A. verfügen)"),
    "basieren": ("B2", "VERB", None, None, "基于，建立在...基础之上(auf D.)"),

    "grundlegend": ("B2", "ADJ", None, None, "根本性的，基础的，彻底的"),
    "wesentlich": ("B2", "ADJ", None, None, "本质的，主要的，关键的"),
    "flexibel": ("B2", "ADJ", None, None, "灵活的，有弹性的"),
    "nachhaltig": ("B2", "ADJ", None, None, "可持续的，深远的"),
    "effektiv": ("B2", "ADJ", None, None, "有效的，产生实效的"),
    "effizient": ("B2", "ADJ", None, None, "高效的，效率高的"),
    "komplex": ("B2", "ADJ", None, None, "复杂的，多元的"),
    "spezifisch": ("B2", "ADJ", None, None, "特定的，具体的，特有的"),
    "relevant": ("B2", "ADJ", None, None, "相关的，有重大意义的"),
    "adäquat": ("B2", "ADJ", None, None, "相称的，恰当的，充分的"),
    "ethisch": ("B2", "ADJ", None, None, "伦理的，道德的"),
    "existenziell": ("B2", "ADJ", None, None, "关乎存在的，生死攸关的"),
    "potenziell": ("B2", "ADJ", None, None, "潜在的，可能的"),
    "kontrovers": ("B2", "ADJ", None, None, "有争议的，引发分歧的"),
    "eindeutig": ("B2", "ADJ", None, None, "明确的，毋庸置疑的"),

    # ── C1 Academic & High Register ───────────────────────────────────────────
    "fungieren": ("C1", "VERB", None, None, "充当，担任，发挥...作用(als)"),
    "implizieren": ("C1", "VERB", None, None, "意味着，暗指，包含"),
    "konstatieren": ("C1", "VERB", None, None, "断定，指出，确认"),
    "differenzieren": ("C1", "VERB", None, None, "细分，区别对待，辨异"),
    "postulieren": ("C1", "VERB", None, None, "主张，要求，假设"),
    "revitalisieren": ("C1", "VERB", None, None, "使复兴，恢复活力"),
    "paradigma": ("C1", "NOUN", "Neut", "Paradigmen", "范式，典范"),
    "ambivalenz": ("C1", "NOUN", "Fem", "-en", "矛盾心理，双重性"),
    "divergenz": ("C1", "NOUN", "Fem", "-en", "分歧，差异，发散"),
    "kohärenz": ("C1", "NOUN", "Fem", "-", "连贯性，一致性"),
    "unabdingbar": ("C1", "ADJ", None, None, "不可或缺的，绝对必要的"),
    "ambivalent": ("C1", "ADJ", None, None, "矛盾的，具有双重性的"),
    "sukzessive": ("C1", "ADJ", None, None, "逐步的，接连的"),
    "inhärent": ("C1", "ADJ", None, None, "固有的，内在的"),
    "manifest": ("C1", "ADJ", None, None, "显而易见的，明白的"),
}

def lookup_core_vocab(lemma_or_word: str) -> Optional[Dict[str, Any]]:
    """O(1) memory lookup for Goethe core vocabulary."""
    if not lemma_or_word:
        return None
    key = lemma_or_word.strip().lower()
    
    # Direct match
    if key in CORE_VOCAB_DB:
        cefr, pos, gender, plural, def_zh = CORE_VOCAB_DB[key]
        return {
            "lemma": key,
            "cefr_level": cefr,
            "pos": pos,
            "gender": gender,
            "plural": plural or "",
            "definition_zh": def_zh,
            "source": "local_dict"
        }
    
    # Strip common German verb inflections or noun plurals if lemma is slightly variant
    for ending in ["en", "e", "n", "s"]:
        if key.endswith(ending) and len(key) > len(ending) + 2:
            base = key[:-len(ending)]
            if base in CORE_VOCAB_DB:
                cefr, pos, gender, plural, def_zh = CORE_VOCAB_DB[base]
                return {
                    "lemma": base,
                    "cefr_level": cefr,
                    "pos": pos,
                    "gender": gender,
                    "plural": plural or "",
                    "definition_zh": def_zh,
                    "source": "local_dict"
                }
    return None

def get_core_cefr_level(lemma: str) -> Optional[str]:
    """Get exact CEFR level if in core dictionary."""
    if not lemma:
        return None
    key = lemma.strip().lower()
    if key in CORE_VOCAB_DB:
        return CORE_VOCAB_DB[key][0]
    return None

# ── 合并 AI 批量生成的扩展词库（core_dict_ext.py，见 tools/build_dict.py）────
# 为什么 import 而非运行时读 JSON：Chaquopy extract_packages 为空，open() 数据
# 文件会失败；.py 模块按 import 链正常打包（PyInstaller 自动分析，CI 拷贝进
# android/app/src/main/python）。base 443 冲突时手编词条优先（dict 合并顺序）。
try:
    from core_dict_ext import CORE_VOCAB_EXT
except ImportError:
    CORE_VOCAB_EXT = {}
CORE_VOCAB_DB = {**CORE_VOCAB_EXT, **CORE_VOCAB_DB}
