# -*- coding: utf-8 -*-
"""AI 批量生成的德语动词/形容词固定介词搭配表（auto-generated）。

Schema: lemma -> ((介词, 格, 中文义, 例句), ...)
值是**元组的元组**：一个词头可带多个介词且意思不同
（bestehen auf 坚持 / aus 由…组成 / in 在于），单值会丢义项。

键全小写、反身动词不带 sich（freuen 而非 sich freuen），
以便直接匹配 spaCy 的 lemma 输出。
手动改会丢：必考搭配请改 tools/build_prep.py 的 SEED_COLLOCATIONS，
长尾靠 AI 生成，两者由 tools/build_prep.py 合并（seed 优先）。
"""

PREP_COLLOCATIONS = {  # 494 词条 / 617 条搭配 · 已问过 1740 词 · seed 47 词 + AI 长尾
    "abfahren": (("auf", "Akk", "着迷，喜欢", "Sie fährt total auf diese Musik ab."),),
    "abheben": (("auf", "Akk", "针对，着眼于", "Der Film hebt auf die Probleme der Jugend ab."),),
    "abhängen": (("von", "Dat", "取决于", "Der Erfolg hängt von der Vorbereitung ab."),),
    "abhängig": (("von", "Dat", "依赖于", "Der Erfolg ist von vielen Faktoren abhängig."),),
    "ablenken": (("von", "Dat", "使分心", "Das Geräusch lenkt von der Arbeit ab."),),
    "abrechnen": (("mit", "Dat", "算账", "Er rechnet mit seinem Betrüger ab."),),
    "abstimmen": (("auf", "Akk", "协调", "Wir stimmen die Maßnahmen auf die Bedürfnisse ab."), ("über", "Akk", "表决", "Das Parlament stimmt über den Gesetzentwurf ab."), ("mit", "Dat", "与…协调", "Er stimmt das Vorgehen mit seinem Kollegen ab.")),
    "abtreten": (("an", "Akk", "移交给", "Der Minister tritt sein Amt an seinen Nachfolger ab."),),
    "abweichen": (("von", "Dat", "偏离", "Die Ergebnisse weichen von der Norm ab."),),
    "abwenden": (("von", "Dat", "(sich)背离", "Er wendet sich von der Gesellschaft ab."),),
    "achten": (("auf", "Akk", "注意", "Bitte achten Sie auf die Verkehrszeichen."),),
    "alternativ": (("zu", "Dat", "替代", "Wir suchen einen alternativen Termin zu dem geplanten."),),
    "anerkennen": (("als", "Akk", "承认…为", "Er erkennt ihn als seinen Vorgesetzten an."),),
    "anfangen": (("mit", "Dat", "开始做", "Wir fangen mit der Übung an."),),
    "anfällig": (("für", "Akk", "易受…影响", "Er ist anfällig für Grippe."),),
    "angeben": (("mit", "Dat", "吹嘘，炫耀", "Er gibt mit seinem Auto an."),),
    "angleichend": (("an", "Akk", "使…与…一致", "Sie gleicht ihre Daten an die Realität an."),),
    "ankommen": (("auf", "Akk", "取决于", "Es kommt auf deine Entscheidung an."), ("gegen", "Akk", "对抗/抵挡", "Gegen diese Maßnahmen kommen wir nicht an.")),
    "anlegen": (("mit", "Dat", "（sich）与…争吵", "Er hat sich mit seinem Bruder angelegt."),),
    "anmelden": (("bei", "Dat", "（sich）在…登记", "Ich melde mich bei der Agentur an."), ("für", "Akk", "（sich）报名", "Sie meldet sich für den Kurs an.")),
    "anschließen": (("an", "Akk", "连接到", "Schließen Sie das Gerät an den Computer an."),),
    "ansprechen": (("auf", "Akk", "对…有反应", "Der Patient spricht gut auf die Therapie an."),),
    "antworten": (("auf", "Akk", "回答", "Er antwortet auf die Frage."),),
    "anwenden": (("auf", "Akk", "应用于", "Ich wende diese Methode auf das Problem an."),),
    "anwesend": (("bei", "Dat", "在场", "Er war bei der Versammlung anwesend."),),
    "arbeiten": (("an", "Dat", "致力于，从事", "Er arbeitet an einem neuen Roman."), ("für", "Akk", "为...工作", "Sie arbeitet für eine große Firma."), ("bei", "Dat", "在...工作", "Er arbeitet bei Siemens.")),
    "arm": (("an", "Dat", "缺乏，不足", "Das Land ist arm an natürlichen Ressourcen."),),
    "auffallen": (("durch", "Akk", "因…引人注意", "Er fällt durch seine Kleidung auf."),),
    "aufgeschlossen": (("für", "Akk", "对…开放", "Sie ist aufgeschlossen für neue Ideen."),),
    "aufhalten": (("in", "Dat", "(sich)停留于", "Er hält sich in Berlin auf."),),
    "aufhören": (("mit", "Dat", "停止做", "Er hört mit dem Rauchen auf."),),
    "aufmerksam": (("auf", "Akk", "对…注意", "Er ist aufmerksam auf die Details."),),
    "aufnehmen": (("in", "Akk", "接纳到…里", "Sie nimmt ihn in ihr Team auf."),),
    "aufpassen": (("auf", "Akk", "注意，照看", "Pass auf den Verkehr auf."),),
    "aufregen": (("über", "Akk", "(sich)对…气愤", "Er regt sich über den Lärm auf."),),
    "aufräumen": (("mit", "Dat", "清除", "Sie räumte mit alten Vorurteilen auf."),),
    "aufstehen": (("gegen", "Akk", "反抗", "Viele Bürger standen gegen die Diktatur auf."), ("für", "Akk", "支持", "Er steht für seine Rechte auf.")),
    "auftreten": (("gegen", "Akk", "对抗", "Sie tritt gegen Ungerechtigkeit auf."), ("für", "Akk", "支持", "Er tritt für die Umwelt auf.")),
    "aufwachen": (("aus", "Dat", "从…醒来", "Er wachte aus einem Traum auf."),),
    "aus-sein": (("mit", "Dat", "结束", "Es ist aus mit unserer Freundschaft."),),
    "ausarten": (("in", "Akk", "演变成", "Die Diskussion artete in einen Streit aus."),),
    "ausgeben": (("für", "Akk", "花费", "Sie gibt viel Geld für Bücher aus."),),
    "ausgehen": (("von", "Dat", "以…为前提", "Die Theorie geht von einfachen Annahmen aus."),),
    "ausreichen": (("für", "Akk", "足够用于", "Das Geld reicht für die Miete aus."),),
    "ausreichend": (("für", "Akk", "对…足够", "Die Vorräte sind ausreichend für den Winter."),),
    "ausrichten": (("auf", "Akk", "将…对准", "Er richtet die Kamera auf das Denkmal."), ("nach", "Dat", "(sich) 按照…调整", "Wir richten uns nach deinem Rat."), ("an", "Dat", "(sich) 以…为准", "Das Projekt richtet sich an den Bedürfnissen aus.")),
    "aussagen": (("über", "Akk", "陈述关于", "Er sagt über das Unglück aus."), ("gegen", "Akk", "作证指控", "Die Zeugin sagt gegen den Angeklagten aus.")),
    "ausschließen": (("aus", "Dat", "把…开除出", "Der Spieler wurde aus dem Team ausgeschlossen."), ("von", "Dat", "将…排除在…外", "Sie schloss ihn von der Besprechung aus.")),
    "aussehen": (("nach", "Dat", "看起来像", "Das sieht nach Regen aus."),),
    "aussprechen": (("für", "Akk", "(sich) 赞成", "Ich spreche mich für den Plan aus."), ("gegen", "Akk", "(sich) 反对", "Sie spricht sich gegen die Idee aus.")),
    "aussteigen": (("aus", "Dat", "从…下车/退出", "Sie steigt aus dem Zug aus."),),
    "austauschen": (("gegen", "Akk", "用…替换", "Er tauscht das alte Gerät gegen ein neues aus."), ("mit", "Dat", "与…交流", "Sie tauscht sich mit ihrer Kollegin aus."), ("über", "Akk", "交流…", "Wir tauschten uns über das Projekt aus.")),
    "ausweichen": (("auf", "Akk", "改用", "Der Redner wich auf ein anderes Thema aus."),),
    "auswählen": (("aus", "Dat", "从…选出", "Sie wählt ein Buch aus dem Regal aus."),),
    "basieren": (("auf", "Dat", "基于", "Die Theorie basiert auf alten Quellen."),),
    "basteln": (("an", "Dat", "制作", "Er bastelt an einem Regal."),),
    "bauen": (("auf", "Akk", "信赖", "Wir bauen auf dich."),),
    "beauftragen": (("mit", "Dat", "委托", "Der Chef beauftragt sie mit der Planung."),),
    "bedenken": (("mit", "Dat", "给予", "Er bedachte sie mit einem Geschenk."),),
    "bedeutsam": (("für", "Akk", "对…重要", "Das ist bedeutsam für unsere Zukunft."),),
    "befangen": (("in", "Dat", "拘泥于", "Er ist in seinen Vorurteilen befangen."),),
    "befassen": (("mit", "Dat", "(sich) 处理", "Sie befasst sich mit diesem Problem."),),
    "befreit": (("von", "Dat", "脱离，免除", "Er ist von allen Ängsten befreit."),),
    "befähigen": (("zu", "Dat", "使能，胜任", "Diese Ausbildung befähigt ihn zu dieser Arbeit."),),
    "begeistert": (("von", "Dat", "对…热情", "Sie ist von dem Film begeistert."), ("über", "Akk", "因…兴奋", "Er ist über das Geschenk begeistert.")),
    "beginnen": (("mit", "Dat", "以…开始", "Die Versammlung beginnt mit einer Rede."),),
    "begrenzt": (("auf", "Akk", "局限于", "Die Teilnehmerzahl ist auf zwanzig begrenzt."),),
    "begründen": (("mit", "Dat", "用…说明理由", "Er begründet seine Entscheidung mit Zeitmangel."),),
    "beharren": (("auf", "Dat", "坚持", "Er beharrt auf seiner Meinung."),),
    "behaupten": (("gegen", "Akk", "(sich) 坚持住", "Er muss sich gegen die Konkurrenz behaupten."),),
    "bekannt": (("für", "Akk", "因…闻名", "Die Stadt ist für ihre Architektur bekannt."),),
    "beliebt": (("bei", "Dat", "受…欢迎", "Sie ist bei ihren Schülern beliebt."),),
    "beraten": (("über", "Akk", "就…咨询", "Wir beraten über den Vertrag."),),
    "berechtigt": (("zu", "Dat", "有权…", "Er ist zu dieser Leistung berechtigt."),),
    "bereit": (("zu", "Dat", "愿意", "Er ist zu einem Kompromiss bereit."),),
    "berichten": (("über", "Akk", "报道…", "Der Reporter berichtet über den Unfall."),),
    "berichteten": (("über", "Akk", "报道…", "Sie berichteten über das Ereignis."),),
    "berücksichtigen": (("bei", "Dat", "在…时考虑", "Er berücksichtigte meine Vorschläge bei der Planung."),),
    "berühmt": (("für", "Akk", "因…而著名", "Sie ist berühmt für ihre Musik."),),
    "beschließen": (("über", "Akk", "就…作出决定", "Der Ausschuss beschloss über den Antrag."),),
    "beschränken": (("auf", "Akk", "(sich)限制在，局限于", "Die Ausgaben beschränken sich auf das Nötigste."),),
    "beschäftigen": (("mit", "Dat", "(sich)从事/研究", "Ich beschäftige mich mit deutscher Literatur."),),
    "besetzen": (("mit", "Dat", "用…填充/配备", "Sie besetzten die Stelle mit einem Experten."),),
    "besetzt": (("mit", "Dat", "被…占据/布满", "Der Platz war mit Menschen besetzt."),),
    "bestehen": (("auf", "Dat", "坚持", "Er besteht auf seiner Meinung."), ("aus", "Dat", "由…组成", "Das Team besteht aus fünf Personen."), ("in", "Dat", "在于", "Die Aufgabe besteht in der Analyse der Daten.")),
    "bestimmt": (("für", "Akk", "为…准备", "Das Geld ist für die Renovierung bestimmt."),),
    "bestrafen": (("für", "Akk", "因…惩罚", "Er wurde für seine Tat bestraft."),),
    "beteiligen": (("an", "Dat", "(sich)参与", "Er beteiligt sich an der Diskussion."),),
    "betrachten": (("als", "Akk", "视为", "Er betrachtet den Plan als einen Fehler."),),
    "betrügen": (("um", "Akk", "骗取", "Er betrog sie um ihr Geld."),),
    "beurteilen": (("nach", "Dat", "依据…评价", "Man beurteilt ihn nach seiner Leistung."),),
    "bewerben": (("um", "Akk", "(sich)申请职位", "Er bewirbt sich um die Stelle."), ("bei", "Dat", "(sich)向…求职", "Sie bewirbt sich bei einer Bank.")),
    "bewerten": (("mit", "Dat", "用…评分", "Die Leistung wird mit Noten bewertet."),),
    "bezahlen": (("für", "Akk", "为…付款", "Er bezahlt für das Essen."),),
    "bieten": (("auf", "Akk", "出价", "Er bietet auf das Gemälde."),),
    "bitten": (("um", "Akk", "请求", "Er bittet mich um Hilfe."),),
    "bleiben": (("bei", "Dat", "坚持", "Er bleibt bei seiner Meinung."),),
    "blind": (("für", "Akk", "对…视而不见", "Er ist blind für seine Fehler."),),
    "brauchbare": (("für", "Akk", "适用于", "Dieses Werkzeug ist brauchbar für Heimwerker."), ("als", "Akk", "可用作", "Dieser Stoff ist brauchbar als Tischdecke.")),
    "brechen": (("mit", "Dat", "与…决裂", "Er brach mit seiner Vergangenheit."),),
    "brennen": (("auf", "Akk", "渴望", "Sie brennt auf die Nachricht."), ("für", "Akk", "为…燃烧", "Er brennt für seine Idee.")),
    "bringen": (("auf", "Akk", "使想到", "Das bringt mich auf eine Idee."), ("um", "Akk", "使失去", "Er brachte ihn um sein Vermögen.")),
    "böse": (("auf", "Akk", "生气", "Sie ist böse auf ihn."),),
    "chatten": (("mit", "Dat", "与…聊天", "Ich chatte mit einem Freund."),),
    "dankbar": (("für", "Akk", "感激", "Ich bin dir für deine Hilfe dankbar."),),
    "danken": (("für", "Akk", "为…感谢", "Ich danke dir für deine Hilfe."),),
    "darstellen": (("als", "Akk", "把…描述为", "Er stellt sich als Held dar."),),
    "dekorieren": (("mit", "Dat", "用…装饰", "Sie dekoriert das Zimmer mit Blumen."),),
    "denken": (("an", "Akk", "想到", "Ich denke oft an meine Familie."),),
    "differenzieren": (("zwischen", "Dat", "区分, 辨别", "Man muss zwischen Tatsachen und Meinungen differenzieren."),),
    "diskutieren": (("über", "Akk", "讨论关于", "Wir diskutieren über das neue Gesetz."), ("mit", "Dat", "与...讨论", "Er diskutiert mit seinem Kollegen.")),
    "dotieren": (("mit", "Dat", "以…支付酬金", "Die Stelle ist mit 6000 Euro dotiert."),),
    "drehen": (("um", "Akk", "围绕, 关系到", "Die Erde dreht sich um die Sonne."),),
    "drücken": (("auf", "Akk", "按, 压", "Drück bitte auf den Knopf."),),
    "durchsetzt": (("mit", "Dat", "夹杂，充满", "Die Luft ist mit Staub durchsetzt."),),
    "durstig": (("nach", "Dat", "渴望", "Er ist durstig nach Wissen."),),
    "ehrlich": (("mit", "Dat", "对…诚实", "Sei ehrlich mit mir!"),),
    "einbinden": (("in", "Akk", "纳入", "Wir binden alle Kollegen in das Projekt ein."),),
    "einbrechen": (("in", "Akk", "闯入", "Die Diebe brachen in das Geschäft ein."),),
    "einfallen": (("in", "Akk", "入侵", "Die Truppen fielen in das Land ein."),),
    "einfügen": (("in", "Akk", "插入", "Bitte fügen Sie das Bild in das Dokument ein."),),
    "einführen": (("in", "Akk", "引入", "Er führte die Gäste in den Saal ein."),),
    "einordnen": (("in", "Akk", "归入", "Bitte ordnen Sie die Akten in den Schrank ein."),),
    "einpacken": (("in", "Akk", "包入", "Sie packte das Geschenk in buntes Papier ein."),),
    "einrichten": (("auf", "Akk", "(sich)做准备", "Wir richten uns auf lange Verhandlungen ein."),),
    "einschalten": (("in", "Akk", "(sich) 干预", "Er schaltet sich in die Diskussion ein."),),
    "einschreiben": (("in", "Akk", "(sich) 报名", "Ich schreibe mich in den Kurs ein."),),
    "einsetzen": (("für", "Akk", "(sich) 致力于", "Er setzt sich für die Umwelt ein."), ("gegen", "Akk", "(sich) 反对", "Sie setzt sich gegen Rassismus ein.")),
    "einsteigen": (("in", "Akk", "登上", "Wir steigen in den Zug ein."),),
    "einstellen": (("auf", "Akk", "(sich) 适应", "Er stellt sich auf die neue Situation ein."),),
    "eintragen": (("in", "Akk", "(sich) 登记", "Er trägt sich in das Gästebuch ein."),),
    "eintreten": (("für", "Akk", "支持", "Er tritt für die Rechte der Arbeiter ein."), ("in", "Akk", "加入", "Sie tritt in den Verein ein."), ("gegen", "Akk", "反对", "Wir treten gegen Gewalt ein.")),
    "einverstanden": (("mit", "Dat", "同意", "Ich bin mit dem Plan einverstanden."),),
    "einverstanden-sein": (("mit", "Dat", "同意", "Sie ist mit dem Vorschlag einverstanden."),),
    "einweihen": (("in", "Akk", "告知，使知晓", "Er weiht mich in das Geheimnis ein."),),
    "einzahlen": (("auf", "Akk", "存入", "Ich zahle Geld auf mein Konto ein."),),
    "einziehen": (("in", "Akk", "搬入", "Sie zieht in die neue Wohnung ein."),),
    "einzuschleusen": (("in", "Akk", "偷运", "Sie versuchen, Waffen in das Land einzuschleusen."),),
    "einzuschleussen": (("in", "Akk", "偷运", "Sie versuchen, Waffen in das Land einzuschleussen."),),
    "empfänglich": (("für", "Akk", "对…敏感", "Sie ist empfänglich für neue Ideen."),),
    "empört": (("über", "Akk", "对…愤怒", "Sie ist empört über die Entscheidung."),),
    "enden": (("mit", "Dat", "以…结束", "Das Fest endet mit einem Feuerwerk."), ("in", "Dat", "以…告终", "Die Straße endet in einer Sackgasse.")),
    "entfernen": (("von", "Dat", "从…移开", "Er entfernte das Etikett von der Flasche."),),
    "entlassen": (("aus", "Dat", "从…放出", "Er wurde aus dem Krankenhaus entlassen."), ("in", "Akk", "使进入退休", "Der Beamte wurde in den Ruhestand entlassen.")),
    "entlehntes": (("aus", "Dat", "从…借用", "Ein entlehntes Wort aus dem Griechischen."),),
    "entlohnen": (("mit", "Dat", "用…酬谢", "Er entlohnt seine Mitarbeiter mit einem Bonus."),),
    "entrüstet": (("über", "Akk", "对…愤慨", "Sie ist entrüstet über die Lüge."),),
    "entscheiden": (("über", "Akk", "决定", "Der Richter entscheidet über den Fall."), ("für", "Akk", "(sich)决定选择", "Ich entscheide mich für das blaue Kleid.")),
    "entschlossen": (("zu", "Dat", "决心…", "Er ist entschlossen zu einem Neuanfang."),),
    "entschuldigen": (("für", "Akk", "(sich)为…道歉", "Ich entschuldige mich für die Verspätung."), ("bei", "Dat", "(sich)向…道歉", "Er entschuldigt sich bei seinem Chef.")),
    "entstehen": (("aus", "Dat", "由…产生", "Aus dem Projekt entstehen viele Ideen."),),
    "entwickeln": (("zu", "Dat", "(sich)发展成", "Die Stadt entwickelt sich zu einem Zentrum."),),
    "erfahren": (("von", "Dat", "得知", "Ich habe von dem Unfall erfahren."),),
    "ergänzen": (("um", "Akk", "补充…", "Wir ergänzen das Team um zwei Leute."),),
    "erinnern": (("an", "Akk", "(sich)记得", "Ich erinnere mich an den Tag."),),
    "erklären": (("für", "Akk", "宣布为", "Die Regierung erklärte den Vertrag für ungültig."), ("zu", "Dat", "任命为", "Sie erklärte ihn zu ihrem Stellvertreter.")),
    "ermitteln": (("gegen", "Akk", "调查", "Die Polizei ermittelt gegen den Verdächtigen."),),
    "ernst": (("mit", "Dat", "对…认真", "Er ist ernst mit seiner Arbeit."),),
    "ernähren": (("von", "Dat", "(sich) 以…为食", "Er ernährt sich von Obst und Gemüse."),),
    "erschrecken": (("über", "Akk", "对…感到惊吓", "Ich erschrak über die laute Stimme."), ("vor", "Dat", "被…吓到", "Das Kind erschrickt vor dem lauten Hund.")),
    "erschüttert": (("über", "Akk", "对…感到震惊", "Sie war über die Nachricht zutiefst erschüttert."),),
    "ersetzen": (("durch", "Akk", "用…替换", "Wir ersetzen das alte Gerät durch ein neues."),),
    "erwachsen": (("aus", "Dat", "由…产生", "Aus dem Konflikt erwachsen neue Probleme."), ("zu", "Dat", "成长为", "Sie ist zu einer starken Persönlichkeit erwachsen.")),
    "erwarten": (("von", "Dat", "对…有期望", "Das erwarte ich von dir."),),
    "erziehen": (("zu", "Dat", "培养成…", "Sie erzieht ihr Kind zu einem selbstbewussten Menschen."),),
    "erzählen": (("von", "Dat", "讲述…", "Er erzählt von seiner Reise durch Europa."), ("über", "Akk", "谈论…", "Sie erzählt über ihre Arbeit in der Firma.")),
    "fallen": (("unter", "Akk", "属于", "Das fällt unter das Urheberrecht."),),
    "fehlen": (("an", "Dat", "缺少", "Es fehlt an Geld."),),
    "feindselig": (("gegenüber", "Dat", "敌视", "Sie ist feindselig gegenüber ihren Kollegen."),),
    "feindselige": (("gegenüber", "Dat", "敌视", "Sie ist feindselig gegenüber ihren Kollegen."),),
    "fertig": (("mit", "Dat", "完成，结束", "Ich bin endlich mit der Arbeit fertig."), ("für", "Akk", "准备好", "Wir sind fertig für den großen Tag.")),
    "fertig-sein": (("mit", "Dat", "完成", "Er ist mit der Arbeit fertig."),),
    "festhalten": (("an", "Dat", "坚持", "Sie hält an ihrer Meinung fest."),),
    "festlegen": (("auf", "Akk", "确定", "Er legt sich auf den Termin fest."),),
    "fit-sein": (("für", "Akk", "为…做好准备", "Er ist fit für die Prüfung."), ("in", "Dat", "擅长", "Sie ist fit in Mathe.")),
    "fliehen": (("vor", "Dat", "逃离，躲避", "Die Menschen fliehen vor dem Krieg."),),
    "folgen": (("auf", "Akk", "紧跟其后", "Der Sommer folgt auf den Frühling."), ("aus", "Dat", "源于", "Das folgt aus den Fakten.")),
    "folgenreich": (("für", "Akk", "对…影响深远", "Der Krieg war folgenreich für Europa."),),
    "fordern": (("von", "Dat", "向…要求", "Ich fordere eine Antwort von dir."),),
    "fragen": (("nach", "Dat", "询问，打听", "Er fragt nach dem Weg."), ("um", "Akk", "请求得到", "Sie fragt um Hilfe.")),
    "frech": (("zu", "Dat", "对…无礼", "Der Junge war frech zu seiner Lehrerin."),),
    "fressen": (("an", "Dat", "啃，侵蚀", "Der Hund frisst an einem Knochen."),),
    "freuen": (("auf", "Akk", "(sich)期待", "Ich freue mich auf die Ferien."), ("über", "Akk", "(sich)为…高兴", "Sie freut sich über das Geschenk.")),
    "freundlich": (("zu", "Dat", "对…友好", "Sie ist freundlich zu allen Gästen."),),
    "froh": (("über", "Akk", "对…感到高兴", "Ich bin froh über deine Hilfe."),),
    "fähig": (("zu", "Dat", "有能力", "Er ist zu großen Leistungen fähig."),),
    "führen": (("zu", "Dat", "导致", "Das führt zu vielen Problemen."),),
    "garantieren": (("für", "Akk", "为…担保", "Die Firma garantiert für die Qualität."),),
    "geboren": (("für", "Akk", "天生适合", "Du bist für diesen Beruf geboren."),),
    "geeignet": (("für", "Akk", "适合", "Dieser Kurs ist für Anfänger geeignet."), ("zu", "Dat", "适于", "Er ist zu dieser Aufgabe geeignet.")),
    "gefährlich": (("für", "Akk", "对…危险", "Rauchen ist für die Gesundheit gefährlich."),),
    "gegensteuern": (("gegen", "Akk", "对…采取对策", "Wir müssen gegen die Inflation gegensteuern."),),
    "gehen": (("um", "Akk", "涉及", "Es geht um die wichtigste Frage."),),
    "gehören": (("zu", "Dat", "属于", "Dieses Buch gehört zu meiner Sammlung."),),
    "gelegen": (("an", "Dat", "重视，在乎", "Mir ist an einer Lösung gelegen."),),
    "gelten": (("für", "Akk", "适用于", "Das gilt für alle Teilnehmer."),),
    "gepflastert": (("mit", "Dat", "铺有，用…铺", "Der Weg ist mit Kies gepflastert."),),
    "geprüft": (("auf", "Akk", "检测，检验", "Die Probe wird auf Bakterien geprüft."),),
    "gerecht": (("gegenüber", "Dat", "对…公正", "Er ist gerecht gegenüber allen Mitarbeitern."),),
    "geschieden": (("von", "Dat", "与…离婚的", "Er ist von seiner Frau geschieden."),),
    "gespannt": (("auf", "Akk", "对…期待/好奇", "Ich bin gespannt auf das Ergebnis."),),
    "gesperrt": (("für", "Akk", "对…封锁", "Die Straße ist für den Verkehr gesperrt."),),
    "gewinnen": (("an", "Dat", "在…方面增长", "Das Projekt gewinnt an Bedeutung."), ("gegen", "Akk", "战胜…", "Die Mannschaft gewann gegen den Gegner.")),
    "gewohnt": (("an", "Akk", "习惯于…的", "Er ist an die Kälte gewohnt."),),
    "gewöhnen": (("an", "Akk", "(sich)习惯于", "Ich gewöhne mich an das Klima."),),
    "glauben": (("an", "Akk", "相信", "Sie glaubt an den Erfolg."),),
    "glücklich": (("über", "Akk", "对…高兴", "Sie ist glücklich über das Geschenk."),),
    "gratulieren": (("zu", "Dat", "祝贺", "Wir gratulieren ihr zu ihrem Erfolg."),),
    "greifen": (("nach", "Dat", "抓取", "Er greift nach dem Glas."),),
    "gründen": (("auf", "Akk", "(sich)基于", "Das Argument gründet sich auf Fakten."),),
    "gut": (("in", "Dat", "擅长", "Er ist gut in Mathe."), ("zu", "Dat", "对…好", "Sie ist gut zu ihren Kindern."), ("für", "Akk", "对…有益", "Das ist gut für deine Gesundheit.")),
    "gültig": (("für", "Akk", "对…有效", "Dieser Ausweis ist gültig für zwei Jahre."),),
    "gültig-sein": (("für", "Akk", "对…有效", "Der Vertrag ist gültig für ein Jahr."),),
    "günstig": (("für", "Akk", "对…有利", "Das Angebot ist günstig für uns."),),
    "haltbar": (("für", "Akk", "可保存", "Die Milch ist haltbar für drei Tage."),),
    "halten": (("für", "Akk", "把…看作", "Ich halte ihn für einen Lügner."), ("von", "Dat", "对…的看法", "Was hältst du von dem neuen Film?"), ("auf", "Akk", "重视", "Er hält auf sein Äußeres."), ("zu", "Dat", "忠于", "Er hält zu seinem Freund.")),
    "handeln": (("von", "Dat", "涉及", "Das Buch handelt von einem Drachen."), ("mit", "Dat", "交易", "Er handelt mit antiken Möbeln."), ("um", "Akk", "涉及(sich)", "Es handelt sich um ein wichtiges Thema.")),
    "hart": (("zu", "Dat", "对…严厉", "Der Lehrer ist hart zu den Schülern."),),
    "hassen": (("an", "Dat", "讨厌…的方面", "Ich hasse an ihm seine Ungeduld."),),
    "heiß": (("auf", "Akk", "渴望", "Ich bin heiß auf das Konzert."),),
    "helfen": (("bei", "Dat", "帮忙做", "Er hilft mir bei den Hausaufgaben."),),
    "herrscht": (("über", "Akk", "统治", "Der König herrscht über das Land."),),
    "hindeute": (("auf", "Akk", "表明", "Die Daten deuten auf eine Besserung hin."),),
    "hineinfuchsen": (("in", "Akk", "(sich)钻研", "Er fuchst sich in die Mathematik hinein."),),
    "hinweisen": (("auf", "Akk", "指出", "Er weist auf den Fehler hin."),),
    "hinzufügen": (("zu", "Dat", "添加到", "Fügen Sie Wasser zu der Suppe hinzu."),),
    "hinzukommen": (("zu", "Dat", "添加到", "Zu den Kosten kommt ein Aufschlag hinzu."),),
    "hoffen": (("auf", "Akk", "希望", "Wir hoffen auf besseres Wetter."),),
    "hungrig": (("nach", "Dat", "渴望", "Er ist hungrig nach Erfolg."),),
    "hängen": (("an", "Dat", "依恋", "Sie hängt sehr an ihrer Mutter."),),
    "höflich": (("zu", "Dat", "对…有礼貌", "Er ist höflich zu seinen Gästen."),),
    "hören": (("auf", "Akk", "听从", "Er hört auf seinen Vater."), ("von", "Dat", "听说", "Ich habe von dem Unfall gehört.")),
    "ideal": (("für", "Akk", "适合", "Dieses Buch ist ideal für Anfänger."),),
    "infizieren": (("mit", "Dat", "(sich) 感染上", "Er hat sich mit dem Virus infiziert."),),
    "informieren": (("über", "Akk", "通知；告知", "Wir informieren die Gäste über die Terminänderung."),),
    "integrieren": (("in", "Akk", "使融入/整合", "Wir müssen die Flüchtlinge in die Gesellschaft integrieren."),),
    "interagieren": (("mit", "Dat", "与…互动", "Der Lehrer interagiert mit den Schülern."),),
    "interessant": (("für", "Akk", "对…有趣", "Das Angebot ist interessant für Kunden."),),
    "interessieren": (("für", "Akk", "(sich)对…感兴趣", "Er interessiert sich für Politik."),),
    "interessiert": (("an", "Dat", "对…感兴趣", "Sie ist an Technik interessiert."),),
    "interpretieren": (("als", "Akk", "解释为", "Sie interpretierte seine Worte als Kritik."),),
    "jammern": (("über", "Akk", "抱怨", "Sie jammerte über den hohen Preis."),),
    "kapitulieren": (("vor", "Dat", "向…投降", "Er kapitulierte vor der Schwierigkeit."),),
    "klagen": (("über", "Akk", "抱怨", "Sie klagt über die lautstarke Musik."), ("gegen", "Akk", "控告", "Er klagt gegen seinen Nachbarn."), ("auf", "Akk", "索赔", "Der Anwalt klagt auf Schadenersatz.")),
    "klar": (("über", "Akk", "(sich) 意识到", "Ich bin mir über die Risiken klar."),),
    "kleben": (("an", "Dat", "粘在…上", "Der Aufkleber klebt an der Tür."),),
    "klicken": (("auf", "Akk", "点击", "Klicken Sie auf den Link."),),
    "klingen": (("nach", "Dat", "听起来像", "Das klingt nach einem guten Plan."),),
    "klopfen": (("an", "Akk", "敲击", "Er klopft an die Tür."),),
    "knapp": (("an", "Dat", "缺乏", "Wir sind knapp an Zeit."),),
    "kommen": (("auf", "Akk", "想到", "Ich komme auf eine gute Idee."), ("zu", "Dat", "达到", "Wir kommen zu einem Ergebnis."), ("um", "Akk", "失去", "Er kam um sein Leben."), ("über", "Akk", "侵袭", "Eine große Freude kam über mich.")),
    "kontrollieren": (("auf", "Akk", "检查有无", "Der Arzt kontrolliert den Patienten auf Symptome."),),
    "kramen": (("in", "Dat", "翻找", "Sie kramt in ihrer Handtasche."),),
    "krank": (("an", "Dat", "患…病", "Er ist an Tuberkulose krank."),),
    "kratzen": (("an", "Dat", "抓挠", "Die Katze kratzt an der Tür."),),
    "kritisch": (("gegenüber", "Dat", "对…持批判", "Sie ist kritisch gegenüber dem Plan."),),
    "kämpfen": (("für", "Akk", "为...战斗", "Er kämpft für seine Rechte."), ("gegen", "Akk", "反对...", "Wir kämpfen gegen die Verschmutzung."), ("um", "Akk", "争夺", "Sie kämpfen um den Titel."), ("mit", "Dat", "与...斗争", "Ich kämpfe mit meiner Angst.")),
    "kümmern": (("um", "Akk", "(sich)照顾", "Sie kümmert sich um die Kinder."),),
    "lachen": (("über", "Akk", "嘲笑", "Wir lachen über den Witz."),),
    "leben": (("von", "Dat", "靠…生活", "Er lebt von seinem Gehalt."), ("für", "Akk", "为…而活", "Sie lebt für die Musik."), ("mit", "Dat", "与…一起生活", "Sie lebt mit ihrer Familie.")),
    "leer": (("an", "Dat", "缺乏", "Das Hotel ist leer an Gästen."),),
    "leiden": (("an", "Dat", "患（病）", "Er leidet an einer Allergie."), ("unter", "Dat", "受…之苦", "Sie leidet unter dem Lärm.")),
    "lieb": (("zu", "Dat", "对…友好", "Er ist lieb zu seiner Schwester."),),
    "liegen": (("an", "Dat", "取决于", "Das liegt an dir."), ("in", "Dat", "在于", "Das Problem liegt in der Planung.")),
    "loben": (("für", "Akk", "因…表扬", "Der Lehrer lobt den Schüler für die Arbeit."),),
    "lächeln": (("über", "Akk", "对…微笑", "Sie lächelt über den Witz."),),
    "machen": (("aus", "Dat", "用…做", "Ich mache aus Papier ein Flugzeug."),),
    "maßgeblich": (("für", "Akk", "对…起决定作用", "Diese Faktoren sind maßgeblich für den Erfolg."),),
    "meinen": (("mit", "Dat", "意指", "Was meinst du mit diesem Satz?"), ("zu", "Dat", "对…的看法", "Was meinen Sie zu unserem Vorschlag?")),
    "melden": (("bei", "Dat", "(sich) 联系; 报到", "Er meldet sich bei seinem alten Lehrer."), ("für", "Akk", "(sich) 报名参加", "Sie meldet sich für einen Sprachkurs.")),
    "messen": (("an", "Dat", "以…衡量", "Man misst den Erfolg an den Ergebnissen."), ("mit", "Dat", "(sich) 与…较量", "Er misst sich mit seinem Bruder im Schach.")),
    "mischen": (("mit", "Dat", "把…与…混合", "Du musst die Farbe mit Wasser mischen."), ("in", "Akk", "(sich) 干涉，插手", "Du solltest dich nicht in ihre Angelegenheiten mischen."), ("unter", "Akk", "(sich) 混入，混进", "Er mischt sich unter die Zuschauer.")),
    "mitgerissen": (("von", "Dat", "被…深深打动", "Das Publikum war von der Musik mitgerissen."),),
    "mithalten": (("mit", "Dat", "跟得上，不落后", "Der neue Mitarbeiter kann mit den Experten mithalten."),),
    "mitmachen": (("bei", "Dat", "参与，参加", "Alle Schüler machen bei dem Projekt mit."),),
    "mitspielen": (("bei", "Dat", "参与；参加游戏", "Die Kinder spielen bei dem Theaterstück mit."),),
    "müde": (("von", "Dat", "因...而累", "Er ist müde von der langen Reise."),),
    "nachdenken": (("über", "Akk", "思考", "Ich denke über das Problem nach."),),
    "neidisch": (("auf", "Akk", "嫉妒", "Er ist neidisch auf seinen Bruder."),),
    "nennen": (("nach", "Dat", "以…命名", "Das Kind wurde nach seinem Großvater genannt."),),
    "nett": (("zu", "Dat", "对…友好", "Er ist nett zu allen Kollegen."),),
    "neugierig": (("auf", "Akk", "好奇", "Ich bin neugierig auf das Ergebnis."),),
    "notwendig": (("für", "Akk", "对…必要", "Genügend Schlaf ist notwendig für die Gesundheit."),),
    "nördlich": (("von", "Dat", "在…以北", "Die Stadt liegt nördlich von Berlin."),),
    "nötig": (("für", "Akk", "对…必要", "Das Werkzeug ist nötig für die Reparatur."),),
    "nützen": (("zu", "Dat", "用于，有助于", "Das nützt zu nichts."),),
    "nützlich": (("für", "Akk", "对…有用", "Dieses Buch ist nützlich für Studenten."),),
    "offen": (("für", "Akk", "乐于接受", "Ich bin offen für neue Ideen."),),
    "passen": (("zu", "Dat", "适合，相配", "Die Schuhe passen zu dem Kleid."),),
    "passieren": (("mit", "Dat", "发生在…身上", "Was ist mit dir passiert?"),),
    "plaudern": (("mit", "Dat", "与…聊天", "Sie plaudert mit ihrer Freundin."),),
    "plädieren": (("für", "Akk", "为…辩护", "Er plädiert für mehr Umweltschutz."), ("auf", "Akk", "要求（判刑）", "Der Anwalt plädiert auf Freispruch.")),
    "populär": (("bei", "Dat", "在…中受欢迎", "Der Politiker ist populär bei der Jugend."),),
    "profilieren": (("durch", "Akk", "通过…脱颖而出", "Er profiliert sich durch seine Fachkenntnisse."), ("mit", "Dat", "以…树立形象", "Sie profiliert sich mit innovativen Ideen.")),
    "protestieren": (("gegen", "Akk", "抗议...", "Die Bürger protestieren gegen die Steuererhöhung."),),
    "prüfen": (("auf", "Akk", "检查…方面", "Der Arzt prüft den Patienten auf Allergien."),),
    "raten": (("auf", "Akk", "猜测", "Ich rate auf ein Unentschieden."), ("zu", "Dat", "建议", "Ich rate dir zu mehr Geduld.")),
    "reagieren": (("auf", "Akk", "对…作出反应", "Sie reagiert empfindlich auf Kritik."),),
    "rechnen": (("mit", "Dat", "预计", "Wir rechnen mit Regen."),),
    "rechtfertigen": (("mit", "Dat", "用…辩解", "Er rechtfertigt seine Tat mit Notwehr."), ("vor", "Dat", "(sich)在…面前辩解", "Sie muss sich vor der Jury rechtfertigen.")),
    "reden": (("von", "Dat", "谈论", "Sie redet von ihrem Urlaub."), ("über", "Akk", "谈论", "Wir reden über das Wetter."), ("mit", "Dat", "与…交谈", "Er redet mit seinem Nachbarn.")),
    "reduzieren": (("auf", "Akk", "减少到", "Wir reduzieren die Ausgaben auf das Nötigste."), ("um", "Akk", "减少了", "Der Preis wurde um 20 Prozent reduziert.")),
    "referieren": (("über", "Akk", "就…作报告", "Sie referiert über aktuelle Themen."),),
    "reflektieren": (("über", "Akk", "反思", "Er reflektiert über seine Fehler."),),
    "reichen": (("für", "Akk", "足够", "Das Geld reicht für die Miete."), ("zu", "Dat", "足够用于", "Das Material reicht zu einem Tisch.")),
    "reif": (("für", "Akk", "对…成熟", "Er ist reif für die Prüfung."),),
    "reinigen": (("von", "Dat", "清除…", "Sie reinigt die Wunde von Schmutz."),),
    "reizvoll": (("für", "Akk", "对…有吸引力", "Das Angebot ist reizvoll für Kunden."),),
    "relevant": (("für", "Akk", "对…重要", "Diese Information ist relevant für das Projekt."),),
    "reservieren": (("für", "Akk", "为…预订", "Ich reserviere einen Platz für meinen Bruder."),),
    "retten": (("aus", "Dat", "从…中救出", "Er rettet das Kind aus dem Wasser."), ("vor", "Dat", "使免于", "Die Impfung rettet viele vor der Krankheit.")),
    "riechen": (("nach", "Dat", "闻起来有…", "Der Raum riecht nach Kaffee."),),
    "rufen": (("nach", "Dat", "呼喊", "Er ruft nach dem Arzt."), ("um", "Akk", "呼求", "Sie ruft um Hilfe.")),
    "rumbasteln": (("an", "Dat", "摆弄", "Er bastelt an seinem Fahrrad rum."),),
    "rücksichtslose": (("gegen", "Akk", "对…无情", "Sie ist rücksichtslos gegen ihre Feinde."), ("gegenüber", "Dat", "对…无情", "Er ist rücksichtslos gegenüber seinen Kollegen.")),
    "sagen": (("zu", "Dat", "对…说", "Was sagen Sie zu diesem Plan?"), ("über", "Akk", "关于…说", "Er sagt nichts über seine Pläne.")),
    "sauer": (("auf", "Akk", "生…的气", "Ich bin sauer auf meinen Bruder."), ("über", "Akk", "对…生气", "Sie ist sauer über die Kritik.")),
    "schalten": (("auf", "Akk", "切换到", "Er schaltet auf Empfang."),),
    "scharf": (("auf", "Akk", "渴望", "Er ist scharf auf das Angebot."),),
    "schauen": (("auf", "Akk", "看，注视", "Sie schaut auf die Straße."), ("nach", "Dat", "看，照看", "Er schaut nach dem Bus.")),
    "scheitern": (("an", "Dat", "失败于", "Das Projekt scheitert an der Finanzierung."),),
    "schicken": (("nach", "Dat", "派人去请", "Wir schicken nach einem Arzt."),),
    "schieben": (("auf", "Akk", "推卸给", "Er schiebt die Schuld auf seinen Kollegen."),),
    "schießen": (("auf", "Akk", "朝...射击", "Der Jäger schießt auf den Hasen."),),
    "schimpfen": (("auf", "Akk", "骂", "Er schimpft auf das Wetter."), ("über", "Akk", "抱怨", "Sie schimpft über die schlechte Note."), ("mit", "Dat", "责骂", "Die Mutter schimpft mit ihrem Sohn.")),
    "schlafen": (("mit", "Dat", "与...睡觉", "Sie schläft mit ihrem Freund."),),
    "schlagen": (("nach", "Dat", "长得像", "Das Kind schlägt nach dem Vater."),),
    "schließen": (("aus", "Dat", "从...推断", "Ich schließe aus seinen Worten, dass er müde ist."), ("auf", "Akk", "推断出", "Man schließt aus den Spuren auf einen Einbrecher.")),
    "schlussfolgern": (("aus", "Dat", "从...推断", "Wir schlussfolgern aus den Daten, dass sich der Trend fortsetzt."),),
    "schmecken": (("nach", "Dat", "有...味道", "Das Essen schmeckt nach Salz."),),
    "schreiben": (("an", "Akk", "写信给", "Ich schreibe einen Brief an meine Mutter."), ("über", "Akk", "写关于", "Er schreibt über das Buch."), ("mit", "Dat", "用…写", "Sie schreibt mit einem Bleistift.")),
    "schreien": (("nach", "Dat", "喊叫要求", "Das Kind schreit nach Hilfe."), ("vor", "Dat", "因…叫喊", "Sie schreit vor Schmerz.")),
    "schrumpfen": (("auf", "Akk", "缩减到", "Die Stadt schrumpft auf 10000 Einwohner."), ("um", "Akk", "减少了", "Das Unternehmen schrumpft um zehn Prozent.")),
    "schuldig": (("an", "Dat", "对…有罪", "Er ist schuldig an dem Unfall."),),
    "schwach": (("in", "Dat", "在…方面弱", "Er ist schwach in Mathematik."),),
    "schweben": (("in", "Dat", "处于…状态", "Er schwebt in großer Gefahr."),),
    "schweigen": (("über", "Akk", "对…沉默", "Sie schweigt über das Problem."), ("zu", "Dat", "对…不予置评", "Er schweigt zu diesem Thema.")),
    "schwierig": (("für", "Akk", "对…困难", "Dieser Test ist schwierig für die Schüler."),),
    "schwitzen": (("vor", "Dat", "因…出汗", "Er schwitzt vor Aufregung."),),
    "schädlich": (("für", "Akk", "对…有害", "Rauchen ist schädlich für die Gesundheit."),),
    "schätzen": (("als", "Akk", "把…视为", "Ich schätze ihn als Freund."), ("an", "Dat", "欣赏…方面", "Ich schätze an ihm seine Ehrlichkeit.")),
    "schütteln": (("mit", "Dat", "摇动…", "Er schüttelt mit dem Kopf."),),
    "schützen": (("vor", "Dat", "保护免受", "Die Creme schützt vor der Sonne."),),
    "sehen": (("nach", "Dat", "查看", "Er sieht nach den Kindern."),),
    "sicher": (("vor", "Dat", "免受…的", "Der Bunker ist sicher vor Bomben."),),
    "sichern": (("vor", "Dat", "保护免受", "Der Helm sichert vor Verletzungen."), ("gegen", "Akk", "防护", "Das Schloss sichert das Fahrrad gegen Diebstahl.")),
    "siegen": (("über", "Akk", "战胜", "Die Mannschaft siegt über den Gegner."),),
    "sinken": (("in", "Akk", "陷入", "Er sinkt in Ohnmacht."),),
    "sorgen": (("für", "Akk", "照料/负责", "Sie sorgt für ihre kranke Mutter."), ("um", "Akk", "(sich)担心", "Ich sorge mich um dich.")),
    "sparen": (("an", "Dat", "节省（某物）", "Wir sparen an Wasser."), ("für", "Akk", "为...存钱", "Ich spare für ein Fahrrad.")),
    "spenden": (("für", "Akk", "为...捐赠", "Sie spendet für den Tierschutz."), ("an", "Akk", "捐赠给...", "Er spendet an die Kirche.")),
    "spielen": (("mit", "Dat", "与...玩；玩弄", "Das Kind spielt mit dem Ball."), ("um", "Akk", "赌博/争夺", "Sie spielen um viel Geld."), ("gegen", "Akk", "与...比赛", "Wir spielen gegen Hamburg.")),
    "sprechen": (("über", "Akk", "谈论", "Wir sprechen über die Prüfung."), ("mit", "Dat", "与…交谈", "Ich spreche mit dem Lehrer."), ("von", "Dat", "提到", "Sie spricht oft von ihrer Reise.")),
    "stammen": (("aus", "Dat", "来自（起源）", "Er stammt aus Italien."), ("von", "Dat", "源自（某人/时代）", "Das Zitat stammt von Goethe.")),
    "stecken": (("in", "Dat", "处于，陷在", "Er steckt in einem Stau."),),
    "stehen": (("auf", "Akk", "喜欢，热衷于", "Ich stehe auf Jazz."), ("zu", "Dat", "支持，信守", "Er steht zu seinem Wort."), ("für", "Akk", "代表，象征", "Dieses Symbol steht für Frieden."), ("vor", "Dat", "面临", "Wir stehen vor einer großen Aufgabe.")),
    "sterben": (("an", "Dat", "死于", "Er starb an einer Lungenentzündung."),),
    "stimmen": (("für", "Akk", "投票赞成", "Ich stimme für den Kandidaten."), ("gegen", "Akk", "投票反对", "Sie stimmte gegen den Vorschlag.")),
    "stinken": (("nach", "Dat", "有...气味", "Der Fisch stinkt nach Ammoniak."),),
    "stolz": (("auf", "Akk", "为…自豪", "Die Eltern sind stolz auf ihre Tochter."),),
    "streben": (("nach", "Dat", "追求", "Alle streben nach Glück."),),
    "streng": (("mit", "Dat", "对...严格", "Er ist streng mit seinem Sohn."),),
    "studieren": (("an", "Dat", "在某大学学习", "Sie studiert an der Universität."),),
    "stören": (("bei", "Dat", "打扰(某人做某事)", "Er stört mich bei der Arbeit."),),
    "stürzen": (("auf", "Akk", "(sich)扑向", "Er stürzt sich auf den Kuchen."), ("in", "Akk", "陷入", "Er stürzt in eine tiefe Krise.")),
    "suchen": (("nach", "Dat", "寻找,搜寻", "Er sucht nach seinem Schlüssel."),),
    "süchtig": (("nach", "Dat", "对…上瘾", "Er ist süchtig nach Alkohol."),),
    "taub": (("für", "Akk", "对…充耳不闻", "Er ist taub für alle Bitten."),),
    "tauschen": (("gegen", "Akk", "用…交换", "Er tauscht das Buch gegen eine CD."), ("mit", "Dat", "与…交换", "Ich tausche den Platz mit dir.")),
    "teilen": (("mit", "Dat", "与…分享", "Er teilt sein Brot mit mir."), ("in", "Akk", "分成", "Sie teilt den Kuchen in vier Stücke.")),
    "teilnehmen": (("an", "Dat", "参加", "Sie nimmt an der Konferenz teil."),),
    "telefonieren": (("mit", "Dat", "与…通电话", "Ich telefoniere mit meiner Mutter."),),
    "testen": (("auf", "Akk", "检测…", "Der Arzt testet das Blut auf Viren."),),
    "tippen": (("auf", "Akk", "猜测；押注", "Ich tippe auf einen Sieg."),),
    "tolerant": (("gegenüber", "Dat", "对…宽容的", "Sie ist tolerant gegenüber anderen Meinungen."),),
    "tragen": (("mit", "Dat", "(sich) 怀有想法", "Ich trage mich mit dem Gedanken, umzuziehen."),),
    "traurig": (("über", "Akk", "对…感到悲伤", "Sie ist traurig über das Ergebnis."),),
    "treffen": (("mit", "Dat", "(sich) 与…见面", "Ich treffe mich mit meinen Freunden."), ("auf", "Akk", "偶然遇到；碰到", "Sie traf auf einen alten Bekannten.")),
    "trinken": (("auf", "Akk", "为…干杯", "Wir trinken auf deine Gesundheit."),),
    "träumen": (("von", "Dat", "梦想", "Sie träumt von einer Weltreise."),),
    "typisch": (("für", "Akk", "典型的", "Das ist typisch für ihn."),),
    "tödlich": (("für", "Akk", "对…致命的", "Dieses Gift ist tödlich für Katzen."),),
    "ubergreifen": (("auf", "Akk", "蔓延到", "Das Feuer griff auf das Dach über."),),
    "umgehen": (("mit", "Dat", "处理，对待", "Er weiß mit Kindern umzugehen."),),
    "umgekommen": (("bei", "Dat", "在…中丧生", "Bei dem Unfall sind zwei Menschen umgekommen."),),
    "umhören": (("nach", "Dat", "(sich)打听", "Er hörte sich nach einem Job um."),),
    "umsatteln": (("auf", "Akk", "改行，改做", "Er sattelt auf Informatik um."),),
    "umsetzen": (("in", "Akk", "实施，转化", "Wir müssen den Plan in die Tat umsetzen."),),
    "umsteigen": (("auf", "Akk", "换乘到", "Er steigt auf die U-Bahn um."), ("in", "Akk", "换乘进", "Er steigt in den Bus um.")),
    "umtauschen": (("in", "Akk", "兑换成", "Er tauscht das Geld in Euro um."), ("gegen", "Akk", "交换", "Ich möchte das Buch gegen ein anderes umtauschen.")),
    "unabdingbar": (("für", "Akk", "对…必不可少", "Ruhe ist unabdingbar für die Arbeit."),),
    "unbeteiligt": (("an", "Dat", "未参与", "Er war an dem Gespräch unbeteiligt."),),
    "unschuldig": (("an", "Dat", "对…无罪", "Sie ist unschuldig an dem Unfall."),),
    "unterhalten": (("über", "Akk", "(sich)聊起", "Wir unterhalten uns über Musik."),),
    "unterrichten": (("über", "Akk", "通知", "Er unterrichtet uns über die neue Regel."), ("in", "Dat", "教授", "Sie unterrichtet in Mathematik.")),
    "unterscheiden": (("zwischen", "Dat", "区分", "Man muss zwischen Tatsachen und Meinungen unterscheiden."), ("von", "Dat", "区别于(sich)", "Er unterscheidet sich von seinen Kollegen.")),
    "unterstützen": (("bei", "Dat", "支持", "Sie unterstützt mich bei der Arbeit."),),
    "untersuchen": (("auf", "Akk", "检查", "Der Arzt untersucht den Patienten auf Krebs."),),
    "verabredet": (("mit", "Dat", "约好", "Ich bin mit ihr verabredet."),),
    "verabredet-sein": (("mit", "Dat", "约好", "Er ist mit dem Arzt verabredet."),),
    "verankert": (("in", "Dat", "扎根于", "Das Recht ist in der Verfassung verankert."),),
    "veranlassen": (("zu", "Dat", "促使", "Das veranlasst mich zu einem Brief."),),
    "verantwortlich": (("für", "Akk", "对…负责", "Sie ist für das Projekt verantwortlich."),),
    "verbinden": (("mit", "Dat", "与…连接", "Bitte verbinden Sie mich mit Herrn Müller."),),
    "verbringen": (("mit", "Dat", "与…度过", "Ich verbringe den Nachmittag mit Freunden."),),
    "verbunden": (("mit", "Dat", "与…相关", "Das Glück ist mit der Gesundheit verbunden."),),
    "verbündete": (("mit", "Dat", "与…结盟", "Die Partei verbündete sich mit der Opposition."),),
    "verdienen": (("an", "Dat", "从…赚钱", "Er verdient viel Geld an seinen Aktien."),),
    "vereinbaren": (("mit", "Dat", "与…约定", "Wir vereinbaren einen Termin mit dem Arzt."),),
    "vererben": (("an", "Akk", "传给某人", "Er vererbt sein Haus an seinen Sohn."),),
    "verfahren": (("mit", "Dat", "对待，处理", "Wir verfahren mit dem Problem vorsichtig."),),
    "verfallen": (("in", "Akk", "陷入", "Er verfällt in Panik."),),
    "verfasst": (("in", "Dat", "以…写成", "Der Text ist in Deutsch verfasst."),),
    "verfügen": (("über", "Akk", "拥有，支配", "Er verfügt über große Erfahrung."),),
    "vergleichen": (("mit", "Dat", "与…比较", "Er vergleicht das Bild mit dem Original."),),
    "verheiratet": (("mit", "Dat", "与…结婚", "Sie ist mit einem Anwalt verheiratet."),),
    "verhängt": (("über", "Akk", "对…施加", "Das Gericht verhängt eine Strafe über ihn."),),
    "verkaufen": (("an", "Akk", "卖给某人", "Sie verkauft ihr Fahrrad an einen Kollegen."),),
    "verlangen": (("nach", "Dat", "渴望，需要", "Die Pflanze verlangt nach Wasser."), ("von", "Dat", "向…要求", "Ich verlange von dir eine Antwort.")),
    "verlassen": (("auf", "Akk", "(sich)信赖", "Du kannst dich auf mich verlassen."),),
    "verliebt": (("in", "Akk", "爱上；迷恋", "Sie ist in ihn verliebt."),),
    "verlängern": (("um", "Akk", "延长了", "Wir verlängern die Frist um eine Woche."),),
    "vermieten": (("an", "Akk", "出租给", "Sie vermietet das Zimmer an einen Studenten."),),
    "verpflichtet": (("zu", "Dat", "有义务做", "Er ist zu diesem Schritt verpflichtet."),),
    "verrückt": (("nach", "Dat", "迷恋；热衷", "Er ist verrückt nach Fußball."),),
    "verschieben": (("auf", "Akk", "推迟到", "Wir verschieben das Treffen auf morgen."),),
    "verschieden": (("von", "Dat", "与…不同", "Er ist ganz verschieden von seinem Bruder."),),
    "verschreiben": (("gegen", "Akk", "开药治疗", "Der Arzt verschreibt ein Medikament gegen die Krankheit."),),
    "verseucht": (("mit", "Dat", "被…污染", "Der Boden ist mit Chemikalien verseucht."),),
    "versichern": (("gegen", "Akk", "(sich)投保防", "Er versichert sich gegen Diebstahl."),),
    "versprechen": (("von", "Dat", "(sich)期望从", "Ich verspreche mir viel von diesem Kurs."),),
    "verstehen": (("von", "Dat", "懂，了解", "Sie versteht viel von Kunst."), ("auf", "Akk", "(sich)精通", "Er versteht sich auf alte Autos."), ("mit", "Dat", "(sich)合得来", "Sie versteht sich gut mit ihren Kollegen.")),
    "verständigen": (("über", "Akk", "通知关于", "Der Arzt verständigte die Angehörigen über den Zustand."), ("mit", "Dat", "(sich)沟通", "Er verständigt sich gut mit seinen Kollegen."), ("auf", "Akk", "(sich)达成一致", "Die Parteien verständigten sich auf einen Kompromiss.")),
    "verständlich": (("für", "Akk", "对…易懂", "Der Text ist für Kinder verständlich."),),
    "versuchen": (("mit", "Dat", "尝试用", "Er versuchte es mit einem anderen Schlüssel."),),
    "vertrauen": (("auf", "Akk", "信任，信赖", "Ich vertraue auf deine Hilfe."),),
    "verträglich": (("mit", "Dat", "与…相容", "Das neue System ist mit dem alten System verträglich."),),
    "verurteilen": (("zu", "Dat", "判处", "Der Richter verurteilt ihn zu einer Geldstrafe."),),
    "verwandt": (("mit", "Dat", "与…有亲属关系", "Sie ist mit meiner Schwester verwandt."),),
    "verwechseln": (("mit", "Dat", "把…和…混淆", "Er verwechselt die Schlüssel mit seinen eigenen."),),
    "verwenden": (("für", "Akk", "把…用于", "Ich verwende dieses Werkzeug für die Reparatur."),),
    "verwundbar": (("gegenüber", "Dat", "对…脆弱", "Er ist sehr verwundbar gegenüber Kritik."),),
    "verzichten": (("auf", "Akk", "放弃", "Wir verzichten auf den Urlaub."),),
    "verzweifeln": (("an", "Dat", "对…绝望", "Sie verzweifelt an ihrer Aufgabe."),),
    "vorbereiten": (("auf", "Akk", "(sich)为…做准备", "Ich bereite mich auf die Prüfung vor."),),
    "vorsichtig": (("mit", "Dat", "小心对待", "Er ist vorsichtig mit dem Gerät."),),
    "wachsen": (("an", "Dat", "因…成长", "Er wächst an seinen Aufgaben."), ("zu", "Dat", "成长为", "Sie wächst zu einer starken Frau.")),
    "warnen": (("vor", "Dat", "警告提防", "Er warnt vor den Gefahren."),),
    "warten": (("auf", "Akk", "等待", "Ich warte auf den Bus."),),
    "weinen": (("um", "Akk", "为…而哭", "Sie weint um ihren Vater."), ("über", "Akk", "因…而哭", "Er weint über den Verlust.")),
    "weiterleiten": (("an", "Akk", "转发给", "Er leitet die E-Mail an seinen Chef weiter."),),
    "wenden": (("an", "Akk", "(sich)向…求助", "Sie wendet sich an den Kundenservice."), ("gegen", "Akk", "(sich)反对", "Er wendet sich gegen die Entscheidung.")),
    "westlich": (("von", "Dat", "在…以西", "Die Stadt liegt westlich von Berlin."),),
    "wetten": (("auf", "Akk", "打赌", "Ich wette auf den Sieg."),),
    "wichtig": (("für", "Akk", "对…重要", "Das ist wichtig für mich."),),
    "wild": (("auf", "Akk", "热衷于", "Er ist wild auf Schokolade."),),
    "wirken": (("auf", "Akk", "影响", "Das Medikament wirkt auf das Herz."), ("gegen", "Akk", "有效", "Das Mittel wirkt gegen Kopfschmerzen.")),
    "wissen": (("von", "Dat", "知道", "Ich weiß von nichts."), ("um", "Akk", "意识到", "Er weiß um die Gefahr.")),
    "wütend": (("auf", "Akk", "对某人生气", "Ich bin wütend auf meinen Bruder."), ("über", "Akk", "因某事生气", "Sie ist wütend über das Ergebnis.")),
    "zahlen": (("für", "Akk", "支付", "Er zahlt für das Essen."),),
    "zeichnen": (("für", "Akk", "负责，签名", "Er zeichnet für die Qualität der Produkte."),),
    "zeigen": (("auf", "Akk", "指向", "Sie zeigt auf das Bild an der Wand."),),
    "zentral": (("für", "Akk", "对…关键", "Diese Frage ist zentral für das Projekt."),),
    "ziehen": (("an", "Dat", "拉，拽", "Er zieht an der Tür."),),
    "zufrieden": (("mit", "Dat", "满意", "Ich bin mit dem Ergebnis zufrieden."),),
    "zugehen": (("auf", "Akk", "走向，靠近", "Er geht auf den Mann zu."),),
    "zugänglich": (("für", "Akk", "对…开放", "Der Park ist für die Öffentlichkeit zugänglich."),),
    "zunehmen": (("an", "Dat", "在...方面增加", "Er nimmt an Gewicht zu."),),
    "zurechtkommen": (("mit", "Dat", "处理好，应付", "Ich komme mit dem Problem zurecht."),),
    "zurückbleiben": (("hinter", "Dat", "落后于", "Er bleibt hinter den Erwartungen zurück."),),
    "zurückgehen": (("auf", "Akk", "追溯到", "Diese Regel geht auf das 19. Jahrhundert zurück."),),
    "zurückgeht": (("auf", "Akk", "追溯到", "Das Problem geht auf ihn zurück."),),
    "zurückkommen": (("auf", "Akk", "回到（话题）", "Kommen wir auf das Thema zurück."),),
    "zusammenstossen": (("mit", "Dat", "与...相撞", "Das Auto stieß mit einem Baum zusammen."),),
    "zuständig": (("für", "Akk", "负责", "Er ist zuständig für die Buchhaltung."),),
    "zusätzlich": (("zu", "Dat", "除...之外", "Zusätzlich zu seinem Lohn bekommt er einen Bonus."),),
    "zweifeln": (("an", "Dat", "怀疑", "Er zweifelt an seiner Entscheidung."),),
    "zählen": (("auf", "Akk", "指望，依靠", "Wir zählen auf Ihre Unterstützung."), ("zu", "Dat", "属于", "Sie zählt zu den besten Künstlern.")),
    "ändern": (("an", "Dat", "改变，改动", "Sie konnte an der Situation nichts ändern."),),
    "ärgerlich": (("über", "Akk", "对…生气", "Er ist ärgerlich über das Ergebnis."),),
    "ärgern": (("über", "Akk", "(sich)为…生气", "Er ärgert sich über den Fehler."),),
    "äußerte": (("zu", "Dat", "(sich)发表意见", "Er äußerte sich zu dem Vorschlag."),),
    "überlegen": (("an", "Dat", "在…方面占优势", "Er ist seinem Gegner an Erfahrung überlegen."),),
    "überprüfen": (("auf", "Akk", "检查…是否有…", "Man überprüfte die Ware auf Schäden."),),
    "überraschen": (("mit", "Dat", "以…使惊讶", "Sie überraschte ihre Mutter mit Blumen."),),
    "überreden": (("zu", "Dat", "说服做…", "Er überredete sie zu einem Umzug."),),
    "übersetzen": (("aus", "Dat", "从…翻译", "Sie übersetzt den Artikel aus dem Englischen."),),
    "übertragen": (("auf", "Akk", "传染/转移给", "Das Virus wird auf den Menschen übertragen."),),
    "überweisen": (("auf", "Akk", "转账到（账户）", "Ich überweise das Geld auf dein Konto."), ("an", "Akk", "汇给", "Wir überweisen den Betrag an die Firma.")),
    "überwältigt": (("von", "Dat", "被…所压倒/折服", "Die Zuschauer waren von der Musik überwältigt."),),
    "überzeugen": (("von", "Dat", "使相信", "Er konnte mich von seiner Unschuld überzeugen."),),
    "überzeugt": (("von", "Dat", "确信", "Er ist von seiner Idee überzeugt."),),
    "überzogen": (("mit", "Dat", "覆盖着…", "Der Draht ist mit Kunststoff überzogen."),),
    "übrig": (("für", "Akk", "对…有好感", "Ich habe für dieses Lied etwas übrig."),),
}
