# -*- coding: utf-8 -*-
"""AI 批量生成的德语动词/形容词固定介词搭配表（auto-generated）。

Schema: lemma -> ((介词, 格, 中文义, 例句), ...)
值是**元组的元组**：一个词头可带多个介词且意思不同
（bestehen auf 坚持 / aus 由…组成 / in 在于），单值会丢义项。

键全小写、反身动词不带 sich（freuen 而非 sich freuen），
以便直接匹配 spaCy 的 lemma 输出。
手动改会丢：必考搭配请改 tools/build_prep.py 的 SEED_COLLOCATIONS，
长尾靠 AI 生成，两者由 tools/build_prep.py 合并（seed 优先）。
"""

PREP_COLLOCATIONS = {  # 552 词条 / 691 条搭配 · 已问过 1773 词 · seed 47 词 + AI 长尾
    "abgeben": (("mit", "Dat", "与…打交道(sich)", "Er gibt sich mit zwielichtigen Leuten ab."),),
    "abheben": (("auf", "Akk", "着眼于，针对", "Der Vorwurf hebt auf die Finanzierung ab."), ("von", "Dat", "与…区别(sich)", "Das Muster hebt sich von der Wand ab.")),
    "abhängen": (("von", "Dat", "取决于，依靠", "Das hängt von der Witterung ab."),),
    "abhängig": (("von", "Dat", "依赖于", "Der Erfolg ist von vielen Faktoren abhängig."),),
    "ablenken": (("von", "Dat", "使…从…分心", "Der Lärm lenkt von der Arbeit ab."),),
    "abnehmen": (("an", "Dat", "在…方面减少", "Die Stadt nimmt an Einwohnern ab."),),
    "abrechnen": (("mit", "Dat", "与…结算，算账", "Die Firma rechnet mit einem alten Partner ab."),),
    "abschließen": (("mit", "Dat", "以…结束，与…签订", "Die Veranstaltung schließt mit einem Konzert ab."),),
    "abstimmen": (("auf", "Akk", "使协调，调整", "Wir stimmen das Programm auf die Zielgruppe ab."), ("über", "Akk", "表决", "Das Parlament stimmt über den Gesetzentwurf ab.")),
    "abtreten": (("von", "Dat", "退去，退出", "Der Minister tritt von seinem Amt ab."), ("an", "Akk", "转让给", "Er tritt die Firma an seinen Sohn ab.")),
    "abweichen": (("von", "Dat", "偏离", "Die Meinung weicht von der Norm ab."),),
    "abwenden": (("von", "Dat", "(sich)背离", "Sie wendet sich von der Vergangenheit ab."),),
    "achten": (("auf", "Akk", "注意", "Bitte achten Sie auf die Verkehrszeichen."),),
    "alternativ": (("zu", "Dat", "替代，可供选择", "Dieser Plan ist alternativ zu dem alten."),),
    "anfangen": (("mit", "Dat", "开始做", "Wir fangen mit der Übung an."),),
    "anfällig": (("für", "Akk", "容易患…", "Er ist anfällig für Grippe."),),
    "angeben": (("mit", "Dat", "吹嘘、炫耀", "Peter gibt mit seinem Erfolg an."),),
    "angerechnet": (("auf", "Akk", "计入、抵扣", "Er hat die Anzahlung auf den Kaufpreis angerechnet."),),
    "anhaben": (("gegen", "Akk", "对…有办法", "Man kann nichts gegen diese Krankheit anhaben."),),
    "animieren": (("zu", "Dat", "鼓励、促使", "Der Film animiert die Zuschauer zum Nachdenken."),),
    "ankommen": (("auf", "Akk", "取决于", "Es kommt auf deine Entscheidung an."),),
    "anlegen": (("in", "Akk", "投资于", "Sie legt ihr Geld in Aktien an."), ("mit", "Dat", "(sich)与…争吵", "Er legt sich oft mit Kollegen an.")),
    "anmelden": (("für", "Akk", "报名参加", "Ich melde mich für den Kurs an."), ("zu", "Dat", "报名参加", "Er meldet sich zu einem Seminar an.")),
    "anschließen": (("an", "Akk", "(sich)加入", "Wir schließen uns an die Gruppe an."),),
    "ansprechen": (("auf", "Akk", "谈及", "Ich spreche ihn auf den Termin an."),),
    "antworten": (("auf", "Akk", "回答", "Er antwortet auf die Frage."),),
    "anwenden": (("auf", "Akk", "应用于", "Man wendet die Regel auf den Fall an."),),
    "arbeiten": (("an", "Dat", "从事；致力于", "Er arbeitet an einem neuen Roman."), ("für", "Akk", "为…工作", "Sie arbeitet für eine große Firma."), ("bei", "Dat", "在…任职", "Ich arbeite bei Siemens."), ("mit", "Dat", "与…合作", "Er arbeitet mit einem Kollegen.")),
    "arm": (("an", "Dat", "缺乏；贫乏", "Die Region ist arm an Wasser."),),
    "auffallen": (("durch", "Akk", "因…惹人注目", "Er fällt durch sein lautes Lachen auf."),),
    "auffordern": (("zu", "Dat", "要求；促使", "Der Lehrer fordert die Schüler zur Ruhe auf."),),
    "aufgeschlossen": (("für", "Akk", "对…持开放态度", "Sie ist für neue Ideen aufgeschlossen."), ("gegenüber", "Dat", "对…开放", "Er ist gegenüber Kritik aufgeschlossen.")),
    "aufhalten": (("mit", "Dat", "(sich) 忙于", "Ich halte mich nicht mit Nebensächlichkeiten auf."),),
    "aufhören": (("mit", "Dat", "停止做", "Er hört mit dem Rauchen auf."),),
    "aufmerksam": (("auf", "Akk", "对…注意", "Sie ist aufmerksam auf die Gefahr."),),
    "aufnehmen": (("in", "Akk", "接收；接纳", "Die Universität nimmt neue Studenten in den Kurs auf."),),
    "aufpassen": (("auf", "Akk", "照看；注意", "Die Mutter passt auf das Kind auf."),),
    "aufregen": (("über", "Akk", "(sich) 对…恼火", "Er regt sich über den Lärm auf."),),
    "aufrufen": (("zu", "Dat", "呼吁，号召", "Der Chef ruft zur Vorsicht auf."),),
    "aufräumen": (("mit", "Dat", "清除，破除", "Er will mit Vorurteilen aufräumen."),),
    "aufstehen": (("gegen", "Akk", "起来反抗", "Wir stehen gegen Unrecht auf."),),
    "auftreten": (("gegen", "Akk", "对付，反抗", "Die Opposition tritt gegen die Regierung auf."), ("für", "Akk", "为…出头，代言", "Sie tritt für ihre Kollegen auf.")),
    "aus-sein": (("auf", "Akk", "追求，目的在于", "Er ist auf Rache aus."),),
    "ausarten": (("in", "Akk", "演变成，恶化成", "Die Diskussion artete in einen Streit aus."),),
    "ausgeben": (("für", "Akk", "花费在…上", "Sie gibt viel Geld für Reisen aus."), ("für", "Akk", "(sich) 冒充", "Er gibt sich für einen Arzt aus.")),
    "ausgebildet": (("zu", "Dat", "受训成为", "Er wurde zum Ingenieur ausgebildet."),),
    "ausgegrenzt": (("aus", "Dat", "被排斥出", "Er wurde aus der Gruppe ausgegrenzt."),),
    "ausgehen": (("von", "Dat", "以…为出发点", "Die Theorie geht von dieser Annahme aus."),),
    "ausgelagert": (("an", "Akk", "外包给", "Die Produktion wurde an ein anderes Unternehmen ausgelagert."),),
    "ausgelastet": (("mit", "Dat", "忙于", "Der Mitarbeiter ist mit Aufgaben ausgelastet."),),
    "ausgezeichnet": (("mit", "Dat", "被授予", "Sie wurde mit dem Preis ausgezeichnet."),),
    "ausreichen": (("für", "Akk", "足够用于", "Das Geld reicht für die Reise aus."),),
    "ausreichend": (("für", "Akk", "足够用于", "Das Essen ist für drei Personen ausreichend."),),
    "ausrichten": (("auf", "Akk", "(sich) 以…为目标", "Das Projekt richtet sich auf die Bedürfnisse der Kunden aus."),),
    "aussagen": (("über", "Akk", "对…作证", "Er sagte über den Unfall aus."), ("gegen", "Akk", "作证指控", "Sie sagte gegen den Angeklagten aus.")),
    "ausschließen": (("von", "Dat", "被排除在…外", "Er wurde von der Versammlung ausgeschlossen."),),
    "aussehen": (("nach", "Dat", "看起来像", "Das sieht nach Regen aus."),),
    "aussprechen": (("für", "Akk", "(sich) 支持", "Er sprach sich für den Plan aus."), ("gegen", "Akk", "(sich) 反对", "Sie sprach sich gegen die Entscheidung aus.")),
    "aussteigen": (("aus", "Dat", "从…下来", "Sie stieg aus dem Bus aus."),),
    "ausstellen": (("auf", "Akk", "开出（支票）给", "Er stellt einen Scheck auf ihren Namen aus."),),
    "austauschen": (("gegen", "Akk", "换成", "Er tauscht das alte Handy gegen ein neues aus."), ("mit", "Dat", "(sich)与…交流", "Er tauscht sich mit einem Kollegen aus.")),
    "austragen": (("aus", "Dat", "从…中注销", "Sie trägt ihren Namen aus der Liste aus."),),
    "ausweichen": (("auf", "Akk", "改而采用", "Wir weichen auf einen anderen Plan aus."),),
    "auswählen": (("aus", "Dat", "从…中选出", "Er wählt einen Kandidaten aus einer Liste aus."),),
    "ausziehen": (("aus", "Dat", "搬出（住所）", "Die Familie zieht aus der alten Wohnung aus."),),
    "basieren": (("auf", "Dat", "基于", "Seine Theorie basiert auf vielen Fakten."),),
    "basteln": (("an", "Dat", "忙于制作", "Er bastelt an einem Holzschiff."),),
    "bauen": (("auf", "Akk", "依靠", "Wir bauen auf deine Hilfe."), ("an", "Dat", "忙于建造", "Sie bauen an einem neuen Haus.")),
    "beantragen": (("bei", "Dat", "向…申请", "Er beantragt einen neuen Pass bei der Behörde."),),
    "beantworten": (("mit", "Dat", "用…回答", "Sie beantwortet die Frage mit einem Lächeln."),),
    "beauftragen": (("mit", "Dat", "委托…做", "Der Chef beauftragt einen Mitarbeiter mit der Aufgabe."),),
    "bedenken": (("mit", "Dat", "以…馈赠", "Sie bedenkt ihren Freund mit einem Geschenk."),),
    "bedeutsam": (("für", "Akk", "对…意义重大", "Diese Entdeckung ist bedeutsam für die Forschung."),),
    "befangen": (("in", "Dat", "陷于，拘泥于", "Er ist in seinen eigenen Gedanken befangen."),),
    "befassen": (("mit", "Dat", "(sich) 处理，研究", "Sie befasst sich mit moderner Literatur."),),
    "befreit": (("von", "Dat", "摆脱…的", "Endlich ist er von allen Sorgen befreit."),),
    "befähigen": (("zu", "Dat", "使能，使有能力", "Die Erfahrung befähigt ihn zu dieser Aufgabe."),),
    "begeistert": (("von", "Dat", "对…兴奋，着迷", "Ich bin von der neuen Ausstellung begeistert."), ("für", "Akk", "热衷于，支持", "Er ist für Fußball begeistert.")),
    "beginnen": (("mit", "Dat", "以…开始", "Der Kurs beginnt mit einer Einführung."),),
    "begrenzt": (("auf", "Akk", "限于，限制在", "Die Redezeit ist auf fünf Minuten begrenzt."),),
    "begründen": (("mit", "Dat", "以…为由，论证", "Er begründet seinen Vorschlag mit aktuellen Daten."),),
    "beharren": (("auf", "Dat", "坚持", "Sie beharrt auf ihrer Forderung."),),
    "beitragen": (("zu", "Dat", "有助于，促成", "Jeder kann zum Umweltschutz beitragen."),),
    "bekannt": (("für", "Akk", "因…闻名", "Die Stadt ist für ihre Architektur bekannt."),),
    "beliebt": (("bei", "Dat", "受欢迎", "Er ist bei seinen Kollegen beliebt."),),
    "bemängeln": (("an", "Dat", "挑剔，批评", "Sie bemängelt an dem Plan die Kosten."),),
    "beraten": (("über", "Akk", "商议，协商", "Wir beraten über die neue Strategie."),),
    "berechtigt": (("zu", "Dat", "有权，有资格", "Nur der Chef ist zu dieser Entscheidung berechtigt."),),
    "bereit": (("zu", "Dat", "愿意", "Er ist zu einem Kompromiss bereit."),),
    "berichten": (("über", "Akk", "报道，讲述", "Der Journalist berichtet über den Unfall."),),
    "berichteten": (("über", "Akk", "报道，讲述", "Sie berichteten über den Vorfall."),),
    "berühmt": (("für", "Akk", "因…而著名", "Er ist berühmt für seine Arbeit."), ("wegen", "Gen", "由于…闻名", "Sie ist berühmt wegen ihres Talents.")),
    "beschränken": (("auf", "Akk", "(sich)限于", "Er beschränkt sich auf das Nötigste."),),
    "beschäftigen": (("mit", "Dat", "(sich)从事/研究", "Ich beschäftige mich mit deutscher Literatur."),),
    "besprechen": (("mit", "Dat", "和…商谈", "Er bespricht das Problem mit seinem Kollegen."),),
    "bestehen": (("auf", "Dat", "坚持", "Er besteht auf seiner Meinung."), ("aus", "Dat", "由…组成", "Das Team besteht aus fünf Personen."), ("in", "Dat", "在于", "Die Aufgabe besteht in der Analyse der Daten.")),
    "bestehend": (("aus", "Dat", "由…组成", "Die aus Holz bestehende Brücke ist alt."),),
    "bestellen": (("bei", "Dat", "向…订购", "Ich bestelle die Bücher bei einem Online-Shop."),),
    "besticht": (("durch", "Akk", "以…吸引人", "Sie besticht durch ihre Ausstrahlung."),),
    "bestimmt": (("für", "Akk", "为…预定", "Dieses Geschenk ist für dich bestimmt."),),
    "bestrafen": (("für", "Akk", "因…惩罚", "Sie bestrafen ihn für seinen Fehler."), ("mit", "Dat", "用…惩罚", "Das Gericht bestraft den Dieb mit einer Geldstrafe.")),
    "bestätigen": (("in", "Dat", "使确信", "Diese Nachricht bestätigt mich in meiner Annahme."),),
    "beteiligen": (("an", "Dat", "(sich)参与", "Er beteiligt sich an der Diskussion."),),
    "beten": (("zu", "Dat", "向…祈祷", "Wir beten zu Gott."), ("für", "Akk", "为…祈祷", "Sie betet für ihre Familie.")),
    "betrachten": (("als", "Akk", "把…看作", "Wir betrachten ihn als unseren Freund."),),
    "betrunken": (("von", "Dat", "因…醉酒的", "Er war betrunken von dem vielen Bier."),),
    "betrügen": (("um", "Akk", "骗取某物", "Er betrog sie um ihr ganzes Vermögen."),),
    "beugen": (("vor", "Dat", "(sich) 屈服于", "Er beugte sich vor dem König."),),
    "beurteilen": (("nach", "Dat", "根据…评价", "Man beurteilt einen Menschen nicht nur nach seiner Kleidung."),),
    "beurteilt": (("nach", "Dat", "依据…评判", "Die Situation wurde nach verschiedenen Kriterien beurteilt."),),
    "bewegen": (("zu", "Dat", "促使", "Er bewegte ihn zum Aufgeben."),),
    "bewerben": (("um", "Akk", "(sich)申请职位", "Er bewirbt sich um die Stelle."), ("bei", "Dat", "(sich)向…求职", "Sie bewirbt sich bei einer Bank.")),
    "bezahlen": (("für", "Akk", "支付", "Ich bezahle für das Essen."),),
    "bieten": (("auf", "Akk", "出价", "Er bietet 100 Euro auf die Vase."),),
    "bitten": (("um", "Akk", "请求", "Er bittet mich um Hilfe."),),
    "blind": (("für", "Akk", "对…盲目", "Er ist blind für seine Fehler."),),
    "brechen": (("mit", "Dat", "与…决裂", "Er bricht mit der Tradition."),),
    "brennen": (("für", "Akk", "热衷", "Er brennt für seine Idee."), ("auf", "Akk", "渴望", "Ich brenne auf das Konzert.")),
    "bringen": (("auf", "Akk", "使想起", "Das bringt mich auf eine Idee."), ("um", "Akk", "使失去", "Sie brachte ihn um sein Geld."), ("zu", "Dat", "导致", "Das brachte ihn zu Fall.")),
    "böse": (("auf", "Akk", "生气", "Sie ist böse auf ihn."),),
    "chatten": (("mit", "Dat", "与…聊天", "Ich chatte mit meinem Freund."), ("über", "Akk", "聊到", "Wir chatten über das Wetter.")),
    "dankbar": (("für", "Akk", "感激", "Ich bin dir für deine Hilfe dankbar."),),
    "danken": (("für", "Akk", "感谢", "Ich danke dir für deine Unterstützung."),),
    "darstellen": (("als", "Akk", "描述为", "Er stellt sie als Heldin dar."),),
    "definieren": (("als", "Akk", "定义为", "Er definiert den Begriff als Freiheit."),),
    "dekorieren": (("mit", "Dat", "用…装饰", "Wir dekorieren den Raum mit Blumen."),),
    "denken": (("an", "Akk", "想到", "Ich denke oft an meine Familie."),),
    "dicht": (("an", "Dat", "紧挨", "Das Haus ist dicht an der Straße."),),
    "dienen": (("zu", "Dat", "用于", "Dieser Raum dient zur Lagerung."),),
    "differenzieren": (("zwischen", "Dat", "区分", "Man muss zwischen Ursache und Wirkung differenzieren."),),
    "diskutieren": (("über", "Akk", "讨论", "Wir diskutieren über die Lösung."), ("mit", "Dat", "与…讨论", "Er diskutiert mit seinem Kollegen.")),
    "dotieren": (("mit", "Dat", "以…作为报酬", "Die Stelle ist mit 5000 Euro dotiert."),),
    "drehen": (("an", "Dat", "拧动", "Er dreht am Lautstärkeregler."), ("um", "Akk", "(sich) 围绕", "Das Buch dreht sich um Liebe.")),
    "drücken": (("auf", "Akk", "按压", "Bitte drücken Sie auf den Knopf."), ("vor", "Dat", "(sich) 逃避", "Er drückt sich vor der Arbeit.")),
    "durchsetzt": (("mit", "Dat", "夹杂着", "Die Suppe ist durchsetzt mit Gemüse."),),
    "durstig": (("nach", "Dat", "渴望", "Er ist durstig nach Wissen."),),
    "ebnen": (("für", "Akk", "为…铺平道路", "Das Gesetz ebnet den Weg für die Reform."),),
    "egal": (("für", "Akk", "对…无所谓", "Das ist egal für mich."),),
    "ehrlich": (("mit", "Dat", "对…诚实", "Er ist ehrlich mit seinen Freunden."), ("zu", "Dat", "对…诚实", "Sei ehrlich zu mir.")),
    "eilen": (("mit", "Dat", "紧迫", "Es eilt mit der Entscheidung."),),
    "eilig": (("mit", "Dat", "急于", "Sie hat es eilig mit der Abreise."),),
    "einbinden": (("in", "Akk", "把…融入", "Die neuen Mitarbeiter werden in das Team eingebunden."),),
    "einbrechen": (("in", "Akk", "闯入", "Einbrecher brachen in das Haus ein."),),
    "einfallen": (("in", "Akk", "入侵，侵入", "Die Truppen fielen in das Land ein."),),
    "einfügen": (("in", "Akk", "插入", "Fügen Sie das Bild in den Text ein."), ("in", "Akk", "(sich)融入", "Sie fügt sich gut in die Gruppe ein.")),
    "einführen": (("in", "Akk", "引入，引进", "Er führte die neue Methode in den Betrieb ein."),),
    "einladen": (("zu", "Dat", "邀请参加", "Ich lade dich zu meiner Party ein."),),
    "einnehmen": (("für", "Akk", "赢得…支持", "Er nahm die Zuhörer für seinen Vorschlag ein."),),
    "einordnen": (("in", "Akk", "归入，整理", "Er ordnete die Dokumente in den Ordner ein."),),
    "einpacken": (("in", "Akk", "包入，包装", "Sie packt das Geschenk in buntes Papier ein."),),
    "einrichten": (("auf", "Akk", "(sich)为…做准备", "Wir richten uns auf lange Wartezeiten ein."),),
    "einschalten": (("in", "Akk", "介入 (sich)", "Er schaltet sich in die Diskussion ein."),),
    "einschreiben": (("in", "Akk", "报名 (sich)", "Ich schreibe mich in den Kurs ein."),),
    "einsetzen": (("für", "Akk", "为…奋斗 (sich)", "Er setzt sich für den Umweltschutz ein."), ("gegen", "Akk", "反对 (sich)", "Sie setzt sich gegen Gewalt ein.")),
    "einsteigen": (("in", "Akk", "进入，介入", "Er steigt in die Politik ein."),),
    "einstellen": (("auf", "Akk", "调整适应 (sich)", "Sie stellt sich auf die neue Lage ein."),),
    "eintragen": (("in", "Akk", "登记 (sich)", "Er trägt sich in die Anwesenheitsliste ein."),),
    "eintreten": (("für", "Akk", "支持", "Er tritt für die Rechte der Kinder ein."), ("in", "Akk", "加入", "Sie tritt in die Partei ein.")),
    "einverstanden": (("mit", "Dat", "同意", "Ich bin mit dem Plan einverstanden."),),
    "einverstanden-sein": (("mit", "Dat", "同意", "Er ist mit dem Ergebnis einverstanden."),),
    "einweihen": (("in", "Akk", "使知情", "Er weiht sie in den Plan ein."),),
    "einzahlen": (("auf", "Akk", "存入", "Ich zahle das Geld auf ein Konto ein."),),
    "einzuschleusen": (("in", "Akk", "偷运进", "Sie versucht, die Waffen in das Land einzuschleusen."),),
    "einzuschleussen": (("in", "Akk", "偷运进", "Er versucht, Spione in das Gebiet einzuschleussen."),),
    "empfänglich": (("für", "Akk", "易受…影响", "Er ist empfänglich für Musik."),),
    "empört": (("über", "Akk", "对…愤慨", "Sie ist empört über die Entscheidung."),),
    "entfernen": (("von", "Dat", "(sich)离开，远离", "Er entfernt sich von der Gruppe."),),
    "entrüstet": (("über", "Akk", "对…愤怒", "Die Fans sind entrüstet über die Absage."),),
    "entscheiden": (("über", "Akk", "决定，裁决", "Der Richter entscheidet über den Fall."), ("für", "Akk", "(sich)决定选择", "Ich entscheide mich für dieses Angebot."), ("gegen", "Akk", "(sich)决定反对", "Er entschied sich gegen den Plan."), ("zwischen", "Dat", "(sich)在…间取舍", "Sie muss sich zwischen zwei Optionen entscheiden.")),
    "entschlossen": (("zu", "Dat", "决心…的", "Er ist zu dem Schritt entschlossen."),),
    "entschuldigen": (("für", "Akk", "(sich)为…道歉", "Ich entschuldige mich für die Verspätung."), ("bei", "Dat", "(sich)向…道歉", "Er entschuldigt sich bei seinem Chef.")),
    "entstehen": (("aus", "Dat", "由…产生", "Aus der Idee entstand ein Buch."), ("durch", "Akk", "通过…产生", "Durch den Krieg entsteht Leid.")),
    "entwickeln": (("zu", "Dat", "(sich) 发展为", "Sie entwickelt sich zu einer starken Frau."), ("aus", "Dat", "(sich) 由…发展", "Aus einer Kleinigkeit entwickelt sich ein Streit.")),
    "erfahren": (("von", "Dat", "从…得知", "Ich habe von dem Unfall erfahren."), ("über", "Akk", "了解关于…", "Wir erfahren viel über das Land.")),
    "erforderlich": (("für", "Akk", "对…必需的", "Sorgfalt ist für diese Arbeit erforderlich."),),
    "erfüllen": (("mit", "Dat", "使充满…", "Die Nachricht erfüllt ihn mit Hoffnung."),),
    "ergänzen": (("um", "Akk", "补充…", "Wir ergänzen den Text um ein Kapitel."), ("durch", "Akk", "通过…补充", "Die Mannschaft ergänzt sich durch neue Spieler.")),
    "erhöhen": (("um", "Akk", "增加了", "Die Firma erhöht die Preise um 5 Prozent."), ("auf", "Akk", "提高到", "Wir erhöhen die Temperatur auf 20 Grad.")),
    "erinnern": (("an", "Akk", "(sich)记得", "Ich erinnere mich an den Tag."),),
    "erkennen": (("an", "Dat", "通过...认出", "Man erkennt ihn an seiner Stimme."),),
    "ermitteln": (("gegen", "Akk", "调查", "Die Polizei ermittelt gegen den Verdächtigen."),),
    "ermutige": (("zu", "Dat", "鼓励做某事", "Er ermutigt mich zu diesem Schritt."),),
    "ernähren": (("von", "Dat", "(sich)以...为食", "Das Tier ernährt sich von Pflanzen."),),
    "erschrecken": (("über", "Akk", "对…吃惊", "Sie erschrak über die laute Stimme."), ("vor", "Dat", "害怕…", "Er erschrickt vor Spinnen.")),
    "erschüttert": (("über", "Akk", "对…震惊", "Er war erschüttert über die Nachricht."),),
    "ersetzen": (("durch", "Akk", "用…代替", "Wir ersetzen das alte Gerät durch ein neues."),),
    "erwachsen": (("aus", "Dat", "由…产生", "Aus diesem Konflikt erwuchsen viele Probleme."),),
    "erziehen": (("zu", "Dat", "教育成…", "Sie erzieht ihr Kind zur Selbstständigkeit."),),
    "existenziell": (("für", "Akk", "对…至关重要", "Diese Frage ist existenziell für unsere Zukunft."),),
    "fair": (("zu", "Dat", "对…公平", "Er ist fair zu seinen Kollegen."),),
    "fassen": (("in", "Akk", "用…表达", "Er kann seine Gedanken nicht in Worte fassen."),),
    "fehlen": (("an", "Dat", "缺少，缺乏", "Es fehlt an qualifizierten Arbeitskräften."),),
    "feindselig": (("gegenüber", "Dat", "对…敌视", "Er ist feindselig gegenüber seinen Nachbarn."),),
    "feindselige": (("gegenüber", "Dat", "对…敌视", "Die feindselige Haltung gegenüber dem Plan ist unverständlich."),),
    "fertig": (("mit", "Dat", "完成，结束", "Ich bin mit der Arbeit fertig."), ("für", "Akk", "为…准备好", "Wir sind für den Notfall fertig.")),
    "fertig-sein": (("mit", "Dat", "完成，结束", "Er ist mit der Arbeit fertig."), ("für", "Akk", "为…准备好", "Sie sind für die Prüfung fertig.")),
    "festhalten": (("an", "Dat", "坚持", "Er hält an seiner Meinung fest."),),
    "festlegen": (("auf", "Akk", "(sich) 确定，选定", "Wir müssen uns auf einen Termin festlegen."),),
    "festsetzen": (("auf", "Akk", "把…定为", "Das Gericht setzte das Bußgeld auf 500 Euro fest."), ("in", "Dat", "(sich) 固定，留存", "Der Staub hat sich in den Ritzen festgesetzt.")),
    "fit-sein": (("für", "Akk", "为…做好准备", "Er ist fit für die Prüfung."),),
    "fliehen": (("vor", "Dat", "逃避，躲避", "Er flieht vor der Polizei."),),
    "folgen": (("auf", "Akk", "继…之后", "Auf den Sommer folgt der Herbst."), ("aus", "Dat", "由…得出", "Aus diesem Fehler folgen Konsequenzen.")),
    "fordern": (("von", "Dat", "向…要求", "Ich fordere das von dir."), ("zu", "Dat", "要求…做…", "Er fordert ihn zum Duell.")),
    "fragen": (("nach", "Dat", "询问，打听", "Er fragt nach dem Weg."),),
    "frech": (("zu", "Dat", "对…无礼", "Sei nicht frech zu deinen Eltern!"),),
    "freuen": (("auf", "Akk", "(sich)期待", "Ich freue mich auf die Ferien."), ("über", "Akk", "(sich)为…高兴", "Sie freut sich über das Geschenk.")),
    "freundlich": (("zu", "Dat", "对…友好", "Sie ist freundlich zu neuen Kollegen."),),
    "froh": (("über", "Akk", "为…高兴", "Ich bin froh über das Geschenk."),),
    "fähig": (("zu", "Dat", "有能力", "Er ist zu großen Leistungen fähig."),),
    "führen": (("zu", "Dat", "导致", "Stress kann zu Fehlern führen."),),
    "garantieren": (("für", "Akk", "为…担保", "Ich garantiere für seine Ehrlichkeit."),),
    "geeignet": (("für", "Akk", "适合", "Diese Software ist für Anfänger geeignet."), ("zu", "Dat", "适合", "Er ist zu dieser Aufgabe geeignet.")),
    "gefährlich": (("für", "Akk", "对…危险", "Rauchen ist gefährlich für die Gesundheit."),),
    "gegensteuern": (("gegen", "Akk", "对抗", "Wir müssen gegen den Trend gegensteuern."),),
    "gehen": (("um", "Akk", "涉及", "Es geht um eine wichtige Entscheidung."),),
    "gehören": (("zu", "Dat", "属于", "Dieses Buch gehört zu meiner Sammlung."),),
    "gelten": (("für", "Akk", "适用于", "Das gilt für alle Teilnehmer."),),
    "gescheiterten": (("an", "Dat", "在…上失败", "Er ist an dieser Aufgabe gescheitert."),),
    "gespannt": (("auf", "Akk", "期待", "Ich bin gespannt auf das Ergebnis."),),
    "gesperrt": (("für", "Akk", "对…关闭", "Die Straße ist für den Verkehr gesperrt."),),
    "getauft": (("auf", "Akk", "被命名为", "Das Kind ist auf den Namen Anna getauft."),),
    "gewinnen": (("an", "Dat", "在…上增长", "Das Projekt gewinnt an Bedeutung."),),
    "gewöhnen": (("an", "Akk", "(sich)习惯于", "Ich gewöhne mich an das Klima."),),
    "giftig": (("für", "Akk", "对…有毒", "Diese Pflanze ist giftig für Hunde."),),
    "glauben": (("an", "Akk", "相信", "Sie glaubt an den Erfolg."),),
    "glücklich": (("über", "Akk", "为…高兴", "Sie ist glücklich über das Geschenk."), ("mit", "Dat", "对…满意", "Er ist glücklich mit seinem Job.")),
    "gratulieren": (("zu", "Dat", "祝贺", "Wir gratulieren ihr zu ihrem Erfolg."),),
    "grausam": (("zu", "Dat", "对…残忍", "Er ist grausam zu seinen Tieren."),),
    "greifen": (("nach", "Dat", "伸手抓", "Er greift nach dem Glas."), ("zu", "Dat", "诉诸，采用", "Sie greift zu einer Lüge.")),
    "großzügig": (("mit", "Dat", "对…慷慨", "Sie ist großzügig mit ihrem Geld."),),
    "gründen": (("auf", "Dat", "基于", "Sein Erfolg gründet auf harter Arbeit."), ("in", "Dat", "源于", "Ihr Misstrauen gründet in schlechten Erfahrungen.")),
    "gut": (("für", "Akk", "对…有益", "Obst ist gut für die Gesundheit."), ("zu", "Dat", "对…友善", "Er ist gut zu seinen Kindern.")),
    "gültig": (("für", "Akk", "适用于", "Der Pass ist gültig für fünf Jahre."),),
    "gültig-sein": (("für", "Akk", "对…有效", "Das Ticket ist gültig für eine Woche."),),
    "günstig": (("für", "Akk", "有利于", "Das Wetter ist günstig für die Ernte."),),
    "halten": (("für", "Akk", "把…看作", "Ich halte ihn für einen guten Lehrer."), ("von", "Dat", "对…的看法", "Was halten Sie von diesem Plan?")),
    "handeln": (("von", "Dat", "讲述，关于", "Der Film handelt von einem Detektiv."), ("mit", "Dat", "经营", "Die Firma handelt mit Holz."), ("um", "Akk", "涉及 (sich)", "Es handelt sich um eine wichtige Frage.")),
    "hart": (("zu", "Dat", "对…严厉", "Sei nicht so hart zu dir selbst."),),
    "heizen": (("mit", "Dat", "用…取暖", "Wir heizen mit Gas."),),
    "heiß": (("auf", "Akk", "渴望", "Die Kinder sind heiß auf das neue Spielzeug."),),
    "heißen": (("auf", "Akk", "渴望", "Die Kinder sind heiß auf das neue Spielzeug."),),
    "helfen": (("bei", "Dat", "帮忙做", "Er hilft mir bei den Hausaufgaben."),),
    "herstellen": (("aus", "Dat", "由…制成", "Sie stellt die Figur aus Ton her."),),
    "hineinfuchsen": (("in", "Akk", "钻研(sich)", "Er fuchst sich in die Materie hinein."),),
    "hinweisen": (("auf", "Akk", "指出", "Er weist auf die Gefahr hin."),),
    "hinzugekommen": (("zu", "Dat", "加入", "Er ist zu den Gästen hinzugekommen."),),
    "hinzukommen": (("zu", "Dat", "加入", "Ein weiterer Punkt kommt zu den Problemen hinzu."),),
    "hoffen": (("auf", "Akk", "希望", "Wir hoffen auf besseres Wetter."),),
    "hängen": (("an", "Dat", "依恋", "Das Kind hängt sehr an seiner Mutter."),),
    "hören": (("auf", "Akk", "听从", "Du solltest auf deinen Vater hören."),),
    "ideal": (("für", "Akk", "适合", "Diese Wohnung ist ideal für eine Familie."),),
    "infizieren": (("mit", "Dat", "(sich)感染", "Er hat sich mit einem Virus infiziert."),),
    "informieren": (("über", "Akk", "通知；了解(sich)", "Er informiert sich über die Neuigkeiten."),),
    "integrieren": (("in", "Akk", "融入，整合", "Er integriert sich schnell in die Gruppe."),),
    "interagieren": (("mit", "Dat", "与…互动", "Die Schüler interagieren mit dem Lehrer."),),
    "interessant": (("für", "Akk", "对…有趣", "Das Buch ist interessant für Kinder."),),
    "interessieren": (("für", "Akk", "(sich)对…感兴趣", "Er interessiert sich für Politik."),),
    "interessiert": (("an", "Dat", "对…感兴趣", "Er ist an Kunst interessiert."),),
    "jammern": (("über", "Akk", "抱怨，哀叹", "Er jammert über das Wetter."),),
    "kapitulieren": (("vor", "Dat", "向…投降", "Die Armee kapitulierte vor dem Feind."),),
    "klagen": (("über", "Akk", "抱怨", "Er klagt über starke Kopfschmerzen."), ("gegen", "Akk", "起诉", "Sie klagt gegen die Firma."), ("auf", "Akk", "诉请", "Er klagt auf Schadensersatz.")),
    "klar": (("über", "Akk", "意识到", "Ich bin mir über die Risiken klar."),),
    "kleben": (("an", "Dat", "粘在", "Der Teig klebt an der Form."),),
    "klicken": (("auf", "Akk", "点击", "Bitte klicken Sie auf den Link."),),
    "klingen": (("nach", "Dat", "听起来像", "Das klingt nach einer guten Idee."),),
    "kommen": (("auf", "Akk", "想到，谈及", "Wie kommst du auf diese Idee?"), ("aus", "Dat", "来自", "Er kommt aus einer kleinen Stadt."), ("zu", "Dat", "得到，达到", "Er kommt zu Geld."), ("hinter", "Akk", "查明", "Wir kommen hinter die Wahrheit."), ("um", "Akk", "失去", "Er kommt um sein Vermögen.")),
    "kontrollieren": (("auf", "Akk", "检查有无", "Der Zoll kontrolliert den Koffer auf Drogen."),),
    "kramen": (("in", "Dat", "在…里翻找", "Er kramt in der Schublade."), ("nach", "Dat", "翻找某物", "Sie kramt nach ihrem Schlüssel.")),
    "kratzen": (("an", "Dat", "刮擦，抓挠", "Der Hund kratzt an der Tür."),),
    "kritisch": (("gegenüber", "Dat", "对…持批判态度", "Er ist kritisch gegenüber der Regierung."),),
    "kritisieren": (("an", "Dat", "批评某方面", "Was kritisierst du an dem Buch?"),),
    "kämpfen": (("für", "Akk", "为…而战", "Wir kämpfen für unsere Rechte."), ("gegen", "Akk", "对抗…", "Sie kämpfen gegen den Klimawandel."), ("um", "Akk", "争夺…", "Die Spieler kämpfen um den Sieg."), ("mit", "Dat", "与…斗争", "Er kämpfte mit einem starken Gegner.")),
    "kümmern": (("um", "Akk", "(sich)照顾", "Sie kümmert sich um die Kinder."),),
    "lachen": (("über", "Akk", "嘲笑", "Die Kinder lachen über den Clown."),),
    "leben": (("von", "Dat", "靠…生活", "Er lebt von seinem Gehalt."), ("für", "Akk", "为…而活", "Sie lebt für die Musik."), ("mit", "Dat", "与…生活", "Sie lebt mit ihrer Schwester.")),
    "leiden": (("an", "Dat", "患（病）", "Er leidet an einer Allergie."), ("unter", "Dat", "受…之苦", "Sie leidet unter dem Lärm.")),
    "liegen": (("an", "Dat", "由于，取决于", "Es liegt an dir, ob wir gewinnen."), ("in", "Dat", "在于", "Der Erfolg liegt in der Zusammenarbeit.")),
    "loben": (("für", "Akk", "因…表扬", "Der Lehrer lobt den Schüler für seine Arbeit."),),
    "lächeln": (("über", "Akk", "对…微笑", "Sie lächelt über seinen Witz."),),
    "melden": (("bei", "Dat", "(sich) 报到", "Er meldet sich bei seinem Chef."), ("für", "Akk", "(sich) 报名", "Sie meldet sich für den Kurs an.")),
    "messen": (("mit", "Dat", "(sich)与…较量", "Er misst sich mit dem Meister."),),
    "mischen": (("mit", "Dat", "与…混合", "Sie mischt Wasser mit Wein."), ("in", "Akk", "(sich)插手", "Er mischt sich in meine Angelegenheiten.")),
    "mitgerissen": (("von", "Dat", "被…吸引", "Sie war von der Musik mitgerissen."),),
    "mithalten": (("mit", "Dat", "与…匹敌", "Er kann mit den Besten mithalten."),),
    "mitmachen": (("bei", "Dat", "参加", "Er macht bei dem Spiel mit."),),
    "mitspielen": (("bei", "Dat", "参与", "Sie spielt bei dem Konzert mit."),),
    "mitverdienen": (("an", "Dat", "从…获利", "Sie verdient an dem Projekt mit."),),
    "nachdenken": (("über", "Akk", "思考", "Er denkt über das Problem nach."),),
    "neidisch": (("auf", "Akk", "嫉妒", "Er ist neidisch auf seinen Bruder."),),
    "nett": (("zu", "Dat", "对...友好", "Sei nett zu mir!"),),
    "neugierig": (("auf", "Akk", "好奇", "Ich bin neugierig auf das Ergebnis."),),
    "notwendig": (("für", "Akk", "对...必要", "Wasser ist notwendig für das Leben."),),
    "nördlich": (("von", "Dat", "在...以北", "Nördlich von Berlin liegt eine große Stadt."),),
    "nötig": (("für", "Akk", "对...必要", "Genug Schlaf ist nötig für die Gesundheit."),),
    "nützlich": (("für", "Akk", "对...有用", "Dieses Buch ist nützlich für Anfänger."),),
    "offen": (("für", "Akk", "对...开放", "Ich bin offen für neue Ideen."),),
    "operieren": (("an", "Dat", "对...手术", "Die Ärzte operieren am Herzen des Patienten."),),
    "parallel": (("zu", "Dat", "与…平行", "Die Straße verläuft parallel zu dem Fluss."),),
    "passen": (("zu", "Dat", "适合，与…相配", "Der Schlüssel passt zu diesem Schloss."),),
    "plaudern": (("mit", "Dat", "与…闲聊", "Ich plaudere gern mit meinen Kollegen."), ("über", "Akk", "闲聊关于…", "Wir plaudern über den Urlaub.")),
    "plädieren": (("für", "Akk", "主张，为…辩护", "Der Anwalt plädiert für seinen Mandanten."), ("gegen", "Akk", "反对…", "Die Partei plädiert gegen Steuererhöhungen.")),
    "populär": (("bei", "Dat", "在…中受欢迎", "Der Sänger ist bei Jugendlichen populär."),),
    "profilieren": (("durch", "Akk", "(sich)以…出众", "Er profiliert sich durch seine Leistungen."),),
    "protestieren": (("gegen", "Akk", "抗议，反对", "Sie protestierten gegen die Entscheidung."),),
    "prüfen": (("auf", "Akk", "检查有无…", "Der Arzt prüft den Patienten auf Allergien."),),
    "putschen": (("gegen", "Akk", "政变反对…", "Die Offiziere putschten gegen den Präsidenten."),),
    "raten": (("zu", "Dat", "建议，劝告", "Ich rate dir zu diesem Kurs."),),
    "ratseln": (("an", "Dat", "对…感到困惑", "Wir rätseln an dieser Aufgabe."), ("über", "Akk", "对…猜想/迷惑", "Sie rätseln über die Lösung.")),
    "reagieren": (("auf", "Akk", "对…作出反应", "Er reagiert auf die Nachricht."),),
    "rechnen": (("mit", "Dat", "预计", "Wir rechnen mit Regen."),),
    "recht-haben": (("mit", "Dat", "在…方面是对的", "Du hast recht mit dieser Idee."),),
    "rechtfertigen": (("mit", "Dat", "用…辩解", "Er rechtfertigt sein Verhalten mit Stress."), ("gegenüber", "Dat", "向…辩解", "Er rechtfertigt sein Handeln gegenüber seinem Chef.")),
    "reden": (("über", "Akk", "谈论", "Wir reden über die Politik."), ("von", "Dat", "谈到", "Sie redet von ihrem Urlaub."), ("mit", "Dat", "与…交谈", "Ich rede mit meinem Freund."), ("zu", "Dat", "对…说话", "Der Präsident redet zu dem Volk.")),
    "reduzieren": (("auf", "Akk", "减少到", "Die Kosten wurden auf 100 Euro reduziert."), ("um", "Akk", "减少了", "Wir reduzieren die Ausgaben um 10%.")),
    "referieren": (("über", "Akk", "就…作报告", "Er referiert über die neue Studie."),),
    "reflektieren": (("über", "Akk", "反思", "Sie reflektiert über ihre Erfahrungen."),),
    "reichen": (("für", "Akk", "足够用于", "Das Geld reicht für die Miete."),),
    "reif": (("für", "Akk", "适宜于", "Die Situation ist reif für eine Veränderung."),),
    "reizen": (("an", "Dat", "在…方面吸引", "Was reizt dich an dieser Idee?"), ("zu", "Dat", "激起", "Das reizt mich zu einer Antwort.")),
    "reizvoll": (("für", "Akk", "对…有吸引力", "Das Angebot ist reizvoll für Kunden."),),
    "relevant": (("für", "Akk", "对…重要", "Das ist relevant für unser Projekt."),),
    "reservieren": (("für", "Akk", "为…预订", "Wir haben einen Tisch für zwei Personen reserviert."),),
    "retten": (("vor", "Dat", "从…中救出", "Er rettete das Kind vor dem Ertrinken."),),
    "richtig": (("für", "Akk", "对…合适/正确", "Das ist richtig für die Aufgabe."),),
    "riechen": (("nach", "Dat", "闻起来有…味", "Es riecht hier nach frischem Brot."),),
    "rufen": (("nach", "Dat", "大声呼唤…", "Die Frau ruft nach Hilfe."),),
    "rumbasteln": (("an", "Dat", "在…上摆弄", "Er rumbastelt an seinem alten Radio."),),
    "rätseln": (("über", "Akk", "对…猜测", "Wir rätseln über die Lösung des Rätsels."), ("an", "Dat", "为…伤脑筋", "Sie rätselt an einer schwierigen Aufgabe.")),
    "rücksichtslose": (("gegenüber", "Dat", "对…粗暴无礼", "Sie ist rücksichtslos gegenüber ihren Mitmenschen."),),
    "sammeln": (("für", "Akk", "为…收集", "Wir sammeln Geld für das Fest."),),
    "sauer": (("auf", "Akk", "对…生气", "Er ist sauer auf mich."),),
    "schalten": (("auf", "Akk", "切换到", "Ich schalte auf Rot."),),
    "scharf": (("auf", "Akk", "渴望…", "Er ist scharf auf Rache."),),
    "scheitern": (("an", "Dat", "因…失败", "Das Projekt scheiterte an der Finanzierung."),),
    "schieben": (("auf", "Akk", "推卸给…", "Er schiebt die Schuld auf seinen Kollegen."),),
    "schießen": (("auf", "Akk", "向…射击", "Der Polizist schießt auf den Angreifer."),),
    "schimpfen": (("auf", "Akk", "骂…", "Sie schimpft auf ihren Mann."), ("über", "Akk", "抱怨…", "Er schimpft über die Arbeitszeiten.")),
    "schließen": (("aus", "Dat", "从…推断出", "Ich schließe aus seinem Blick, dass er traurig ist."), ("mit", "Dat", "以…结束", "Ich schließe meine Rede mit einem Zitat.")),
    "schmecken": (("nach", "Dat", "尝起来有…味", "Die Suppe schmeckt nach Salz."),),
    "schreiben": (("an", "Akk", "写信给…", "Ich schreibe an meine Tante."), ("über", "Akk", "写关于…", "Sie schreibt über ihre Reise.")),
    "schreien": (("nach", "Dat", "呼喊着要…", "Er schreit nach Hilfe."),),
    "schuldig": (("an", "Dat", "对…有罪", "Er ist schuldig an dem Brand."),),
    "schwanger": (("mit", "Dat", "怀有", "Sie ist schwanger mit Zwillingen."),),
    "schweben": (("in", "Dat", "处于（状态）", "Er schwebt in Lebensgefahr."),),
    "schweigen": (("zu", "Dat", "对…沉默", "Er schweigt zu dieser Frage."),),
    "schädlich": (("für", "Akk", "对…有害", "Rauchen ist schädlich für die Gesundheit."),),
    "schätzen": (("auf", "Akk", "估计为", "Ich schätze den Wert auf 100 Euro."), ("an", "Dat", "赏识", "Ich schätze an ihm seine Zuverlässigkeit.")),
    "schützen": (("vor", "Dat", "保护免受", "Die Creme schützt vor der Sonne."),),
    "sehen": (("nach", "Dat", "照看", "Sie sieht nach dem Kind."), ("auf", "Akk", "注重", "Er sieht auf die Qualität."), ("in", "Dat", "视为", "Ich sehe in ihm einen guten Freund.")),
    "senkrecht": (("zu", "Dat", "垂直于", "Die Wand ist senkrecht zum Boden."),),
    "sich-anmelden": (("zu", "Dat", "报名参加", "Er meldet sich zum Kurs an."), ("bei", "Dat", "在…登记", "Ich melde mich bei der Behörde an.")),
    "sich-ausruhen": (("von", "Dat", "从…恢复", "Er ruht sich von der Arbeit aus."),),
    "sich-bedanken": (("bei", "Dat", "感谢某人", "Ich bedanke mich bei dir."), ("für", "Akk", "为…感谢", "Wir bedanken uns für das Geschenk.")),
    "sich-beeilen": (("mit", "Dat", "赶紧做…", "Du musst dich mit der Arbeit beeilen."),),
    "sich-beschweren": (("über", "Akk", "抱怨…", "Er beschwert sich über das Wetter."), ("bei", "Dat", "向…投诉", "Sie beschwert sich beim Chef.")),
    "sich-bewerben": (("um", "Akk", "申请…", "Er bewirbt sich um die Stelle."), ("bei", "Dat", "向…申请", "Sie bewirbt sich bei der Firma.")),
    "sich-eintragen": (("in", "Akk", "登记入…", "Ich trage mich in die Liste ein."),),
    "sich-entschuldigen": (("bei", "Dat", "向…道歉", "Er entschuldigt sich bei dem Lehrer."), ("für", "Akk", "为…道歉", "Sie entschuldigt sich für den Fehler.")),
    "sich-erinnern": (("an", "Akk", "(sich) 想起；记得", "Er erinnert sich an seine Kindheit."),),
    "sich-freuen": (("über", "Akk", "(sich) 因…高兴", "Ich freue mich über das Geschenk."), ("auf", "Akk", "(sich) 期待", "Wir freuen uns auf den Urlaub."), ("an", "Dat", "(sich) 享受；欣赏", "Sie freut sich an den Blumen.")),
    "sich-interessieren": (("für", "Akk", "(sich) 对…感兴趣", "Sie interessiert sich für Kunst."),),
    "sich-kümmern": (("um", "Akk", "(sich) 关心", "Sie kümmert sich um ihre kranke Mutter."),),
    "sich-streiten": (("über", "Akk", "(sich) 争论", "Wir streiten uns über die Politik."), ("um", "Akk", "(sich) 争夺", "Die Kinder streiten sich um das Spielzeug.")),
    "sich-treffen": (("mit", "Dat", "(sich) 见面", "Ich treffe mich mit meinen Freunden."),),
    "sich-unterhalten": (("mit", "Dat", "(sich) 交谈", "Sie unterhält sich mit ihrem Kollegen."), ("über", "Akk", "(sich) 谈论", "Wir unterhalten uns über das Wetter.")),
    "sich-verlieben": (("in", "Akk", "(sich) 爱上", "Er verliebt sich in seine Nachbarin."),),
    "sich-ärgern": (("über", "Akk", "(sich) 生气", "Sie ärgert sich über den Fehler."),),
    "sich-über-informieren": (("über", "Akk", "(sich) 了解", "Er informiert sich über das Angebot."),),
    "sicher": (("vor", "Dat", "免受", "Das Haus ist sicher vor Einbrechern."),),
    "sichern": (("vor", "Dat", "保护免受", "Die Mauer sichert die Stadt vor Feinden."),),
    "siegen": (("über", "Akk", "战胜", "Die Mannschaft siegte über den Rivalen."),),
    "sorgen": (("für", "Akk", "照料/负责", "Sie sorgt für ihre kranke Mutter."), ("um", "Akk", "(sich)担心", "Ich sorge mich um dich.")),
    "sparen": (("für", "Akk", "为…存钱", "Wir sparen für ein neues Auto."), ("an", "Dat", "节省", "Man sollte nicht am Essen sparen.")),
    "sparsam": (("mit", "Dat", "节省使用", "Sie ist sparsam mit ihrem Geld."),),
    "spenden": (("für", "Akk", "为…捐赠", "Er spendet Geld für die Kinderhilfe."),),
    "sprechen": (("über", "Akk", "谈论", "Wir sprechen über die Prüfung."), ("mit", "Dat", "与…交谈", "Ich spreche mit dem Lehrer."), ("von", "Dat", "提到", "Sie spricht oft von ihrer Reise.")),
    "stammen": (("aus", "Dat", "来自（地方）", "Er stammt aus Berlin."), ("von", "Dat", "出自（来源）", "Das Bild stammt von Picasso.")),
    "stecken": (("in", "Dat", "卡在，陷入", "Der Schlüssel steckt im Schloss."),),
    "stehen": (("auf", "Akk", "喜欢（口语）", "Ich stehe auf Popmusik."), ("für", "Akk", "代表，象征", "Das Symbol steht für Frieden."), ("zu", "Dat", "支持，信守", "Er steht zu seinem Wort.")),
    "sterben": (("an", "Dat", "死于（疾病）", "Er starb an Krebs."), ("vor", "Dat", "死于（情感）", "Sie starb vor Hunger.")),
    "stimmen": (("für", "Akk", "投票赞成", "Er stimmt für den Vorschlag."), ("gegen", "Akk", "投票反对", "Sie stimmt gegen den Plan.")),
    "stinken": (("nach", "Dat", "有…气味", "Das Zimmer stinkt nach Rauch."),),
    "stolz": (("auf", "Akk", "为…自豪", "Die Eltern sind stolz auf ihre Tochter."),),
    "straubt": (("gegen", "Akk", "(sich)反抗", "Er sträubt sich gegen die Entscheidung."),),
    "streben": (("nach", "Dat", "追求", "Er strebt nach Erfolg."),),
    "streng": (("mit", "Dat", "对…严格", "Der Lehrer ist streng mit den Schülern."),),
    "stören": (("bei", "Dat", "打扰", "Sie stört ihn bei der Arbeit."),),
    "stürzen": (("auf", "Akk", "(sich)扑向", "Er stürzt sich auf das Essen."), ("in", "Akk", "陷入", "Das Land stürzt in eine Krise.")),
    "suchen": (("nach", "Dat", "寻找", "Sie sucht nach ihrem Schlüssel."),),
    "süchtig": (("nach", "Dat", "对…上瘾", "Er ist süchtig nach Alkohol."),),
    "südlich": (("von", "Dat", "在…以南", "Die Stadt liegt südlich von Berlin."),),
    "taub": (("für", "Akk", "对…无动于衷", "Er ist taub für alle Warnungen."),),
    "tauschen": (("mit", "Dat", "与…交换", "Ich tausche mit ihm den Platz."), ("gegen", "Akk", "用…交换", "Er tauscht seinen Stift gegen meinen.")),
    "teilen": (("mit", "Dat", "与…分享", "Ich teile meine Meinung mit dir."), ("in", "Akk", "把…分成", "Wir teilen den Kuchen in vier Stücke.")),
    "teilnehmen": (("an", "Dat", "参加", "Sie nimmt an der Konferenz teil."),),
    "telefonieren": (("mit", "Dat", "与…通电话", "Ich telefoniere mit meiner Mutter."),),
    "tippen": (("auf", "Akk", "估计，认为", "Ich tippe auf einen Sieg."),),
    "tolerant": (("gegenüber", "Dat", "对…宽容", "Sie ist tolerant gegenüber anderen Meinungen."),),
    "traurig": (("über", "Akk", "为…难过", "Sie ist traurig über den Verlust."),),
    "treffen": (("auf", "Akk", "遇到/撞上", "Die Maßnahme trifft auf Zustimmung."), ("mit", "Dat", "(sich) 与…会面", "Ich treffe mich mit meiner Kollegin.")),
    "treu": (("gegenüber", "Dat", "对…忠诚", "Er ist treu gegenüber seinen Freunden."),),
    "trinken": (("auf", "Akk", "为…干杯", "Wir trinken auf deine Gesundheit."),),
    "träumen": (("von", "Dat", "梦想", "Sie träumt von einer Weltreise."),),
    "typisch": (("für", "Akk", "典型…", "Das ist typisch für diese Region."),),
    "umgehen": (("mit", "Dat", "处理，对待", "Er kann gut mit Kindern umgehen."),),
    "umgekommen": (("vor", "Dat", "死于，因…丧命", "Er ist vor Kälte umgekommen."),),
    "umhören": (("nach", "Dat", "(sich) 打听", "Ich höre mich nach einer Wohnung um."),),
    "umsatteln": (("auf", "Akk", "改行，转换", "Er sattelt auf Informatik um."),),
    "umsetzen": (("in", "Akk", "转化为，付诸", "Sie setzt ihre Idee in die Tat um."),),
    "umsteigen": (("auf", "Akk", "换乘，改乘", "Wir steigen am Bahnhof auf den Bus um."),),
    "umtauschen": (("gegen", "Akk", "换，退换", "Ich möchte die Schuhe gegen eine andere Größe umtauschen."), ("in", "Akk", "兑换", "Er tauscht Euro in Dollar um.")),
    "unabdingbar": (("für", "Akk", "对…不可或缺", "Vertrauen ist unabdingbar für eine gute Partnerschaft."),),
    "unbegreiflich": (("für", "Akk", "对…不可理解", "Seine Entscheidung ist für mich unbegreiflich."),),
    "unbeteiligt": (("an", "Dat", "未参与，与…无关", "Er blieb unbeteiligt an der Diskussion."),),
    "ungünstigen": (("für", "Akk", "对…不利", "Die Lage ist ungünstig für uns."),),
    "unschuldig": (("an", "Dat", "对…无罪", "Er ist unschuldig an dem Unfall."),),
    "unterhalten": (("über", "Akk", "(sich)聊起", "Wir unterhalten uns über Musik."),),
    "unterrichten": (("über", "Akk", "通知关于", "Er unterrichtete uns über die Neuigkeit."), ("in", "Dat", "教授科目", "Sie unterrichtet in Mathematik.")),
    "unterscheiden": (("zwischen", "Dat", "区分两者", "Man muss zwischen Tatsachen und Meinungen unterscheiden."), ("von", "Dat", "与…区分", "Ich kann diese Art von jener nicht unterscheiden.")),
    "unterstützen": (("bei", "Dat", "支持", "Er unterstützt mich bei meiner Arbeit."),),
    "untersuchen": (("auf", "Akk", "检查…有无", "Der Arzt untersucht das Blut auf Viren."),),
    "verabredet": (("mit", "Dat", "与...约好", "Ich bin mit ihm verabredet."),),
    "verabredet-sein": (("mit", "Dat", "与...有约", "Sie ist mit dir verabredet."),),
    "verankert": (("in", "Dat", "植根于", "Das Recht ist in der Verfassung verankert."),),
    "veranlassen": (("zu", "Dat", "促使", "Das veranlasst ihn zu einer Klage."),),
    "verantwortlich": (("für", "Akk", "对…负责", "Sie ist für das Projekt verantwortlich."),),
    "verbessern": (("in", "Dat", "在某方面改进(sich)", "Sie verbessert sich in Deutsch."),),
    "verbinden": (("mit", "Dat", "与...连接", "Man verbindet dieses Gerät mit dem Computer."),),
    "verbindlich": (("für", "Akk", "对...有约束力", "Diese Regel ist für alle verbindlich."),),
    "verboten": (("für", "Akk", "对…禁止", "Das Rauchen ist für Minderjährige verboten."),),
    "verboten-sein": (("für", "Akk", "对…是禁止的", "Essen im Unterricht ist für Schüler verboten."),),
    "verbreitet": (("unter", "Dat", "在…中普遍", "Diese Sitte ist unter der Jugend weit verbreitet."),),
    "verbringen": (("mit", "Dat", "和…一起度过", "Er verbringt das Wochenende mit seiner Familie."),),
    "verbunden": (("mit", "Dat", "与…相连", "Das Schicksal ist mit diesem Ort verbunden."),),
    "verbündete": (("mit", "Dat", "与…结盟的", "Eine mit ihm verbündete Frau half ihm."),),
    "verdienen": (("an", "Dat", "靠…赚钱", "Er verdient viel an diesem Produkt."),),
    "verdrängt": (("aus", "Dat", "被挤出…", "Er wurde aus seinem Amt verdrängt."),),
    "verdächtig": (("auf", "Akk", "疑似…", "Der Knoten ist verdächtig auf Krebs."),),
    "verdächtige": (("auf", "Akk", "疑似…的", "Die auf Krebs verdächtige Wucherung wurde untersucht."),),
    "vereinbaren": (("mit", "Dat", "与…商定", "Wir müssen einen Termin mit dem Kunden vereinbaren."),),
    "vererben": (("an", "Akk", "把…传给", "Er vererbt das Haus an seinen Sohn."),),
    "verfahren": (("mit", "Dat", "处理/对待", "Wir müssen vorsichtig mit dem Material verfahren."),),
    "verfallen": (("auf", "Akk", "突然想到", "Er verfiel auf eine seltsame Idee."), ("in", "Akk", "陷入…", "Sie verfiel in tiefe Trauer.")),
    "verfügbar": (("für", "Akk", "可供…使用", "Der Raum ist für die Konferenz verfügbar."),),
    "verfügen": (("über", "Akk", "拥有/支配", "Er verfügt über große Erfahrung."),),
    "vergleichen": (("mit", "Dat", "与…比较", "Man sollte Äpfel nicht mit Birnen vergleichen."),),
    "vergnügt": (("über", "Akk", "对…感到高兴", "Sie war vergnügt über das Geschenk."),),
    "vergrößern": (("um", "Akk", "扩大了…", "Die Firma vergrößert ihren Umsatz um zehn Prozent."),),
    "verheerenden": (("für", "Akk", "对…是毁灭性的", "Die Nachricht war verheerend für das Unternehmen."),),
    "verheiratet": (("mit", "Dat", "与…结婚", "Sie ist mit einem Arzt verheiratet."),),
    "verhängt": (("über", "Akk", "对…施加", "Das Gericht verhängt eine Strafe über den Angeklagten."),),
    "verkaufen": (("an", "Akk", "卖给…", "Er verkauft das alte Auto an einen Sammler."),),
    "verlangen": (("nach", "Dat", "渴望得到", "Das Kind verlangt nach Aufmerksamkeit."), ("von", "Dat", "向…要求", "Ich verlange das von dir.")),
    "verlassen": (("auf", "Akk", "(sich)信赖", "Du kannst dich auf mich verlassen."),),
    "verliebt": (("in", "Akk", "爱上…", "Er ist sehr verliebt in seine Frau."),),
    "verlieren": (("an", "Dat", "在…方面失去", "Das alte Haus verliert an Wert."), ("gegen", "Akk", "输给", "Die Mannschaft verlor gegen den Meister.")),
    "verlängern": (("um", "Akk", "延长了…", "Wir verlängern die Straße um fünf Kilometer."),),
    "vermieten": (("an", "Akk", "出租给", "Sie vermietet ein Zimmer an Studenten."),),
    "verpflichtet": (("zu", "Dat", "有义务做", "Er ist zu dieser Arbeit verpflichtet."),),
    "verrückt": (("nach", "Dat", "对…痴迷", "Sie ist verrückt nach Schokolade."),),
    "verschieben": (("auf", "Akk", "推迟到", "Wir verschieben das Treffen auf morgen."),),
    "verschieden": (("von", "Dat", "不同于", "Mein Ansatz ist verschieden von deinem."),),
    "verschont": (("von", "Dat", "免于", "Die Stadt blieb von Bomben verschont."),),
    "verseucht": (("mit", "Dat", "被…污染", "Das Wasser ist mit Chemikalien verseucht."),),
    "versichern": (("gegen", "Akk", "投保以防", "Er hat sein Haus gegen Feuer versichert."),),
    "versprechen": (("von", "Dat", "(sich) 期待得到", "Ich verspreche mir viel von diesem Kurs."),),
    "verstehen": (("von", "Dat", "了解，懂得", "Er versteht viel von klassischer Musik."), ("unter", "Dat", "理解为", "Was verstehen Sie unter Freiheit?"), ("auf", "Akk", "(sich) 擅长", "Sie versteht sich auf die französische Küche."), ("mit", "Dat", "(sich) 与...相处", "Er versteht sich gut mit seinen Kollegen.")),
    "verständigen": (("über", "Akk", "(sich) 达成一致", "Wir müssen uns über das Vorgehen verständigen."), ("von", "Dat", "通知", "Er verständigte die Polizei von dem Vorfall."), ("mit", "Dat", "(sich) 沟通", "Sie verständigt sich mit dem Kunden auf Englisch.")),
    "verständlich": (("für", "Akk", "对...可理解", "Der Text ist für Kinder verständlich."),),
    "versuchen": (("an", "Dat", "(sich) 尝试，涉足", "Er versucht sich an einem neuen Projekt."),),
    "verteilen": (("auf", "Akk", "分配到", "Wir verteilen die Aufgaben auf die Gruppe."), ("an", "Akk", "分发给", "Er verteilt Geschenke an die Kinder."), ("unter", "Dat", "在...之间分配", "Sie verteilte die Süßigkeiten unter den Kindern.")),
    "vertrauen": (("auf", "Akk", "信任，信赖", "Ich vertraue auf deine Hilfe."), ("in", "Akk", "信任，相信", "Sie vertraut in die Zukunft.")),
    "verträglich": (("mit", "Dat", "与...兼容", "Das Programm ist mit dem System verträglich."),),
    "verurteilen": (("zu", "Dat", "判处", "Der Richter verurteilte ihn zu drei Jahren Haft."),),
    "verwandt": (("mit", "Dat", "与...有关/有亲戚关系", "Sie ist mit meiner Familie verwandt."),),
    "verwechseln": (("mit", "Dat", "把...与...混淆", "Er verwechselt ihn mit seinem Zwillingsbruder."),),
    "verwenden": (("auf", "Akk", "花费…于", "Er verwendet viel Zeit auf sein Studium."), ("für", "Akk", "用于", "Ich verwende das Geld für ein Buch."), ("zu", "Dat", "用作", "Er verwendet diese Pflanze zur Heilung.")),
    "verwundbar": (("für", "Akk", "易受…伤害", "Kinder sind verwundbar für Gewalt."),),
    "verwöhnen": (("mit", "Dat", "用…宠爱", "Sie verwöhnt ihre Katze mit Leckerlis."),),
    "verzehren": (("nach", "Dat", "(sich)渴望", "Er verzehrt sich nach Freiheit."),),
    "verzichten": (("auf", "Akk", "放弃", "Wir verzichten auf den Urlaub."),),
    "verzweifeln": (("an", "Dat", "对…绝望", "Sie verzweifelt an der Lösung."),),
    "vorangekommen": (("mit", "Dat", "在…取得进展", "Wir sind mit dem Projekt vorangekommen."),),
    "vorbereiten": (("auf", "Akk", "(sich)为…做准备", "Ich bereite mich auf die Prüfung vor."),),
    "vorgesehenen": (("für", "Akk", "为…预留", "Die Mittel sind für den Bau vorgesehen."),),
    "vorsichtig": (("mit", "Dat", "小心对待", "Sei vorsichtig mit der Vase!"),),
    "wachgerüttelt": (("aus", "Dat", "从…中唤醒", "Er wurde aus seiner Gleichgültigkeit wachgerüttelt."),),
    "wachsen": (("an", "Dat", "因…而成长", "Er ist an der Aufgabe gewachsen."),),
    "warm": (("um", "Akk", "内心温暖", "Mir ist warm ums Herz."), ("mit", "Dat", "与…合得来", "Er ist mit den Nachbarn warm geworden.")),
    "warnen": (("vor", "Dat", "警告防范", "Er warnt vor dem Sturm."),),
    "warten": (("auf", "Akk", "等待", "Ich warte auf den Bus."),),
    "wecken": (("in", "Dat", "唤起", "Das weckt in mir Erinnerungen."), ("bei", "Dat", "引起（兴趣）", "Das weckt bei den Kindern Interesse.")),
    "wegweisend": (("für", "Akk", "对…有导向意义", "Ihre Forschung ist wegweisend für die Branche."),),
    "weinen": (("über", "Akk", "为…而哭", "Sie weint über den Verlust ihres Kindes."), ("um", "Akk", "为…哀泣", "Er weint um seine verstorbene Mutter.")),
    "weiterhelfen": (("bei", "Dat", "帮助…解决", "Kann ich Ihnen bei der Aufgabe weiterhelfen?"),),
    "weiterleiten": (("an", "Akk", "转交给…", "Ich leite die Nachricht an meinen Chef weiter."),),
    "weitermachen": (("mit", "Dat", "继续做…", "Wir machen mit der Arbeit weiter."),),
    "wenden": (("an", "Akk", "(sich)向…求助", "Er wendet sich an seinen Anwalt."), ("gegen", "Akk", "(sich)反对…", "Sie wendet sich gegen die Pläne.")),
    "werden": (("zu", "Dat", "变成…", "Er wird zum erfolgreichen Schriftsteller."),),
    "werfen": (("nach", "Dat", "朝…扔", "Der Junge wirft nach dem Hund."), ("mit", "Dat", "用…扔", "Er wirft mit einem Stein.")),
    "wertvoll": (("für", "Akk", "对…有价值", "Diese Erfahrung ist wertvoll für mich."),),
    "wesentlich": (("für", "Akk", "对…重要", "Diese Information ist wesentlich für den Erfolg."),),
    "wesentliche": (("für", "Akk", "对…重要", "Diese Rolle ist wesentlich für den Prozess."),),
    "westlich": (("von", "Dat", "在…以西", "Das Dorf liegt westlich von der Stadt."),),
    "wetten": (("auf", "Akk", "赌…赢", "Ich wette auf den Sieg unserer Mannschaft."),),
    "wichtig": (("für", "Akk", "对…重要", "Gesundheit ist wichtig für das Leben."),),
    "widerzuspiegeln": (("in", "Dat", "(sich)在…中反映", "Seine Gefühle scheinen sich in seinem Verhalten widerzuspiegeln."),),
    "wiegen": (("in", "Dat", "(sich)沉溺于，抱有", "Er wiegt sich in falscher Sicherheit."),),
    "wild": (("auf", "Akk", "急切想要，渴望", "Er ist wild auf Schokolade."),),
    "wirken": (("auf", "Akk", "对…起作用/影响", "Diese Musik wirkt auf mich."), ("gegen", "Akk", "对抗，对…有效", "Das Medikament wirkt gegen Kopfschmerzen.")),
    "wirksam": (("gegen", "Akk", "对…有效", "Das Mittel ist wirksam gegen Erkältungen."),),
    "wissen": (("von", "Dat", "知道，知晓", "Ich weiß von seinem Plan."), ("über", "Akk", "了解，知道关于", "Sie weiß viel über Kunst.")),
    "wütend": (("auf", "Akk", "对…生气", "Ich bin wütend auf meinen Bruder."),),
    "zeichnen": (("für", "Akk", "为…负责", "Er zeichnet für die Organisation."),),
    "ziehen": (("an", "Dat", "拉；拽", "Er zieht an der Tür."),),
    "zufrieden": (("mit", "Dat", "满意", "Ich bin mit dem Ergebnis zufrieden."),),
    "zugehen": (("auf", "Akk", "走向；接近", "Er geht auf die Frau zu."),),
    "zugänglich": (("für", "Akk", "可供…使用", "Das Gebäude ist für Besucher zugänglich."),),
    "zumutbar": (("für", "Akk", "对…可承受", "Die Belastung ist für ihn nicht zumutbar."),),
    "zunehmen": (("an", "Dat", "在…上增加", "Er nimmt an Gewicht zu."),),
    "zurechtkommen": (("mit", "Dat", "应付；相处", "Sie kommt mit dem Stress gut zurecht."),),
    "zurückbleiben": (("hinter", "Dat", "落后于", "Er bleibt hinter den anderen zurück."),),
    "zurückgehen": (("auf", "Akk", "追溯到", "Das Problem geht auf einen Fehler zurück."),),
    "zurückgeht": (("auf", "Akk", "追溯到", "Die Entscheidung geht auf den Chef zurück."),),
    "zurückkommen": (("auf", "Akk", "回到话题", "Ich komme später auf Ihre Frage zurück."),),
    "zusammenfassen": (("zu", "Dat", "概括为", "Sie fasst ihre Notizen zu einem Text zusammen."),),
    "zusammenstossen": (("mit", "Dat", "与…相撞", "Das Auto stösst mit dem Baum zusammen."),),
    "zuschauen": (("bei", "Dat", "旁观", "Sie schaut den Kindern beim Spielen zu."),),
    "zuständig": (("für", "Akk", "负责", "Er ist für den Vertrieb zuständig."),),
    "zusätzlich": (("zu", "Dat", "除…之外", "Zusätzlich zu seinem Gehalt erhält er Prämien."),),
    "zweifeln": (("an", "Dat", "怀疑", "Er zweifelt an seiner Entscheidung."),),
    "zählen": (("auf", "Akk", "指望", "Ich zähle auf deine Unterstützung."), ("zu", "Dat", "属于", "Diese Sängerin zählt zu den Besten.")),
    "ändern": (("an", "Dat", "改变", "Er will nichts an seiner Entscheidung ändern."),),
    "ängstlich": (("vor", "Dat", "害怕", "Das Mädchen ist ängstlich vor dem Gewitter."),),
    "ärgerlich": (("über", "Akk", "对…生气", "Er ist ärgerlich über die Verspätung."),),
    "ärgern": (("über", "Akk", "(sich)为…生气", "Er ärgert sich über den Fehler."),),
    "äußerte": (("über", "Akk", "(sich)发表意见", "Er äußerte sich über das Problem."), ("zu", "Dat", "(sich)表态", "Sie äußerte sich zu den Vorwürfen.")),
    "östlich": (("von", "Dat", "在…以东", "Das Dorf liegt östlich von Berlin."),),
    "üben": (("in", "Dat", "(sich)练习", "Er übt sich im Klavierspiel."),),
    "überlaufen": (("zu", "Dat", "投奔", "Er ist zum Feind übergelaufen."),),
    "übernehmen": (("von", "Dat", "从…接管", "Ich übernehme das Amt von meinem Vorgänger."),),
    "überprüfen": (("auf", "Akk", "检查…是否有", "Die Firma überprüft die Produkte auf Sicherheit."),),
    "überraschen": (("mit", "Dat", "以…使惊讶", "Er überraschte mich mit einem Geschenk."),),
    "überreden": (("zu", "Dat", "说服…做", "Sie überredete ihn zum Bleiben."),),
    "übersetzen": (("aus", "Dat", "从…翻译", "Er übersetzt den Text aus dem Englischen."), ("in", "Akk", "译成…", "Sie übersetzt das Buch ins Französische.")),
    "übertragen": (("auf", "Akk", "转移到", "Man übertrug die Daten auf den Server."), ("in", "Akk", "转成", "Er übertrug den Roman in eine andere Sprache.")),
    "übertreiben": (("mit", "Dat", "对…过分", "Er übertreibt mit seiner Freundlichkeit."),),
    "überweisen": (("auf", "Akk", "汇款到账户", "Ich überweise das Geld auf dein Konto."), ("an", "Akk", "汇款给某人", "Er überwies den Betrag an den Verkäufer.")),
    "überwältigt": (("von", "Dat", "被…压倒", "Sie war von Angst überwältigt."),),
    "überzeugen": (("von", "Dat", "使…信服", "Er überzeugte mich von seiner Ehrlichkeit."),),
    "überzeugt": (("von", "Dat", "确信", "Er ist von seiner Idee überzeugt."),),
    "überzogen": (("mit", "Dat", "覆盖着…", "Der Kuchen ist mit Schokolade überzogen."),),
}
