# -*- coding: utf-8 -*-
"""AI 批量生成的德语动词/形容词固定介词搭配表（auto-generated）。

Schema: lemma -> ((介词, 格, 中文义, 例句), ...)
值是**元组的元组**：一个词头可带多个介词且意思不同
（bestehen auf 坚持 / aus 由…组成 / in 在于），单值会丢义项。

键全小写、反身动词不带 sich（freuen 而非 sich freuen），
以便直接匹配 spaCy 的 lemma 输出。
手动改会丢：必考搭配请改 tools/build_prep.py 的 SEED_COLLOCATIONS，
长尾靠 AI 生成，两者由 tools/build_prep.py 合并（seed 优先）。
"""

PREP_COLLOCATIONS = {  # 285 词条 / 349 条搭配 · 已问过 949 词 · seed 47 词 + AI 长尾
    "abfahren": (("auf", "Akk", "着迷，喜欢", "Sie fährt total auf diese Musik ab."),),
    "abheben": (("auf", "Akk", "针对，着眼于", "Der Film hebt auf die Probleme der Jugend ab."),),
    "abhängen": (("von", "Dat", "取决于", "Der Erfolg hängt von der Vorbereitung ab."),),
    "abhängig": (("von", "Dat", "依赖于", "Der Erfolg ist von vielen Faktoren abhängig."),),
    "ablenken": (("von", "Dat", "使分心", "Das Geräusch lenkt von der Arbeit ab."),),
    "abrechnen": (("mit", "Dat", "算账", "Er rechnet mit seinem Betrüger ab."),),
    "abstimmen": (("auf", "Akk", "协调", "Wir stimmen die Maßnahmen auf die Bedürfnisse ab."), ("über", "Akk", "表决", "Das Parlament stimmt über den Gesetzentwurf ab."), ("mit", "Dat", "与…协调", "Er stimmt das Vorgehen mit seinem Kollegen ab.")),
    "abtreten": (("an", "Akk", "移交给", "Der Minister tritt sein Amt an seinen Nachfolger ab."),),
    "abweichen": (("von", "Dat", "偏离", "Die Ergebnisse weichen von der Norm ab."),),
    "abwenden": (("von", "Dat", "(sich)背离", "Er wendet sich von der Gesellschaft ab."),),
    "achten": (("auf", "Akk", "注意", "Bitte achten Sie auf die Verkehrszeichen."),),
    "alternativ": (("zu", "Dat", "替代", "Wir suchen einen alternativen Termin zu dem geplanten."),),
    "anerkennen": (("als", "Akk", "承认…为", "Er erkennt ihn als seinen Vorgesetzten an."),),
    "anfangen": (("mit", "Dat", "开始做", "Wir fangen mit der Übung an."),),
    "anfällig": (("für", "Akk", "易受…影响", "Er ist anfällig für Grippe."),),
    "angeben": (("mit", "Dat", "吹嘘，炫耀", "Er gibt mit seinem Auto an."),),
    "angleichend": (("an", "Akk", "使…与…一致", "Sie gleicht ihre Daten an die Realität an."),),
    "ankommen": (("auf", "Akk", "取决于", "Es kommt auf deine Entscheidung an."), ("gegen", "Akk", "对抗/抵挡", "Gegen diese Maßnahmen kommen wir nicht an.")),
    "anlegen": (("mit", "Dat", "（sich）与…争吵", "Er hat sich mit seinem Bruder angelegt."),),
    "anmelden": (("bei", "Dat", "（sich）在…登记", "Ich melde mich bei der Agentur an."), ("für", "Akk", "（sich）报名", "Sie meldet sich für den Kurs an.")),
    "anschließen": (("an", "Akk", "连接到", "Schließen Sie das Gerät an den Computer an."),),
    "ansprechen": (("auf", "Akk", "对…有反应", "Der Patient spricht gut auf die Therapie an."),),
    "antworten": (("auf", "Akk", "回答", "Er antwortet auf die Frage."),),
    "anwenden": (("auf", "Akk", "应用于", "Ich wende diese Methode auf das Problem an."),),
    "anwesend": (("bei", "Dat", "在场", "Er war bei der Versammlung anwesend."),),
    "arbeiten": (("an", "Dat", "致力于，从事", "Er arbeitet an einem neuen Roman."), ("für", "Akk", "为...工作", "Sie arbeitet für eine große Firma."), ("bei", "Dat", "在...工作", "Er arbeitet bei Siemens.")),
    "arm": (("an", "Dat", "缺乏，不足", "Das Land ist arm an natürlichen Ressourcen."),),
    "auffallen": (("durch", "Akk", "因…引人注意", "Er fällt durch seine Kleidung auf."),),
    "aufgeschlossen": (("für", "Akk", "对…开放", "Sie ist aufgeschlossen für neue Ideen."),),
    "aufhalten": (("in", "Dat", "(sich)停留于", "Er hält sich in Berlin auf."),),
    "aufhören": (("mit", "Dat", "停止做", "Er hört mit dem Rauchen auf."),),
    "aufmerksam": (("auf", "Akk", "对…注意", "Er ist aufmerksam auf die Details."),),
    "aufnehmen": (("in", "Akk", "接纳到…里", "Sie nimmt ihn in ihr Team auf."),),
    "aufpassen": (("auf", "Akk", "注意，照看", "Pass auf den Verkehr auf."),),
    "aufregen": (("über", "Akk", "(sich)对…气愤", "Er regt sich über den Lärm auf."),),
    "aufräumen": (("mit", "Dat", "清除", "Sie räumte mit alten Vorurteilen auf."),),
    "aufstehen": (("gegen", "Akk", "反抗", "Viele Bürger standen gegen die Diktatur auf."), ("für", "Akk", "支持", "Er steht für seine Rechte auf.")),
    "auftreten": (("gegen", "Akk", "对抗", "Sie tritt gegen Ungerechtigkeit auf."), ("für", "Akk", "支持", "Er tritt für die Umwelt auf.")),
    "aufwachen": (("aus", "Dat", "从…醒来", "Er wachte aus einem Traum auf."),),
    "aus-sein": (("mit", "Dat", "结束", "Es ist aus mit unserer Freundschaft."),),
    "ausarten": (("in", "Akk", "演变成", "Die Diskussion artete in einen Streit aus."),),
    "ausgeben": (("für", "Akk", "花费", "Sie gibt viel Geld für Bücher aus."),),
    "ausgehen": (("von", "Dat", "以…为前提", "Die Theorie geht von einfachen Annahmen aus."),),
    "ausreichen": (("für", "Akk", "足够用于", "Das Geld reicht für die Miete aus."),),
    "ausreichend": (("für", "Akk", "对…足够", "Die Vorräte sind ausreichend für den Winter."),),
    "ausrichten": (("auf", "Akk", "将…对准", "Er richtet die Kamera auf das Denkmal."), ("nach", "Dat", "(sich) 按照…调整", "Wir richten uns nach deinem Rat."), ("an", "Dat", "(sich) 以…为准", "Das Projekt richtet sich an den Bedürfnissen aus.")),
    "aussagen": (("über", "Akk", "陈述关于", "Er sagt über das Unglück aus."), ("gegen", "Akk", "作证指控", "Die Zeugin sagt gegen den Angeklagten aus.")),
    "ausschließen": (("aus", "Dat", "把…开除出", "Der Spieler wurde aus dem Team ausgeschlossen."), ("von", "Dat", "将…排除在…外", "Sie schloss ihn von der Besprechung aus.")),
    "aussehen": (("nach", "Dat", "看起来像", "Das sieht nach Regen aus."),),
    "aussprechen": (("für", "Akk", "(sich) 赞成", "Ich spreche mich für den Plan aus."), ("gegen", "Akk", "(sich) 反对", "Sie spricht sich gegen die Idee aus.")),
    "aussteigen": (("aus", "Dat", "从…下车/退出", "Sie steigt aus dem Zug aus."),),
    "austauschen": (("gegen", "Akk", "用…替换", "Er tauscht das alte Gerät gegen ein neues aus."), ("mit", "Dat", "与…交流", "Sie tauscht sich mit ihrer Kollegin aus."), ("über", "Akk", "交流…", "Wir tauschten uns über das Projekt aus.")),
    "ausweichen": (("auf", "Akk", "改用", "Der Redner wich auf ein anderes Thema aus."),),
    "auswählen": (("aus", "Dat", "从…选出", "Sie wählt ein Buch aus dem Regal aus."),),
    "basieren": (("auf", "Dat", "基于", "Die Theorie basiert auf alten Quellen."),),
    "basteln": (("an", "Dat", "制作", "Er bastelt an einem Regal."),),
    "bauen": (("auf", "Akk", "信赖", "Wir bauen auf dich."),),
    "beauftragen": (("mit", "Dat", "委托", "Der Chef beauftragt sie mit der Planung."),),
    "bedenken": (("mit", "Dat", "给予", "Er bedachte sie mit einem Geschenk."),),
    "bedeutsam": (("für", "Akk", "对…重要", "Das ist bedeutsam für unsere Zukunft."),),
    "befangen": (("in", "Dat", "拘泥于", "Er ist in seinen Vorurteilen befangen."),),
    "befassen": (("mit", "Dat", "(sich) 处理", "Sie befasst sich mit diesem Problem."),),
    "befreit": (("von", "Dat", "脱离，免除", "Er ist von allen Ängsten befreit."),),
    "befähigen": (("zu", "Dat", "使能，胜任", "Diese Ausbildung befähigt ihn zu dieser Arbeit."),),
    "begeistert": (("von", "Dat", "对…热情", "Sie ist von dem Film begeistert."), ("über", "Akk", "因…兴奋", "Er ist über das Geschenk begeistert.")),
    "beginnen": (("mit", "Dat", "以…开始", "Die Versammlung beginnt mit einer Rede."),),
    "begrenzt": (("auf", "Akk", "局限于", "Die Teilnehmerzahl ist auf zwanzig begrenzt."),),
    "begründen": (("mit", "Dat", "用…说明理由", "Er begründet seine Entscheidung mit Zeitmangel."),),
    "beharren": (("auf", "Dat", "坚持", "Er beharrt auf seiner Meinung."),),
    "behaupten": (("gegen", "Akk", "(sich) 坚持住", "Er muss sich gegen die Konkurrenz behaupten."),),
    "bekannt": (("für", "Akk", "因…闻名", "Die Stadt ist für ihre Architektur bekannt."),),
    "beliebt": (("bei", "Dat", "受…欢迎", "Sie ist bei ihren Schülern beliebt."),),
    "beraten": (("über", "Akk", "就…咨询", "Wir beraten über den Vertrag."),),
    "berechtigt": (("zu", "Dat", "有权…", "Er ist zu dieser Leistung berechtigt."),),
    "bereit": (("zu", "Dat", "愿意", "Er ist zu einem Kompromiss bereit."),),
    "berichten": (("über", "Akk", "报道…", "Der Reporter berichtet über den Unfall."),),
    "berichteten": (("über", "Akk", "报道…", "Sie berichteten über das Ereignis."),),
    "berücksichtigen": (("bei", "Dat", "在…时考虑", "Er berücksichtigte meine Vorschläge bei der Planung."),),
    "berühmt": (("für", "Akk", "因…而著名", "Sie ist berühmt für ihre Musik."),),
    "beschließen": (("über", "Akk", "就…作出决定", "Der Ausschuss beschloss über den Antrag."),),
    "beschränken": (("auf", "Akk", "(sich)限制在，局限于", "Die Ausgaben beschränken sich auf das Nötigste."),),
    "beschäftigen": (("mit", "Dat", "(sich)从事/研究", "Ich beschäftige mich mit deutscher Literatur."),),
    "besetzen": (("mit", "Dat", "用…填充/配备", "Sie besetzten die Stelle mit einem Experten."),),
    "besetzt": (("mit", "Dat", "被…占据/布满", "Der Platz war mit Menschen besetzt."),),
    "bestehen": (("auf", "Dat", "坚持", "Er besteht auf seiner Meinung."), ("aus", "Dat", "由…组成", "Das Team besteht aus fünf Personen."), ("in", "Dat", "在于", "Die Aufgabe besteht in der Analyse der Daten.")),
    "bestimmt": (("für", "Akk", "为…准备", "Das Geld ist für die Renovierung bestimmt."),),
    "bestrafen": (("für", "Akk", "因…惩罚", "Er wurde für seine Tat bestraft."),),
    "beteiligen": (("an", "Dat", "(sich)参与", "Er beteiligt sich an der Diskussion."),),
    "betrachten": (("als", "Akk", "视为", "Er betrachtet den Plan als einen Fehler."),),
    "betrügen": (("um", "Akk", "骗取", "Er betrog sie um ihr Geld."),),
    "beurteilen": (("nach", "Dat", "依据…评价", "Man beurteilt ihn nach seiner Leistung."),),
    "bewerben": (("um", "Akk", "(sich)申请职位", "Er bewirbt sich um die Stelle."), ("bei", "Dat", "(sich)向…求职", "Sie bewirbt sich bei einer Bank.")),
    "bewerten": (("mit", "Dat", "用…评分", "Die Leistung wird mit Noten bewertet."),),
    "bezahlen": (("für", "Akk", "为…付款", "Er bezahlt für das Essen."),),
    "bieten": (("auf", "Akk", "出价", "Er bietet auf das Gemälde."),),
    "bitten": (("um", "Akk", "请求", "Er bittet mich um Hilfe."),),
    "bleiben": (("bei", "Dat", "坚持", "Er bleibt bei seiner Meinung."),),
    "blind": (("für", "Akk", "对…视而不见", "Er ist blind für seine Fehler."),),
    "brauchbare": (("für", "Akk", "适用于", "Dieses Werkzeug ist brauchbar für Heimwerker."), ("als", "Akk", "可用作", "Dieser Stoff ist brauchbar als Tischdecke.")),
    "brechen": (("mit", "Dat", "与…决裂", "Er brach mit seiner Vergangenheit."),),
    "brennen": (("auf", "Akk", "渴望", "Sie brennt auf die Nachricht."), ("für", "Akk", "为…燃烧", "Er brennt für seine Idee.")),
    "bringen": (("auf", "Akk", "使想到", "Das bringt mich auf eine Idee."), ("um", "Akk", "使失去", "Er brachte ihn um sein Vermögen.")),
    "böse": (("auf", "Akk", "生气", "Sie ist böse auf ihn."),),
    "chatten": (("mit", "Dat", "与…聊天", "Ich chatte mit einem Freund."),),
    "dankbar": (("für", "Akk", "感激", "Ich bin dir für deine Hilfe dankbar."),),
    "danken": (("für", "Akk", "为…感谢", "Ich danke dir für deine Hilfe."),),
    "darstellen": (("als", "Akk", "把…描述为", "Er stellt sich als Held dar."),),
    "dekorieren": (("mit", "Dat", "用…装饰", "Sie dekoriert das Zimmer mit Blumen."),),
    "denken": (("an", "Akk", "想到", "Ich denke oft an meine Familie."),),
    "differenzieren": (("zwischen", "Dat", "区分, 辨别", "Man muss zwischen Tatsachen und Meinungen differenzieren."),),
    "diskutieren": (("über", "Akk", "讨论关于", "Wir diskutieren über das neue Gesetz."), ("mit", "Dat", "与...讨论", "Er diskutiert mit seinem Kollegen.")),
    "dotieren": (("mit", "Dat", "以…支付酬金", "Die Stelle ist mit 6000 Euro dotiert."),),
    "drehen": (("um", "Akk", "围绕, 关系到", "Die Erde dreht sich um die Sonne."),),
    "drücken": (("auf", "Akk", "按, 压", "Drück bitte auf den Knopf."),),
    "durchsetzt": (("mit", "Dat", "夹杂，充满", "Die Luft ist mit Staub durchsetzt."),),
    "durstig": (("nach", "Dat", "渴望", "Er ist durstig nach Wissen."),),
    "ehrlich": (("mit", "Dat", "对…诚实", "Sei ehrlich mit mir!"),),
    "einbinden": (("in", "Akk", "纳入", "Wir binden alle Kollegen in das Projekt ein."),),
    "einbrechen": (("in", "Akk", "闯入", "Die Diebe brachen in das Geschäft ein."),),
    "einfallen": (("in", "Akk", "入侵", "Die Truppen fielen in das Land ein."),),
    "einfügen": (("in", "Akk", "插入", "Bitte fügen Sie das Bild in das Dokument ein."),),
    "einführen": (("in", "Akk", "引入", "Er führte die Gäste in den Saal ein."),),
    "einordnen": (("in", "Akk", "归入", "Bitte ordnen Sie die Akten in den Schrank ein."),),
    "einpacken": (("in", "Akk", "包入", "Sie packte das Geschenk in buntes Papier ein."),),
    "einrichten": (("auf", "Akk", "(sich)做准备", "Wir richten uns auf lange Verhandlungen ein."),),
    "einschalten": (("in", "Akk", "(sich) 干预", "Er schaltet sich in die Diskussion ein."),),
    "einschreiben": (("in", "Akk", "(sich) 报名", "Ich schreibe mich in den Kurs ein."),),
    "einsetzen": (("für", "Akk", "(sich) 致力于", "Er setzt sich für die Umwelt ein."), ("gegen", "Akk", "(sich) 反对", "Sie setzt sich gegen Rassismus ein.")),
    "einsteigen": (("in", "Akk", "登上", "Wir steigen in den Zug ein."),),
    "einstellen": (("auf", "Akk", "(sich) 适应", "Er stellt sich auf die neue Situation ein."),),
    "eintragen": (("in", "Akk", "(sich) 登记", "Er trägt sich in das Gästebuch ein."),),
    "eintreten": (("für", "Akk", "支持", "Er tritt für die Rechte der Arbeiter ein."), ("in", "Akk", "加入", "Sie tritt in den Verein ein."), ("gegen", "Akk", "反对", "Wir treten gegen Gewalt ein.")),
    "einverstanden": (("mit", "Dat", "同意", "Ich bin mit dem Plan einverstanden."),),
    "einverstanden-sein": (("mit", "Dat", "同意", "Sie ist mit dem Vorschlag einverstanden."),),
    "einweihen": (("in", "Akk", "告知，使知晓", "Er weiht mich in das Geheimnis ein."),),
    "einzahlen": (("auf", "Akk", "存入", "Ich zahle Geld auf mein Konto ein."),),
    "einziehen": (("in", "Akk", "搬入", "Sie zieht in die neue Wohnung ein."),),
    "einzuschleusen": (("in", "Akk", "偷运", "Sie versuchen, Waffen in das Land einzuschleusen."),),
    "einzuschleussen": (("in", "Akk", "偷运", "Sie versuchen, Waffen in das Land einzuschleussen."),),
    "empfänglich": (("für", "Akk", "对…敏感", "Sie ist empfänglich für neue Ideen."),),
    "empört": (("über", "Akk", "对…愤怒", "Sie ist empört über die Entscheidung."),),
    "enden": (("mit", "Dat", "以…结束", "Das Fest endet mit einem Feuerwerk."), ("in", "Dat", "以…告终", "Die Straße endet in einer Sackgasse.")),
    "entfernen": (("von", "Dat", "从…移开", "Er entfernte das Etikett von der Flasche."),),
    "entlassen": (("aus", "Dat", "从…放出", "Er wurde aus dem Krankenhaus entlassen."), ("in", "Akk", "使进入退休", "Der Beamte wurde in den Ruhestand entlassen.")),
    "entlehntes": (("aus", "Dat", "从…借用", "Ein entlehntes Wort aus dem Griechischen."),),
    "entlohnen": (("mit", "Dat", "用…酬谢", "Er entlohnt seine Mitarbeiter mit einem Bonus."),),
    "entrüstet": (("über", "Akk", "对…愤慨", "Sie ist entrüstet über die Lüge."),),
    "entscheiden": (("über", "Akk", "决定", "Der Richter entscheidet über den Fall."), ("für", "Akk", "(sich)决定选择", "Ich entscheide mich für das blaue Kleid.")),
    "entschlossen": (("zu", "Dat", "决心…", "Er ist entschlossen zu einem Neuanfang."),),
    "entschuldigen": (("für", "Akk", "(sich)为…道歉", "Ich entschuldige mich für die Verspätung."), ("bei", "Dat", "(sich)向…道歉", "Er entschuldigt sich bei seinem Chef.")),
    "entstehen": (("aus", "Dat", "由…产生", "Aus dem Projekt entstehen viele Ideen."),),
    "entwickeln": (("zu", "Dat", "(sich)发展成", "Die Stadt entwickelt sich zu einem Zentrum."),),
    "erfahren": (("von", "Dat", "得知", "Ich habe von dem Unfall erfahren."),),
    "ergänzen": (("um", "Akk", "补充…", "Wir ergänzen das Team um zwei Leute."),),
    "erinnern": (("an", "Akk", "(sich)记得", "Ich erinnere mich an den Tag."),),
    "erklären": (("für", "Akk", "宣布为", "Die Regierung erklärte den Vertrag für ungültig."), ("zu", "Dat", "任命为", "Sie erklärte ihn zu ihrem Stellvertreter.")),
    "ermitteln": (("gegen", "Akk", "调查", "Die Polizei ermittelt gegen den Verdächtigen."),),
    "ernst": (("mit", "Dat", "对…认真", "Er ist ernst mit seiner Arbeit."),),
    "ernähren": (("von", "Dat", "(sich) 以…为食", "Er ernährt sich von Obst und Gemüse."),),
    "erschrecken": (("über", "Akk", "对…感到惊吓", "Ich erschrak über die laute Stimme."), ("vor", "Dat", "被…吓到", "Das Kind erschrickt vor dem lauten Hund.")),
    "erschüttert": (("über", "Akk", "对…感到震惊", "Sie war über die Nachricht zutiefst erschüttert."),),
    "ersetzen": (("durch", "Akk", "用…替换", "Wir ersetzen das alte Gerät durch ein neues."),),
    "erwachsen": (("aus", "Dat", "由…产生", "Aus dem Konflikt erwachsen neue Probleme."), ("zu", "Dat", "成长为", "Sie ist zu einer starken Persönlichkeit erwachsen.")),
    "erwarten": (("von", "Dat", "对…有期望", "Das erwarte ich von dir."),),
    "erziehen": (("zu", "Dat", "培养成…", "Sie erzieht ihr Kind zu einem selbstbewussten Menschen."),),
    "erzählen": (("von", "Dat", "讲述…", "Er erzählt von seiner Reise durch Europa."), ("über", "Akk", "谈论…", "Sie erzählt über ihre Arbeit in der Firma.")),
    "fallen": (("unter", "Akk", "属于", "Das fällt unter das Urheberrecht."),),
    "fehlen": (("an", "Dat", "缺少", "Es fehlt an Geld."),),
    "feindselig": (("gegenüber", "Dat", "敌视", "Sie ist feindselig gegenüber ihren Kollegen."),),
    "feindselige": (("gegenüber", "Dat", "敌视", "Sie ist feindselig gegenüber ihren Kollegen."),),
    "fertig": (("mit", "Dat", "完成，结束", "Ich bin endlich mit der Arbeit fertig."), ("für", "Akk", "准备好", "Wir sind fertig für den großen Tag.")),
    "fertig-sein": (("mit", "Dat", "完成", "Er ist mit der Arbeit fertig."),),
    "festhalten": (("an", "Dat", "坚持", "Sie hält an ihrer Meinung fest."),),
    "festlegen": (("auf", "Akk", "确定", "Er legt sich auf den Termin fest."),),
    "fit-sein": (("für", "Akk", "为…做好准备", "Er ist fit für die Prüfung."), ("in", "Dat", "擅长", "Sie ist fit in Mathe.")),
    "fliehen": (("vor", "Dat", "逃离，躲避", "Die Menschen fliehen vor dem Krieg."),),
    "folgen": (("auf", "Akk", "紧跟其后", "Der Sommer folgt auf den Frühling."), ("aus", "Dat", "源于", "Das folgt aus den Fakten.")),
    "folgenreich": (("für", "Akk", "对…影响深远", "Der Krieg war folgenreich für Europa."),),
    "fordern": (("von", "Dat", "向…要求", "Ich fordere eine Antwort von dir."),),
    "fragen": (("nach", "Dat", "询问，打听", "Er fragt nach dem Weg."), ("um", "Akk", "请求得到", "Sie fragt um Hilfe.")),
    "frech": (("zu", "Dat", "对…无礼", "Der Junge war frech zu seiner Lehrerin."),),
    "fressen": (("an", "Dat", "啃，侵蚀", "Der Hund frisst an einem Knochen."),),
    "freuen": (("auf", "Akk", "(sich)期待", "Ich freue mich auf die Ferien."), ("über", "Akk", "(sich)为…高兴", "Sie freut sich über das Geschenk.")),
    "freundlich": (("zu", "Dat", "对…友好", "Sie ist freundlich zu allen Gästen."),),
    "froh": (("über", "Akk", "对…感到高兴", "Ich bin froh über deine Hilfe."),),
    "fähig": (("zu", "Dat", "有能力", "Er ist zu großen Leistungen fähig."),),
    "führen": (("zu", "Dat", "导致", "Das führt zu vielen Problemen."),),
    "garantieren": (("für", "Akk", "为…担保", "Die Firma garantiert für die Qualität."),),
    "geboren": (("für", "Akk", "天生适合", "Du bist für diesen Beruf geboren."),),
    "geeignet": (("für", "Akk", "适合", "Dieser Kurs ist für Anfänger geeignet."), ("zu", "Dat", "适于", "Er ist zu dieser Aufgabe geeignet.")),
    "gefährlich": (("für", "Akk", "对…危险", "Rauchen ist für die Gesundheit gefährlich."),),
    "gegensteuern": (("gegen", "Akk", "对…采取对策", "Wir müssen gegen die Inflation gegensteuern."),),
    "gehen": (("um", "Akk", "涉及", "Es geht um die wichtigste Frage."),),
    "gehören": (("zu", "Dat", "属于", "Dieses Buch gehört zu meiner Sammlung."),),
    "gelegen": (("an", "Dat", "重视，在乎", "Mir ist an einer Lösung gelegen."),),
    "gelten": (("für", "Akk", "适用于", "Das gilt für alle Teilnehmer."),),
    "gepflastert": (("mit", "Dat", "铺有，用…铺", "Der Weg ist mit Kies gepflastert."),),
    "geprüft": (("auf", "Akk", "检测，检验", "Die Probe wird auf Bakterien geprüft."),),
    "gerecht": (("gegenüber", "Dat", "对…公正", "Er ist gerecht gegenüber allen Mitarbeitern."),),
    "geschieden": (("von", "Dat", "与…离婚的", "Er ist von seiner Frau geschieden."),),
    "gespannt": (("auf", "Akk", "对…期待/好奇", "Ich bin gespannt auf das Ergebnis."),),
    "gesperrt": (("für", "Akk", "对…封锁", "Die Straße ist für den Verkehr gesperrt."),),
    "gewinnen": (("an", "Dat", "在…方面增长", "Das Projekt gewinnt an Bedeutung."), ("gegen", "Akk", "战胜…", "Die Mannschaft gewann gegen den Gegner.")),
    "gewohnt": (("an", "Akk", "习惯于…的", "Er ist an die Kälte gewohnt."),),
    "gewöhnen": (("an", "Akk", "(sich)习惯于", "Ich gewöhne mich an das Klima."),),
    "glauben": (("an", "Akk", "相信", "Sie glaubt an den Erfolg."),),
    "glücklich": (("über", "Akk", "对…高兴", "Sie ist glücklich über das Geschenk."),),
    "gratulieren": (("zu", "Dat", "祝贺", "Wir gratulieren ihr zu ihrem Erfolg."),),
    "greifen": (("nach", "Dat", "抓取", "Er greift nach dem Glas."),),
    "gründen": (("auf", "Akk", "(sich)基于", "Das Argument gründet sich auf Fakten."),),
    "gut": (("in", "Dat", "擅长", "Er ist gut in Mathe."), ("zu", "Dat", "对…好", "Sie ist gut zu ihren Kindern."), ("für", "Akk", "对…有益", "Das ist gut für deine Gesundheit.")),
    "gültig": (("für", "Akk", "对…有效", "Dieser Ausweis ist gültig für zwei Jahre."),),
    "gültig-sein": (("für", "Akk", "对…有效", "Der Vertrag ist gültig für ein Jahr."),),
    "günstig": (("für", "Akk", "对…有利", "Das Angebot ist günstig für uns."),),
    "haltbar": (("für", "Akk", "可保存", "Die Milch ist haltbar für drei Tage."),),
    "halten": (("für", "Akk", "把…看作", "Ich halte ihn für einen Lügner."), ("von", "Dat", "对…的看法", "Was hältst du von dem neuen Film?"), ("auf", "Akk", "重视", "Er hält auf sein Äußeres."), ("zu", "Dat", "忠于", "Er hält zu seinem Freund.")),
    "handeln": (("von", "Dat", "涉及", "Das Buch handelt von einem Drachen."), ("mit", "Dat", "交易", "Er handelt mit antiken Möbeln."), ("um", "Akk", "涉及(sich)", "Es handelt sich um ein wichtiges Thema.")),
    "hart": (("zu", "Dat", "对…严厉", "Der Lehrer ist hart zu den Schülern."),),
    "hassen": (("an", "Dat", "讨厌…的方面", "Ich hasse an ihm seine Ungeduld."),),
    "heiß": (("auf", "Akk", "渴望", "Ich bin heiß auf das Konzert."),),
    "helfen": (("bei", "Dat", "帮忙做", "Er hilft mir bei den Hausaufgaben."),),
    "herrscht": (("über", "Akk", "统治", "Der König herrscht über das Land."),),
    "hindeute": (("auf", "Akk", "表明", "Die Daten deuten auf eine Besserung hin."),),
    "hineinfuchsen": (("in", "Akk", "(sich)钻研", "Er fuchst sich in die Mathematik hinein."),),
    "hinweisen": (("auf", "Akk", "指出", "Er weist auf den Fehler hin."),),
    "hinzufügen": (("zu", "Dat", "添加到", "Fügen Sie Wasser zu der Suppe hinzu."),),
    "hinzukommen": (("zu", "Dat", "添加到", "Zu den Kosten kommt ein Aufschlag hinzu."),),
    "hoffen": (("auf", "Akk", "希望", "Wir hoffen auf besseres Wetter."),),
    "hungrig": (("nach", "Dat", "渴望", "Er ist hungrig nach Erfolg."),),
    "hängen": (("an", "Dat", "依恋", "Sie hängt sehr an ihrer Mutter."),),
    "höflich": (("zu", "Dat", "对…有礼貌", "Er ist höflich zu seinen Gästen."),),
    "hören": (("auf", "Akk", "听从", "Er hört auf seinen Vater."), ("von", "Dat", "听说", "Ich habe von dem Unfall gehört.")),
    "ideal": (("für", "Akk", "适合", "Dieses Buch ist ideal für Anfänger."),),
    "infizieren": (("mit", "Dat", "(sich) 感染上", "Er hat sich mit dem Virus infiziert."),),
    "informieren": (("über", "Akk", "通知；告知", "Wir informieren die Gäste über die Terminänderung."),),
    "integrieren": (("in", "Akk", "使融入/整合", "Wir müssen die Flüchtlinge in die Gesellschaft integrieren."),),
    "interagieren": (("mit", "Dat", "与…互动", "Der Lehrer interagiert mit den Schülern."),),
    "interessant": (("für", "Akk", "对…有趣", "Das Angebot ist interessant für Kunden."),),
    "interessieren": (("für", "Akk", "(sich)对…感兴趣", "Er interessiert sich für Politik."),),
    "interessiert": (("an", "Dat", "对…感兴趣", "Sie ist an Technik interessiert."),),
    "interpretieren": (("als", "Akk", "解释为", "Sie interpretierte seine Worte als Kritik."),),
    "jammern": (("über", "Akk", "抱怨", "Sie jammerte über den hohen Preis."),),
    "kapitulieren": (("vor", "Dat", "向…投降", "Er kapitulierte vor der Schwierigkeit."),),
    "klagen": (("über", "Akk", "抱怨", "Sie klagt über die lautstarke Musik."), ("gegen", "Akk", "控告", "Er klagt gegen seinen Nachbarn."), ("auf", "Akk", "索赔", "Der Anwalt klagt auf Schadenersatz.")),
    "klar": (("über", "Akk", "(sich) 意识到", "Ich bin mir über die Risiken klar."),),
    "kleben": (("an", "Dat", "粘在…上", "Der Aufkleber klebt an der Tür."),),
    "klicken": (("auf", "Akk", "点击", "Klicken Sie auf den Link."),),
    "klingen": (("nach", "Dat", "听起来像", "Das klingt nach einem guten Plan."),),
    "klopfen": (("an", "Akk", "敲击", "Er klopft an die Tür."),),
    "knapp": (("an", "Dat", "缺乏", "Wir sind knapp an Zeit."),),
    "kommen": (("auf", "Akk", "想到", "Ich komme auf eine gute Idee."), ("zu", "Dat", "达到", "Wir kommen zu einem Ergebnis."), ("um", "Akk", "失去", "Er kam um sein Leben."), ("über", "Akk", "侵袭", "Eine große Freude kam über mich.")),
    "kontrollieren": (("auf", "Akk", "检查有无", "Der Arzt kontrolliert den Patienten auf Symptome."),),
    "kramen": (("in", "Dat", "翻找", "Sie kramt in ihrer Handtasche."),),
    "krank": (("an", "Dat", "患…病", "Er ist an Tuberkulose krank."),),
    "kratzen": (("an", "Dat", "抓挠", "Die Katze kratzt an der Tür."),),
    "kritisch": (("gegenüber", "Dat", "对…持批判", "Sie ist kritisch gegenüber dem Plan."),),
    "kämpfen": (("für", "Akk", "为...战斗", "Er kämpft für seine Rechte."), ("gegen", "Akk", "反对...", "Wir kämpfen gegen die Verschmutzung."), ("um", "Akk", "争夺", "Sie kämpfen um den Titel."), ("mit", "Dat", "与...斗争", "Ich kämpfe mit meiner Angst.")),
    "kümmern": (("um", "Akk", "(sich)照顾", "Sie kümmert sich um die Kinder."),),
    "lachen": (("über", "Akk", "嘲笑", "Wir lachen über den Witz."),),
    "leben": (("von", "Dat", "靠…生活", "Er lebt von seinem Gehalt."), ("für", "Akk", "为…而活", "Sie lebt für die Musik."), ("mit", "Dat", "与…一起生活", "Sie lebt mit ihrer Familie.")),
    "leer": (("an", "Dat", "缺乏", "Das Hotel ist leer an Gästen."),),
    "leiden": (("an", "Dat", "患（病）", "Er leidet an einer Allergie."), ("unter", "Dat", "受…之苦", "Sie leidet unter dem Lärm.")),
    "lieb": (("zu", "Dat", "对…友好", "Er ist lieb zu seiner Schwester."),),
    "liegen": (("an", "Dat", "取决于", "Das liegt an dir."), ("in", "Dat", "在于", "Das Problem liegt in der Planung.")),
    "loben": (("für", "Akk", "因…表扬", "Der Lehrer lobt den Schüler für die Arbeit."),),
    "müde": (("von", "Dat", "因...而累", "Er ist müde von der langen Reise."),),
    "neugierig": (("auf", "Akk", "好奇", "Ich bin neugierig auf das Ergebnis."),),
    "protestieren": (("gegen", "Akk", "抗议...", "Die Bürger protestieren gegen die Steuererhöhung."),),
    "rechnen": (("mit", "Dat", "预计", "Wir rechnen mit Regen."),),
    "schützen": (("vor", "Dat", "保护免受", "Die Creme schützt vor der Sonne."),),
    "sorgen": (("für", "Akk", "照料/负责", "Sie sorgt für ihre kranke Mutter."), ("um", "Akk", "(sich)担心", "Ich sorge mich um dich.")),
    "sprechen": (("über", "Akk", "谈论", "Wir sprechen über die Prüfung."), ("mit", "Dat", "与…交谈", "Ich spreche mit dem Lehrer."), ("von", "Dat", "提到", "Sie spricht oft von ihrer Reise.")),
    "stolz": (("auf", "Akk", "为…自豪", "Die Eltern sind stolz auf ihre Tochter."),),
    "teilnehmen": (("an", "Dat", "参加", "Sie nimmt an der Konferenz teil."),),
    "träumen": (("von", "Dat", "梦想", "Sie träumt von einer Weltreise."),),
    "unterhalten": (("über", "Akk", "(sich)聊起", "Wir unterhalten uns über Musik."),),
    "verantwortlich": (("für", "Akk", "对…负责", "Sie ist für das Projekt verantwortlich."),),
    "verlassen": (("auf", "Akk", "(sich)信赖", "Du kannst dich auf mich verlassen."),),
    "verzichten": (("auf", "Akk", "放弃", "Wir verzichten auf den Urlaub."),),
    "vorbereiten": (("auf", "Akk", "(sich)为…做准备", "Ich bereite mich auf die Prüfung vor."),),
    "warten": (("auf", "Akk", "等待", "Ich warte auf den Bus."),),
    "zufrieden": (("mit", "Dat", "满意", "Ich bin mit dem Ergebnis zufrieden."),),
    "zweifeln": (("an", "Dat", "怀疑", "Er zweifelt an seiner Entscheidung."),),
    "ärgern": (("über", "Akk", "(sich)为…生气", "Er ärgert sich über den Fehler."),),
    "überzeugt": (("von", "Dat", "确信", "Er ist von seiner Idee überzeugt."),),
}
