plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'org.delector.app'
    compileSdk 34

    defaultConfig {
        applicationId "org.delector.app"
        minSdk 24
        targetSdk 34
        versionCode 350
        versionName "3.5.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86_64"
        }

        python {
            version "3.10"
            pip {
                install "fastapi>=0.109.0"
                install "uvicorn>=0.27.0"
                install "httpx>=0.26.0"
                install "genanki>=0.13.0"
                install "spacy>=3.7.0"
                install "https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.7.0/de_core_news_sm-3.7.0-py3-none-any.whl"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.webkit:webkit:1.10.0'
}
